### ISSUE TITLE
Image doesn't get added to the position of the cursor

### ISSUE THREAD

**Issue by bhupesh-sf** [penge/my-notes#103]
Whenever I try to add an image it will gets added to the beginning of the note not where the cursor is right now.

**Comment by penge** [comment]
Cool, thanks for reporting. I gonna fix that in 3.2.

**Comment by penge** [comment]
I would like to extend this issue.

Not only that Image gets inserted at the cursor position (original issue), but also cursor position is restored on Cancel.

**Comment by penge** [comment]
**Fixed!**
