### ISSUE TITLE
Unable to paste Hex code while setting background color in custom theme option

### ISSUE THREAD

**Issue by bhupesh-sf** [penge/my-notes#104]
Unable to paste Hex code while setting background color in custom theme option

**Comment by penge** [comment]
It is the limitation of the color picker (more here https://www.w3schools.com/colors/colors_picker.asp).

In 3.2 this will be resolved as there will be a new way to customize the theme, much more rich (from 2 things to over 30) via an editor.

**Comment by bhupesh-sf** [comment]
Awesome. Holding my heart ;)

**Comment by penge** [comment]
Done! :)
