### ISSUE TITLE
Decouple Themes, improve Custom theme customization

### ISSUE THREAD

**Issue by penge** [penge/my-notes#107]
Themes in 3.2 will be vastly improved as they will be decoupled from the rest (making them interchangeable).

The new editor in 3.2 will allow to set a Custom theme in a much more rich way.

**Before:**

- can set custom background color
- can set custom text color

**Coming next:**

- can set just about 30+ properties (from background color and text color, to border colors, other background colors, fill colors, hover colors, etc.)

The main purpose of themes decoupling (and the new editor), is to allow easy and rich customization (either via an editor, or a fork); and open the opportunities to the community to create and share the custom themes.

**Comment by bhupesh-sf** [comment]
I liked the idea of decoupling themes as it gives flexibility to share their tried out themes.

**Comment by penge** [comment]
Yep! We could then share the themes via **gist**, or own **repositories**.

**Comment by penge** [comment]
Done! 3.2 is around the corner!

**Comment by penge** [comment]
Here's a screenshot of new customization!

<img width="1411" alt="custom" src="https://user-images.githubusercontent.com/907255/85074817-78181180-b1bd-11ea-9af8-2a7f9540a210.png">

There's around 40 custom properties you can set.

**Comment by bhupesh-sf** [comment]
One sample of your favorite settings will be good to start ;)
