### ISSUE TITLE
Restore H2 and H3 headings

### ISSUE THREAD

**Issue by robaone** [penge/my-notes#111]
Version 3.2 removed the ability to create H2 and H3 headings.
Please restore that ability.  It is very useful.

**Comment by penge** [comment]
Hi Ansel,

Thank you for your feedback. No problem. I will bring it back, you could have it by Friday.

**Comment by robaone** [comment]
Wow! Amazing.  Thank you so much.  I appreciate your work.

**Comment by penge** [comment]
Thank you Ansel,

I have the new version ready. I will publish it on Web Store (review takes usually about 10-15 hours) later, as unfortunately, there is some issue with the Web Store right now (more here https://stackoverflow.com/questions/62587562/unable-to-submit-internal-error-chrome-store-extension-submission), which prevents to submit an extension. Hopefully later today it will be working again. Sorry for the interruption.

**Comment by robaone** [comment]
Amazing.  Thank you again.  This is great!
