### ISSUE TITLE
Option to preserve format (or not) when copy/pasting

### ISSUE THREAD

**Issue by lambdamusic** [penge/my-notes#118]
In previous versions, I could rely on the extension tab to always be using the selected font. Kind of 'plain text' copy. 

Now it seems to preserve some formatting, sometimes with errors. 

Think it'd be useful to have an option to disable that.

**Comment by penge** [comment]
Hi, have you tried these shortcuts? Is it helpful?

- `⌘ + v` or `Ctrl + v` — Paste (preserves formatting)

- `⌘ + Shift + v` or `Ctrl + Shift + v` — Paste as plain text (resets formatting)

**Comment by lambdamusic** [comment]
thanks! I'll try that

**Comment by penge** [comment]
hi @lambdamusic, did the shortcut help?

**Comment by lambdamusic** [comment]
yes it did! thanks, I'm closing the issue if that's ok
