### ISSUE TITLE
Customize shortcuts 

### ISSUE THREAD

**Issue by lambdamusic** [penge/my-notes#120]
The default shortcuts can be in conflict with other user-assigned shortcuts. 

It would then be useful if we could customize them (as with Open My Notes). Any thoughts? 

![image](https://user-images.githubusercontent.com/3493663/88513813-4a5a8f80-cfe9-11ea-9d2e-3439c2ea6274.png)

**Comment by penge** [comment]
Hi, I'll try to look at it. Which shortcut is causing a conflict?

**Comment by penge** [comment]
@lambdamusic

**Comment by penge** [comment]
@lambdamusic Maybe this is not longer an issue in 3.4.1 which is released today. Let me know.
