### ISSUE TITLE
Words corrected through spell checker revert to same after page refresh

### ISSUE THREAD

**Issue by bhupesh-sf** [penge/my-notes#121]
If I have misspelled a word and if I use the spell checker feature which is native and corrects the word, it doesn't stay. As soon as I refresh the page OR close and reopen the notes, the same misspelled words are there again.

**Comment by penge** [comment]
Thank you very much for the finding. I'll give this priority and try to find a solution to that. As a temporary solution, please type in something manually to confirm these auto corrections which seem not to be detected as a change. In the next version, this workaround shouldn't be needed.

**Comment by penge** [comment]
@bhupesh-sf Fix is on the way and it will be available starting next week.

**Comment by bhupesh-sf** [comment]
Awesome
