### ISSUE TITLE
Filter notes by title

### ISSUE THREAD

**Issue by bhupesh-sf** [penge/my-notes#122]
I am having a good list of notes which I am managing through this app. I think this is will be good enhancement to have where I can do some kind of typeahead and get a filtered list of notes for easy access.

Searching through the notes will be even great but that can be later (if possible)

**Comment by penge** [comment]
How many notes do you have? How often do you switch between them?

**Comment by bhupesh-sf** [comment]
@penge I am having around 20 as of now but they are going to grow. Point is whenever I need to get into a note I have to look through the list and figure if there is a textbox where I can just write something and it filters out.

**Comment by penge** [comment]
@bhupesh-sf 

ok, what would you say about this?

You would press `⌘ + p` (like in VSCode), and at the top of the current note, an input would show up and as you type, it would show suggestions of notes that meet the criteria.

Other suggestions?

**Comment by bhupesh-sf** [comment]
@penge 1st option is obviously the best as it matches the our day to day pattern of working with VSCode but even the second one is all good. I think now it's your choice of what you feel the easiest and the best.

**Comment by penge** [comment]
I'll check what can I do. Maybe try both options.

**Comment by bhupesh-sf** [comment]
@penge Any plan to pick this up sooner as the list is increasing :zany_face:

**Comment by penge** [comment]
I don't find filter by Title particularly useful as notes are sorted by their name and two can be easily switched using the browser's Back and Forward buttons.

Some kind of Search in content across all notes, sounds better to me.

**Comment by penge** [comment]
Closing as [Command palette](https://github.com/penge/my-notes/issues/234) will be a nice solution to this.
