### ISSUE TITLE
Ability to give a color to a specific text

### ISSUE THREAD

**Issue by bhupesh-sf** [penge/my-notes#127]
Just like we can select a word and sentence and make it bold, italic etc similarly it will be a good option to give different color to that particular text to have better highlighting of the text.

**Comment by shaambhav** [comment]
Any update on this feature? Colours help me remember stuff more easily. I'll be able to categorise topics by colour or highlight on the basis of importance level. 
Highly important could be = Yellow
Mildly important could be = Orange
something like that

**Comment by penge** [comment]
Creating a new milestone for it – 3.8.

As I see it, there would be several standard colors, **Yellow** and **Orange** among them. This would allow to quickly pick and use the color. In future on in the same version, there would be option to define up to 3 custom colors.

**Comment by penge** [comment]
@bhupesh-sf @shaambhav 
This feature will be relased next week.
