### ISSUE TITLE
Open My Notes in every New Tab Does Not Work in Edge Browser

### ISSUE THREAD

**Issue by twocs** [penge/my-notes#128]
Edge Browser now has access to the Chrome Store. When I installed the My Notes extension, it asked permission (and I granted it).

However, when I open a new tab, I'm unable to see My Notes. It doesn't seem to work in Edge

Previously I had [Daily Unlearnings ](https://chrome.google.com/webstore/detail/daily-unlearnings/dfnjmmhkdljagjpneebefnipjnhhdlad) installed, which also replaces the new tab functionality and works in Edge.

**Comment by penge** [comment]
At this point, only Google Chrome is fully supported. I think Edge Browser is a good candidate to be supported as well.

All the features, maybe except the Google Drive Sync, should be possible to have in Edge Browser.

I will look at it, and extend the support to Edge Browser if possible, as much as possible.

**Comment by twocs** [comment]
Just thought I should mention that My Notes does work in Edge Browser.
Assigning a keyboard via edge://extensions/shortcuts also works to open My Notes.

**Comment by penge** [comment]
Thank you mentioning. I am glad it works in Edge. We can now confirm `edge://extensions/shortcuts` works as `chrome://extensions/shortcuts`.

Having some great news btw! Found the spot (a difference) how to fix "Open My Notes in every New Tab" for Edge. Already tried it and it works.

As soon as 3.4.3 is released, I will release 3.4.4 that fixes this issue. Should be someday this week.
