### ISSUE TITLE
Reorder notes?

### ISSUE THREAD

**Issue by DrostDrafting** [penge/my-notes#129]
Is there a way to reorder the notes. instead if automatically being alphabetical?

**Comment by penge** [comment]
This sounds like an interesting idea. What would you say about having an option (in Options page), to select the order which you would like to use, let it be either alphabetical, or custom. If custom, then reordering would become possible.

Definitely considering to add this.

**Comment by DrostDrafting** [comment]
Simple drag it in the list to where you want it or sort like windows explorer? By the way, this app is awesome!




Thank you,




Scott Drost via Android


Drost Drafting Services


(715) 773-0358







On Wed, Oct 7, 2020 at 6:27 PM -0500, "Pavel Bucka" <notifications@github.com> wrote:















This sounds like an interesting idea. What would you say about having an option (in Options page), to select the order which you would like to use, let it be either alphabetical, or custom. If custom, then reordering would become possible.


Definitely considering to add this.

**Comment by penge** [comment]
Thanks you! The Drag and Drop sounds cool. I think I'll be adding it!

**Comment by penge** [comment]
Thank you! The Drag and Drop sounds cool. I think I'll be adding it!
