### ISSUE TITLE
Sync to same "Notepad" from two different signed in Google accounts?

### ISSUE THREAD

**Issue by EskarGo** [penge/my-notes#130]
The app is great, I just wish I could hit "new tab" and access the same Notepad whether I'm signed into my account, or my work account. Is there any way to add a way to choose which Google account I'd like to sync My Notes with?

**Comment by penge** [comment]
As of right now, the implementation relies on Google API (more here: https://developer.chrome.com/extensions/devguide) which doesn't provide such a functionality. Meaning, it uses the currently signed profile. Would love to see it improved though and I think this profile selection would be really nice to have.
