### ISSUE TITLE
Enable Google Drive Sync and Open My Notes in every New Tab options inoperable

### ISSUE THREAD

**Issue by GilaSki** [penge/my-notes#131]
Just installed My Notes. Set up a My Notes folder in my G-drive. Clicking **Enable Google Drive Sync** option does noting. No check mark, no sync no matter how many times I attempt to check that check box. Rebooted browser (Microsoft Edge), but this option still not functioning.

Also, I was able to select the **Open My Notes in every New Tab** option, but opening a new tab (Edge browser) does not open to My Notes.

MacBook Pro, Catalina 10.15.7.

**Comment by penge** [comment]
Related to https://github.com/penge/my-notes/issues/128.

Current support is Google Chrome only. But looking forward to extend it to Edge Browser as well.

**Comment by kaba72** [comment]
I am having the same issue in Brave - I can activate the "new tab" option which works just fine, but the "sync to google drive" doesn't react to me trying to tick the box.  I thought Brave and Chrome were sufficiently similar/identical for all extensions to work across them.

**Comment by penge** [comment]
Hi, unfortunately in Brave, GAIA (Google Accounts and ID Administration) calls are blocked, and therefore My Notes is unable to authenticate and enable Google Drive Sync.

**Comment by robbielink** [comment]
I was trying to use it in Vivaldi browser (also based on Chrome) and was able to check the box but then when it went to Google to authenticate got an error message: "404. That’s an error.The requested URL was not found on this server. That’s all we know." Is this the same problem as the others here or a different one?

**Comment by penge** [comment]
I will try to get Vivaldi and find the reason there.

**Comment by robbielink** [comment]
Thanks for checking. I seem to remember I had tried another extension which needed to access Google Drive and ran into the same problem on Vivaldi. Worked on Chrome but I prefer Vivaldi.

**Comment by penge** [comment]
Hi Robbie,

I will try my best to bring the support to Vivaldi as well. (if possible)

Pavel
