### ISSUE TITLE
Cannot delete or rename "Clipboard" note

### ISSUE THREAD

**Issue by kankaristo** [penge/my-notes#132]
I'd like to use a different name for the "default" note, which is currently named "Clipboard".

Confusingly, the app allows you to *try* to delete it or rename it, but nothing happens (no error either, not even in the console).

I'd like to rename "Clipboard" to something like "@Scratchpad", so that it would be always be first in an alphabetized list, and because "Clipboard" sounds to me like it would be synced with the contents of my actual (copy and paste) clipboard.

**Comment by penge** [comment]
Hi Sami,

That's a good point. Clipboard is not possible to rename or delete, because
it is needed for My Notes Context menu to work (read here:
https://github.com/penge/my-notes#context-menu)

I agree there should be no options to rename or delete, because it's locked
from doing so.
Instead, there could be a message like: "Clipboard cannot be renamed or
deleted because it's needed by My Notes Context menu."

What do you think?

Pavel

**Comment by kankaristo** [comment]
Ah, I thought this was a bug, since the option was there, and there was no message saying why it cannot be renamed or deleted. :)

It would still be nice to be able rename it, although I understand needing to have a "default" note which would receive text sent from the context menu.

Maybe a "Set as default" menu option when right-clicking on a note, so the "Clipboard" name wouldn't be fixed?

Or always showing "Clipboard" as the first note in the list, and showing the rest of the list in an alphabetized order?

**Comment by penge** [comment]
Can I ask you to add this as a new issue? I think the suggestions are
really cool and the conversation could be moved there.
What I think could be best, is to have the ability to promote a certain
note to be a Clipboard.
And if this note is called differently in computer A, and B, it wouldn't
really matter.

What do you think?

**Comment by penge** [comment]
@kankaristo 

> Confusingly, the app allows you to _try_ to delete it or rename it, but nothing happens (no error either, not even in the console).

There's version 3.4.2 on the way that doesn't show the context menu for the Clipboard. It had no purpose in that case.

> I'd like to rename "Clipboard" to something like "@scratchpad", so that it would be always be first in an alphabetized list, and because "Clipboard" sounds to me like it would be synced with the contents of my actual (copy and paste) clipboard.

I find the ability to rename the Clipboard also important. Having some questions:

1. How would you name "Clipboard" differently for those who installed My Notes for the first time?

2. Let's consider other approach. I was now thinking about a very different approach. The idea arrived to me when I saw the "@scratchpad" and immediately thought of a "dropzone" (or "received") that doesn't really need to have a name. All sorts of problems would go away like "Promote note to a Clipboard", and something to identify which note is Clipboard. Imagine having a dropzone icon in the sidebar at the bottom where the other icons are.

It solves some things, but also takes away some flexibility. In the end, it would have to be considered to have some name in Google Drive, a name that is not in conflict with some existing note. Any suggestions?

**Comment by penge** [comment]
Hi @kankaristo 

Here's a first visual prototype:

<img width="724" alt="dropzone" src="https://user-images.githubusercontent.com/907255/95687919-deaaba80-0c06-11eb-821f-b0b113f2adbd.png">

Details:

- Note that serves as a dropzone (before Clipboard) has an icon on the right that signals it can receive things
- Only one note can serve as a dropzone
- Context menu has an option to use a note as a dropzone
- On other computer, dropzone can be a differently named note
- "Clipboard" can be renamed and deleted

Special case: No note was selected to be a dropzone, or it was deleted.
Possible solution: The first note in the list should be promoted to take on this role so it can receive the text.

Question: What should be the name of the note, that has a dropzone role after the first installation?
Now it is: [Clipboard, One, Two, Three]
It can be: [Dropzone, One, Two, Three]

@kankaristo What are your thoughts on this?

**Comment by kankaristo** [comment]
@penge, that sounds great!

One change suggestion: it might be better to create a new note called "Dropzone", if the current dropzone is somehow deleted.

Promoting some random note to be the dropzone might be confusing to the user. And in the case where all notes are deleted, you would have to create a new note, anyway. Always creating a new dropzone note if the old one was deleted, would ensure that the user's notes are never accidentally overwritten.

If the dropzone note is deleted, and a note named "Dropzone" already exists, it might still be best to create a new note, appending a random string or running integer (e.g. "Dropzone-83oe5w", "Dropzone-2").

(If a note named "Dropzone" already exists, it could alternatively be promoted to be the dropzone, but a user might want to use that note as the dropzone for computer A, and want to use some other note as the dropzone for computer B. So, it might be safest to always create a new dropzone note if the old one was deleted. That way, the app would always work the same way, less edge cases.)

**Comment by penge** [comment]
@kankaristo Thanks! I like your feedback.

I agree no random note should be promoted as a Dropzone, even if the note with that name exists.

There would be no Dropzone created if one was deleted. User might not want to use that feature.

If Dropzone is about to be used and it doesn't exist, only then it's automatically created.

There could be only one Dropzone. It can have any name.

Clipboard can be deleted/renamed.

**Q:**

1. What name do you like more? Dropzone, or Default? I think Default doesn't say much. Dropzone - it's cool.

2. What would you say about having a Dropzone underlined, always as the first? No additional icons around needed.

3. Would you agree to have these notes after the first installation?
[Dropzone, One, Two, Three]

The thing I like about the name Dropzone, it's clear what it does. Or at least. It can be easily described or referenced in the docs.

**Comment by kankaristo** [comment]
1. Dropzone sounds good to me (can't think of a more descriptive name).
2. An icon might still be useful, and hovering on top of the icon could show a tooltip describing why this note is "special".
    - Underlining might make it look like it's somehow "active" (selected, hovered, etc.), even when it's not.
    - Listing it first would still be great. For me, that's a big reason why I'd like to rename it, so it's listed first (with the current alphabetized listing).
3. Those sound like good defaults.

**Comment by penge** [comment]
Great! I'll keep this in mind and try to add the icon with a descriptive tooltip, no underline, and having dropzone as a first note.

Will share the updates when ready.

**Comment by penge** [comment]
@kankaristo and @nathancarter

I am glad to announce that 3.5 will be released tomorrow. On Web Store it should be by Tuesday, Wednesday.

**What's expected:**

- can rename or delete Clipboard
- any other note can be set as Clipboard
- Clipboard icon to know which note is Clipboard note, if any

Other small improvements expected as well.

**Comment by kankaristo** [comment]
@penge, got the update today, looking good! Saving the URL when sending text to the clipboard is really useful, that will probably make me use it a lot more.
