### ISSUE TITLE
Markdown support?

### ISSUE THREAD

**Issue by kankaristo** [penge/my-notes#133]
I'm used to using Markdown for simple text styling. It's widely used on WhatsApp, Slack, and even here on GitHub.

And since My Notes syncs to Google Drive as plain text files (instead of e.g. Google Docs documents), they would be much easier to edit, if they used Markdown instead of HTML.

Markdown could be an alternative available through the settings, instead of a replacement for the current styling, since some people might also prefer that.

UI/UX suggestion: since Markdown has to be parsed into HTML, it might be nice if the current paragraph (where the cursor is currently) would be visible as plain text, and all other paragraphs would appear as parsed/rendered Markdown.

-----

There are plenty of other "new tab note taking" extensions available for Chrome, which have Markdown support.
But none of them have the features that I like in My Notes (multiple different notes, syncing to Google Drive, etc.).

Markdown would be familiar to a lot of people, and it would allow a lot of styling, including the usual **bold** and *italic* text, headings, pretty keyboard shortcuts (e.g. <kbd>Ctrl</kbd>+<kbd>S</kbd>), the horizontal line a few paragraphs earlier, `inline code` and:

- Bulleted
- lists

1. Numbered
2. lists

- [x] Task
- [ ] lists

```python
def SomeFunction():
    """
    Language aware code blocks.
    """
    return None
```

... all of which you wouldn't have to implement separately, just use a Markdown library like [Marked](https://github.com/markedjs/marked) or [Showdown](https://github.com/showdownjs/showdown).

I realize that even with existing libraries, this might be a considerable amount of work to do for a free extension, but I thought I would test the waters to see if the developer and other users would be interested in Markdown support.

**Comment by penge** [comment]
Thank you so much for a detailed suggestion!
Definitely would love to have this.
There could be an option to create either HTML (WYSIWYG), or markdown note, and this would also be obvious to see in the sidebar. It would also be cool to have a markdown that when edited looks right away as a styled HTML. There are libraries for this manner, but yeah, it would be quite a work.

**Comment by bhupesh-sf** [comment]
Any specific reason to close this one? @penge
