### ISSUE TITLE
option to paste "plain text" by default

### ISSUE THREAD

**Issue by ibmkahm** [penge/my-notes#140]
please add the option to paste "plain text" by default.
I know the formatting can be removed, but this is an extra step. It would be helpful to just paste plain text everytime, just like in a simple editor like Notepad

**Comment by penge** [comment]
Hi, have you tried `Ctrl + Shift + V` to Paste as a plain text? What do you think about it as a solution? Should it be also listed in the Hotkeys list?

**Comment by ibmkahm** [comment]
ok this shortcut works, but it would still be easier to have a "plain text" option in the configuration menu. When enabled, this would remove the formatting editor and always paste in plain text

**Comment by penge** [comment]
Great. I can list the shortcut.
Maybe I could introduce something like a type of a note, which would be selected before creating it.
This type could be either HTML or Plain for now. It would stay the same for the lifetime of a note and there would be some way to tell which note is which type. This is just a though right now.
Other option would be to have a toggle in the Toolbar, that if enabled, would always paste as a plain text. Shortcut works well, although some might prefer using the context menu.

**Comment by ibmkahm** [comment]
your suggestions sound good!
