### ISSUE TITLE
Give feedback when right-clicking Clipboard note

### ISSUE THREAD

**Issue by nathancarter** [penge/my-notes#141]
The first note after installing is Clipboard.  My first instinct was to delete it, thinking I didn't need it.  I right-clicked and nothing happened.  I thought the context menu feature was broken.  No matter how many times I right-clicked, I didn't get a context menu.

Eventually I realized that the Clipboard note was special, and the context menu worked on all other notes.  But it's a natural thing to do, after a first install, to customize the list of notes, starting with the first one.  I think a context menu should pop up, even if it contains only an inactive entry, saying something like, "This note is permanent," or giving an option to hide it, or a link to the help that describes what the Clipboard note does, or something.

No user feedback makes it seem broken.

**Comment by nathancarter** [comment]
That’s great that the conversation there has such cool ideas!  I don’t have strong opinions about them.

**Comment by penge** [comment]
This will be solved in 3.5 where context menu for Clipboard will be added back, as it will be possible to Rename/Delete Clipboard.
