### ISSUE TITLE
Docs are incorrect stating Ctrl/Cmd work the same

### ISSUE THREAD

**Issue by nathancarter** [penge/my-notes#142]
Ctrl+Click follows links, Command+Click does not, but the docs state that Ctrl and Command are interchangeable.

**Comment by penge** [comment]
Thank you for pointing this out. 

Docs could be updated by changing the message from:
`⌘ and Ctrl work the same.` to:
`⌘ and Ctrl work the same for the hotkeys above`. (Suggestions?)

Maybe the message can stay the same, as I found that support for `⌘` can be added.

We would have following shortcuts then:

```
# Windows or Linux

Ctrl + Click           = Open link in a New Tab
Ctrl + Shift + Click   = Open link in a New Tab and focus the New Tab


# Mac

⌘ + Click              = Open link in a New Tab
⌘ + Shift + Click      = Open link in a New Tab and focus the New Tab

Ctrl + Shift + Click   = Open link in a New Tab and focus the New Tab
(still works, but behavior from Windows)
```

That would nicely extend the functionality to OSX.

Do you have any suggestions about the functionality, spelling, descriptions?

**Comment by nathancarter** [comment]
Any of those options are fine with me; I was just asking that the docs became consistent with the features.  Thanks!

**Comment by penge** [comment]
This has been solved together with https://github.com/penge/my-notes/pull/147.
