### ISSUE TITLE
Search contents of my notes

### ISSUE THREAD

**Issue by JACOB-AMP** [penge/my-notes#143]
Thanks for an excellent extension.  I use it daily.

I can search the titles of my notes in Google Chrome by using Control + F (browser feature to search on any web page).

Is there a way to search the contents of my notes?
I will have hundreds of notes and want to search for a specific word in the contents of my notes.

Thanks in advance!

**Comment by penge** [comment]
Thank you!

Let's say after typing the term you would search for, the list of notes would be filtered only to those note containing the searched term. Would that be ok?

**Comment by penge** [comment]
Thank you!

Let's say after typing the term you would search for, the list of notes would be filtered only to those notes that contain the searched term. Would that be ok?

**Comment by JACOB-PLAN** [comment]
Yes, that will be perfect.
Thanks so much.

**Comment by skinnedpanda** [comment]
This is brilliant, thank you!!

**Comment by penge** [comment]
Thank you! :)
