### ISSUE TITLE
Size limit

### ISSUE THREAD

**Issue by JACOB-AMP** [penge/my-notes#144]
What is the size limit of a single note?

Is there a size limit to all my notes?

Thanks in advance.

**Comment by penge** [comment]
Single note and all notes, are limited to 5MB total.

This limit can be increased to unlimited (your disk storage) with a permission called "unlimitedStorage".

I suggest we could be having an option "Use unlimited storage" added to the Options screen.

By having it Optional, we are keeping the Required permissions at minimum, while having an option of an unlimited storage if needed.

I will add this also to the docs. Thanks for asking about it.

**Comment by penge** [comment]
This question is now added to https://github.com/penge/my-notes#qa
