### ISSUE TITLE
Drag and Drop Images

### ISSUE THREAD

**Issue by mtbhuskies** [penge/my-notes#149]
Currently you cannot drag and drop an image into my-notes. Chrome just opens the image in a new tab. You cannot also upload an image, which leaves us only being able to insert an url for an image.

**Comment by penge** [comment]
I like this a lot! Let's say images could be not just dragged and dropped, but also automatically uploaded to Google Drive. I'll look at how this could be done.

**Comment by penge** [comment]
Same as https://github.com/penge/my-notes/issues/220.
