### ISSUE TITLE
3.4.3's new default font size causes some old notes to contain an ugly mix of old and new font sizes

### ISSUE THREAD

**Issue by john-pick** [penge/my-notes#150]
I haven't found a reasonable workaround.
* Copy-paste-without-formatting (Ctrl-A Ctrl-C Ctrl-Shift-V) wrecks all prior formatting while fixing the mixed font size issue.
* None of the toolbar buttons helps.

**Comment by penge** [comment]
I am sorry about that. I will look at this now and try to provide a solution. I hope it has a solution. Some functionality is provided out of the box by using the element called "contenteditable" (just for the record) which behaviour is not fully under my control, more [here](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content) and [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable).

What I think could be a solution, is to add a button to reset the font size, and keep the other formatting intact if possible. Will check it now.

**Comment by penge** [comment]
No real solution to this. If there was some inline style having a fixed font-size, the places where this wasn't on the other hand, used a default font-size. Default font size changed and most likely will remain as is.
