### ISSUE TITLE
Entire document unrecoverable if user accidentally hits "Delete Column" button

### ISSUE THREAD

**Issue by john-pick** [penge/my-notes#153]
I accidentally hit the "Delete Column" button (table buttons), and my entire document, which was not a table and which contained 2 weeks of notes, went blank. Ctrl-Z does nothing. Opening a new tab reflects the empty document. It's just gone.

BTW, I loved My Notes until that moment.

**Comment by john-pick** [comment]
Alas, I can't reproduce the error. But it definitely happened.

**Comment by john-pick** [comment]
More important than fixing just this bug, I'd recommend an overall strategy to prevent data from catastrophically disappearing.

**Comment by penge** [comment]
Hi John, did you have a backup in Google Drive? Anyway, this is terrible to happen. I see working with Tables is causing some problems, I saw your other issue. I'd like to get to the root of this and maybe solve both. Internally it is using some things that are natively supported by the browser, and therefore Ctrl+Z works. Some things are custom, table among them too, and the whole undo functionality would have to be created for it. Having some versions history would be great too. Unfortunatelly there is a 5MB limit but that could be solved.

**Comment by penge** [comment]
This problem has been solved a while ago with the transition to Preact.
