### ISSUE TITLE
Table tools work inconsistently

### ISSUE THREAD

**Issue by john-pick** [penge/my-notes#154]
I've run into several cases of table tools doing nothing or doing the wrong thing (e.g., issue #153).

Here's a reproducible test case:

1. Create a new note.
2. Click the New Table button. A 3x3 table appears.
3. Click the bottom-left cell.
4. Click the Delete Column button. A column disappears.
5. Click the bottom-left cell.
6. Click the Delete Column button. Nothing disappears. 2 columns remain.

**Comment by penge** [comment]
Thank you John, this is a bug. I have tried it now and it's as you described. Thank you for the steps.

**Comment by penge** [comment]
Going to fix this.
