### ISSUE TITLE
Option "Open My Notes in every New Tab" ignored

### ISSUE THREAD

**Issue by alexgv99** [penge/my-notes#158]
I set and unset and turn to set... the options is ignored...

there is a warning "My Notes will request permission to enable this feature." but after the first execution, when I believe it ask me to choose, I can't find that option again... So, I don't know if it's related to permission.

But, I can tell that it was working well... and then, it's not, anymore. :-(

![MyNotesBug](https://user-images.githubusercontent.com/6002790/98442731-3abd0d80-20e5-11eb-9d8f-682064164656.gif)

**Comment by penge** [comment]
Thank you for the video. It most likely has something to do with the permission. First time you closed (or ignored) the permission request, second time it didn't show up - was it like that?

**Comment by alexgv99** [comment]
Actually it wasn't... I granted the permission... I just assumed that it was a permission related issue and tried to grant again, but I couldn't find it anymore... I realize that it works, sometimes... Today, when I turnned my pc on, I openned a new Browser window and it came with google... then I openned a new tab, and My Notes came up... But I tried to repeat the process and it didn't happen again ...
Well... it seams unpredictable... :-)

But thanks for the great software... I love it... it's one of my favorite software, now a days, alongside VSCode, Flameshot and Rocketchat. :-)
I hope you manage to fix, but it's already great. Thank you for create and share My Notes.

**Comment by penge** [comment]
Interesting sometimes it works, sometimes it doesn't. Makes me wonder if it really comes down to permissions or not. Probably no? I'll look at it.

btw, love to hear it made its place among VSCode and other :))

**Comment by JACOB-PLAN** [comment]
> I set and unset and turn to set... the options is ignored...
> 
> there is a warning "My Notes will request permission to enable this feature." but after the first execution, when I believe it ask me to choose, I can't find that option again... So, I don't know if it's related to permission.
> 
> But, I can tell that it was working well... and then, it's not, anymore. :-(
> 
> ![MyNotesBug](https://user-images.githubusercontent.com/6002790/98442731-3abd0d80-20e5-11eb-9d8f-682064164656.gif)

I have exactly the same issue. Is there a fix yet?
Thanks so much for a wonderful extension that I use every day!

**Comment by penge** [comment]
I'll check it out. There will be version 3.5 today or tomorrow on Web Store (hopefully, as sometimes it takes longer to review). And let's see if that solves the problem!

**Comment by penge** [comment]
@JACOB-PLAN and @alexgv99
Are you still experiencing this problem?

**Comment by john-pick** [comment]
Occasionally, My Notes suddenly fails to load when I open a new tab. Disabling and re-enabling the extension is my workaround. This issue started before #168.

I wonder if closing the My Notes tab too quickly after editing a note causes the problem.

**Comment by jayarr100** [comment]
Chiming in here to say that I've also been experiencing this same problem with the extension as of late. It didn't used to happen, but as of the last couple months, give or take, it's very hit and miss as to when it does and doesn't open in a new tab (even with the option and permission set properly). I'd say it works somewhere around half the time, on average. Seeing the same behavior in both Chrome on Windows and on a Chromebook.

Thanks for all you do with this. The extension is exceptional and completely invaluable for me.

**Comment by penge** [comment]
@jayarr100 I will look at this. It is related to background script that if not used for some time (browser decides when that is), it is unloaded from memory to free up resources. The next time background script spins up (as My Notes is to be open or used), it doesn't catch the first new tab to replace it with My Notes.
I haven't experienced this on Chromebook, but I agree this needs fixing. The reason why it happened recently and not in the past, is changing background script to be NOT persistant (running constantly) as that's a preferred way and also it solved an issue with My Notes Context menu registration. So it solved one thing, but caused other, as I see.

Giving it a priority so we can have it fixed.
Thank you @jayarr100 for pointing this out, I am also very glad you like the extension.

**Comment by penge** [comment]
Haven't experienced this in Chrome 88.0.4324.192 and My Notes 3.6 so far. How's your experience?

**Comment by jayarr100** [comment]
Thanks for looking into it — glad to hear you have some ideas about what might be responsible!

It's still hit and miss for me as of now, unfortunately. I'm on a Chromebook at the moment. Just opened up 20 new tabs in a row, and nine of them went to the default Chrome new tab screen, while the other 11 loaded My Notes. This system is actually running the Chrome 89 (89.0.4389.57) beta. My Windows system is on the current stable standalone browser version; I'm not in front of it this minute, but I was seeing vaguely similar behavior on it as recently as yesterday.

I'll check on it later this weekend and see if anything has changed there.

**Comment by jayarr100** [comment]
Update: Still a bit hit and miss for me on the Windows front as well (with Chrome 88.0.4324.190, which is the latest stable version available here). Four out of 10 tabs I just opened went to the default NTP, while six went to My Notes.

**Comment by penge** [comment]
Update from me: Tried it again and experienced the issue as well. Having a fix ready. Would you like to try it out?
@jayarr100 @john-pick @JACOB-PLAN @alexgv99

**Comment by jayarr100** [comment]
Great to hear! Thanks. And sure, I'm always game to give it a try and test anything out.

**Comment by penge** [comment]
Cool! I will upload here a new version to try it out.

**Comment by penge** [comment]
https://drive.google.com/file/d/1Bb29VpE-UNOMvc7tNq-NR3_bcofR67Ve

^ Here's the ZIP file for My Notes 3.6.1


Instruction to install:
1. Extract the zip
2. Open `chrome://extensions/`
3. Enable **Developer mode** (toggle is in the top right corner)
4. Click **"Load unpacked"**
5. Navigate to the extracted folder and click **Select**
6. **My Notes 3.6.1** should be now added to the list

Everything except Google Drive, should be available. Option to open in new tab, should work as expected when enabled in Options.

Let me know if that works for you.

**Comment by jayarr100** [comment]
Sorry for the slow response — got bogged down with some work for a while. Just installed the new version, though, and I'm happy to report that I haven't seen a single tab open up without the extension in place and properly loaded so far. I've probably opened up a solid 70+ tabs since installing it, too. Not a single misfire!

Thanks for the fast fix on this!

**Comment by penge** [comment]
No worries at all. I see it works pretty solid – Great!

I will test it further a bit as well, so far very promissing. Success rate on my side also 100%!

Thank you very much for the testing, very appreciated. I will try to relese a new version 3.6.1 with this fix very soon – during this week.

A sidenote:
Testing version of My Notes, and the released version (the one with ID lkeeogfaiembcblonahillacpaabmiop), can coexist (their local data is separate) and testing version can be disabled/enabled at any moment.
In case you would like to join testing in future for the upcoming features, you are very welcome. I'll try to create a channel for that, like Telegram (or Discord) where we can sync quickly, or mentioning here. Suggestions?

**Comment by jayarr100** [comment]
Awesome — thanks again!

And sure, I'd be happy to help with any testing that I can. I use the extension constantly, especially during the weekdays.

I'm not usually on Telegram or Discord too often, personally, but anything that reaches me via email (which activity here can, if I make sure to watch the appropriate area) would definitely catch my attention relatively quickly.

**Comment by penge** [comment]
I'll be checking migration to Manifest V3 this week and if all good, 3.6.1 will be released on this Tuesday or Wednesday.

**Comment by jayarr100** [comment]
Awesome! Thanks for the update. Looking forward to it and will absolutely keep an eye out for the update.

**Comment by penge** [comment]
@jayarr100 New version 3.6.1 is now released here on GitHub (https://github.com/penge/my-notes/releases/tag/3.6.1). Going to send it to Web Store for the review now. It should be available via an update on Monday (usually it takes 1-2 days for the review).

**Comment by prediscover** [comment]
This feature has disappeared! I really liked having my notes come up on a new tab.  I prefer this as opposed to having another keyboard shortcut opening my notes.
