### ISSUE TITLE
Sync on Edge?

### ISSUE THREAD

**Issue by sooyoung** [penge/my-notes#163]
[Enhancement]

Longshot but any possibility of getting Google Drive sync to work on Edge?

**Comment by penge** [comment]
Edge does not support the needed API yet. More at:

https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/extension-api-roadmap
https://stackoverflow.com/questions/52483650/how-do-you-determine-identity-in-a-microsoft-edge-extension
