### ISSUE TITLE
Recently, My Notes loads after I open a Chrome tab and enter a URL.

### ISSUE THREAD

**Issue by john-pick** [penge/my-notes#168]
Recent sporadic issue on my machine:

When I open a new Chrome tab, My Notes doesn't appear until _after_ I've entered a URL. I tend to enter URLs rather quickly after I open a tab. When the problem happens, My Notes takes a second or two to appear after the tab opens.

The usability concern is that My Notes stops my web page request, and I have to enter my URL again.

**Comment by penge** [comment]
Have you experienced this issue before, or is it a new one?
If you open several new tabs afterwards, is it always like 1-2s, or only on the first time?

**Comment by john-pick** [comment]
This issue is new since Patch Tuesday (Dec. 8).  If I open several new tabs
afterwards, the issue does not happen in those new tabs. However, if I open
a new Chrome window, the issue sometimes happens. It seems that the more I
use My Notes, the less the problem happens, but if I work on something else
for a while and then return to My Notes, the problem happens again.

**Comment by john-pick** [comment]
Chrome URL auto-complete means I can enter a URL rather quickly. For
example, to open github.com in a new tab, I could hit Ctrl-t g [ENTER].

>

**Comment by penge** [comment]
Found delay happens on the initial start after some inactivity.
In my case the delay is very short, and I have no time to enter any URL or g, yet there is a tiny delay on the first start.
This issue is related to https://github.com/penge/my-notes/issues/158. Interested to get the feedback there as I pick the solution based on that.

Is your preference New Tab automatically? How do you see other options: https://github.com/penge/my-notes#how-to-open

**Comment by john-pick** [comment]
In my case, the delay wasn't an issue until the latest Patch Tuesday (Dec.
8).

I enabled all 3 options:

   - Open My Notes in every New Tab
   - Enable Google Drive Sync
   - Indent text on Tab

**Comment by penge** [comment]
Thank you, I will provide a solution soon. Please try the keyboard shortcut, like `Ctrl + Shift + M` (which can be set at `chrome://extensions/shortcuts`) as a quick alternative for now (or click on the icon in the toolbar).

Would you be ok to help me with the testing once the patch is ready? As I said, I don't experience it in that way, so it's not easy to know if the patch works at everyone's system. I would provide a public link to the public beta, with all the instructions, which would be easy btw. If all good, it can proceed to be the final version.

**Comment by john-pick** [comment]
Certainly, I'll help test.

**Comment by penge** [comment]
Solved here: https://github.com/penge/my-notes/pull/211
