### ISSUE TITLE
Ability to add a Horizontal line

### ISSUE THREAD

**Issue by bhupesh-sf** [penge/my-notes#169]
I think it was available earlier as I can see it in one of my previous notes but when I tried today I couldn't find it.

**Comment by penge** [comment]
You are right. It has been there in older versions. I removed it as I found it unnecessary or just take place in already big toolbar.
Consireding to add it back, that would be ok. Need to think more about structuring the toolbar differently. To either have the way to customize which toolbar buttons should be there or not, or put controls into more groups which would open on mouse hover. That way, there could be many more controls and still it would take just little space. Let me know about your opinion.

**Comment by bhupesh-sf** [comment]
Just like any other editor, the second option is better where you let more menu options open on mouse hover.

**Comment by theo-armour** [comment]
@bhupesh-sf @penge 

How about if there is a button to switch between rendered HTML and source code HTML? This would be like "Write" and "Preview" in GitHub issues. WordPress has a similar idea.

If that worked, then you could add <hr>, <details>, <iframe>, <blink> ;-) and more.

**Comment by penge** [comment]
^ This is a great suggestion and I am looking forward to have something like this.

Thanks, @theo-armour!

**Comment by bhupesh-sf** [comment]
Any update here @penge

**Comment by jpatterson1830** [comment]
I would also like the ability to add a horizontal line

**Comment by penge** [comment]
@bhupesh-sf @jpatterson1830
I'd like to let you know that this feature will be soon added in the next version 3.11.5.
