### ISSUE TITLE
Allow custom font choice

### ISSUE THREAD

**Issue by nickforddesign** [penge/my-notes#17]
I like this extension, but would really prefer to be able to set the font family of the notes, because I need the font to be monospaced for this to be useful to me.

I wouldn't mind opening a PR but I don't have a ton of free time at the moment. If you are open to it but don't want to implement, I'll see what I can do! :)

**Comment by penge** [comment]
Hi @nickforddesign 

I understand. The monospaced font is important to me too.

And.
My font is **Monospace** :D Can't be more monospaced than that :D

## The cause

But, let me guess. You have a Mac?
And the font is, let me guess, Helvetica????

## Await 1.4 tomorrow

Good. I will add an **Options** page to select from a few common fonts (the default will be **monospace**). No prob.
That would be tomorrow. (let's call that Round 1).
Round 2 (in Future) could let's say, inject any font from Google Fonts. Can go wild lol.

**Comment by penge** [comment]
**Done.**
