### ISSUE TITLE
Bookmarks Bar?

### ISSUE THREAD

**Issue by shoelessjoe51** [penge/my-notes#170]
I love your extension and it's super useful but I really miss having my bookmarks bar so handy when I open a new tab. Is there a way to have both the bookmarks bar and your extension both stay on the screen?

**Comment by penge** [comment]
Thank you!

To see the bookmarks bar and the extension at the same time you can use `⌘ + Shift + B` or `Ctrl + Shift + B` to show/hide the bookmarks bar. This is also available in settings on `chrome://settings` page.

The default behaviour is that bookmarks bar is displayed only on _New Tab_ page. Unfortunately, this option is not available if _New Tab_  page is replaced by the extension.

Other ways forth trying are to open My Notes in different way like a keyboard shortcut (see `chrome://extensions/shortcuts` to configure the shortcut to open My Notes) or with a click on My Notes icon in the toolbar. Either way, the default _New Tab_ page could stay default, yet there would be quick way to open My Notes.
