### ISSUE TITLE
Sidebar disappeared? 

### ISSUE THREAD

**Issue by Questionsonly** [penge/my-notes#171]
LOVE this extension, I recommend it to everyone. 
I appear to have hidden the sidebar and can't get it back. I see that the latest update made it much thinner (almost to the point of disappearing), but I don't think that's what's happened here. Any help?

**Comment by penge** [comment]
Thank you a lot!

Please try following to fix it:

- press `⌘ + S` or `Ctrl + S` to show/hide Sidebar (This should do the trick!)
- at any moment double-click on Sidebar's resizing line to restore the default width

Let me know if that worked.

**Comment by Questionsonly** [comment]
Yes, that sorted it out perfectly! This really is the best extension. Thanks!
