### ISSUE TITLE
Is My-notes available on android?

### ISSUE THREAD

**Issue by Alexbba** [penge/my-notes#173]
...through the Play Store?

**Comment by penge** [comment]
My Notes is available on [Web Store](https://chrome.google.com/webstore/detail/my-notes/lkeeogfaiembcblonahillacpaabmiop) as a Chrome extension only. To access notes on the phone, you can use Google Drive app.

**Comment by Alexbba** [comment]
Got it! An extremely handy app, much obliged!

**Comment by Alexbba** [comment]
How might one donate to the project?

**Comment by penge** [comment]
I have created https://www.buymeacoffee.com/penge that can be used. In near future I plan other options like GitHub sponsor.
