### ISSUE TITLE
Enhancement: drag/drop from one note to another

### ISSUE THREAD

**Issue by mayurjobanputra** [penge/my-notes#174]
Drag/drop highlighted text from one note to another would be useful. For example, from clipboard to a note of my choice.

**Comment by penge** [comment]
Sounds great! Will look at it.

**Comment by penge** [comment]
@mayurjobanputra This feature is near complete. Testing it. Here's how it looks at the moment:

a) You can drag n drop text from one note the other

![note-to-note](https://user-images.githubusercontent.com/907255/105353261-5073a680-5bef-11eb-8577-c998854a62b2.gif)

b) You can drag n drop text from outside (web or app) to note

![outside-to-note](https://user-images.githubusercontent.com/907255/105353572-b5c79780-5bef-11eb-8e78-fbff7537a6cc.gif)

Some details:
- dropped text is appended to the end, existing content of note remains
- note that receives the text flashes in blue (customizable) as a feedback that it received something (successfully)
- if note that receives the text is open, the received text is immediately visible, if the note is not open, the received text will wait you there once you decided to open it
