### ISSUE TITLE
rename file to HTML

### ISSUE THREAD

**Issue by mayurjobanputra** [penge/my-notes#175]
When I try to open notes in a text editor, I have to choose the default editor each time as the files have no file extension. Since it looks like html, maybe give all the files an .html extension?

**Comment by penge** [comment]
Thank you for the suggestion. I will the extension in future version.

**Comment by penge** [comment]
Thank you for the suggestion. I will add `html` extension in future version.

**Comment by bhupesh-sf** [comment]
Will it update the existing notes as well?

**Comment by penge** [comment]
Yes. The idea is that on the next sync files have `*.html` extension added, if not having yet. The note names would continue to be without `*.html` in the name, of course.

Other method is to set mimeType, which Google Drive does automatically and does it well, it recognizes HTML files for me.

I am not sure about how this feature is usefull. If files are as `*.html` files, you have to open them in text editor to edit anyway. Now, dropping them into Chrome doesn't open them as HTML page, but in the end, it would be without styles and view-only.

To open any file in text editor, you can drop it there, or open My Notes folder from the editor to access all notes. There's no limitation in that.

**Comment by penge** [comment]
Decided to close.
