### ISSUE TITLE
is there a way to do sub-bullets with ordered and unordered lists?

### ISSUE THREAD

**Issue by esichris** [penge/my-notes#177]
is there a way to do sub-bullets with ordered and unordered lists?

**Comment by penge** [comment]
Not at the moment, but I gladly add this to the next version as it's quite easy to do. It will be added as 2 new buttons to the Toolbar - indent and outdent.

**Comment by penge** [comment]
This one is done.

**Comment by penge** [comment]
Buttons to look for:

<img width="559" alt="sub-bullets" src="https://user-images.githubusercontent.com/907255/106943097-442a3600-6725-11eb-890f-f2fd34e87cac.png">

Outdent and Indent buttons are those 2 in the middle.
