### ISSUE TITLE
Option to add icon to notes name similar to clipboard

### ISSUE THREAD

**Issue by bhupesh-sf** [penge/my-notes#178]
A small but nice option to have for each note. It will help to differentiate the notes even better.

Let me know your thoughts on it.

**Comment by penge** [comment]
Icons have to be either stored somewhere, or some public and reliable service would have to be used. Any suggestions how this would work and what icons you'd like to use?

**Comment by bhupesh-sf** [comment]
Icons can be stored in the user's drive account. What do you think?

**Comment by penge** [comment]
It's an option. Or, there would be a predefined collection of icons that would live in the extension. They wound't have to be uploaded, and it would be easier to set them up, or maintain some quality - SVG icons. I personally wound't use this feature as I find note name to be sufficient. I shall wait for more feedback on this to see how is this feature anticipated.

**Comment by theo-armour** [comment]
@bhupesh-sf 

I just pasted some emoji into the sidebar panel titles using My Notes on a Chromebook, then synced to Google Drive, then opened My Notes on a Win10 box. The emoji are visible on both devices.

![image](https://user-images.githubusercontent.com/547626/105642364-2c59d480-5e3e-11eb-8251-4beecf899623.png)

Is pasted emoji support good enough to meet your needs?

**Comment by penge** [comment]
Adding one more.

<img width="535" alt="Screen Shot 2021-01-26 at 17 17 08" src="https://user-images.githubusercontent.com/907255/105872165-61ab2180-5ffa-11eb-9957-c042d9668452.png">

I have completely forgot about this option but it is possible as it gets encoded and becomes a part of the name.

<img width="140" alt="Screen Shot 2021-01-26 at 17 18 33" src="https://user-images.githubusercontent.com/907255/105872344-97500a80-5ffa-11eb-86db-b191569ad4e5.png">

Thanks @theo-armour for pointing this out!

What do you think @bhupesh-sf? Is this sufficient to have? See https://emojipedia.org for emojis.

**Comment by theo-armour** [comment]
@penge 

>I would suggest to remove Clipboard SVG icon on the right.

Yes, good idea. "soft" titling is better than "hard".

**Comment by theo-armour** [comment]
@penge 

HaHa. You asked for it:

**Wishlist item: Add emoji by typing**

Actually may be doable

https://stackoverflow.com/questions/35559097/how-to-add-emoji-in-between-the-letters-in-contenteditable-div

**Comment by bhupesh-sf** [comment]
@penge Yes it works for me. Thanks

**Comment by penge** [comment]
working on a better solution where icon/emoji in the note's name won't be necessary
