### ISSUE TITLE
Unable to delete a note last in the list

### ISSUE THREAD

**Issue by bhupesh-sf** [penge/my-notes#180]
I have a long list of notes and hence last notes come at the bottom. And when I right-click on it delete option from the menu is not visible and hence unable to delete it.

![Screenshot from 2021-01-11 15-09-29](https://user-images.githubusercontent.com/6471510/104165170-059fa500-541f-11eb-8900-d89d2f6ae087.png)

**Comment by penge** [comment]
Thank you for reporting this!

I will fix this in the upcoming version 3.6. The fix would be to make sure context menu never goes beyond the bottom screen border and therefore stays visible within the screen.

**Comment by penge** [comment]
This one is done. Here's what to expect:

<img width="534" alt="context_menu" src="https://user-images.githubusercontent.com/907255/105639296-a9557000-5e77-11eb-8dd9-21da8b2d7366.png">

**How it will work:**
Before the context menu gets displayed, it will check the available height below the note. If there's enough space, context menu will be displayed as usual. If there is _NOT_ enough space (e.g.: small window height, last note), context menu will be padded from bottom. This way, all options will be always visible.

@bhupesh-sf 
I have few more things to do on 3.6. The progress is good and it should be ready soon.

**Comment by bhupesh-sf** [comment]
Awesome, will look forward.
