### ISSUE TITLE
Introduce Zen mode

### ISSUE THREAD

**Issue by penge** [penge/my-notes#181]
_Zen mode_ – no distractions, focus on typing.

At the moment, _Focus_ can achieve similar (hide Sidebar, hide Toolbar).

Still, I think having a Zen mode, would be very nice. It would be a specific mode with less distractions. It can look like this:

<img width="1373" alt="zen" src="https://user-images.githubusercontent.com/907255/105349851-95490e80-5bea-11eb-8d75-621dd1872e18.png">

Let me know what you think.

**Comment by theo-armour** [comment]
@penge 

Good idea! Here is a thought:

How about making Control-S a three way toggle? 

1. Side bar off
2. Sidebar and Toolbar both off
3. Sidebar and Toolbar both on

**Comment by penge** [comment]
Hi @theo-armour

Given the example, I found one more option, which is "Sidebar on, Toolbar off". It is when one would like to go plain text and therefore hide the editing tools. That leaves us with 4 possible states: only Sidebar, only Toolbar, none, both.

To avoid cycling through the states, I've decided to go with:

- `⌘ + S` to toggle Sidebar only
- `⌘ + E` to toggle Toolbar only (E stands for Edit; T is taken by New Tab action)
- `⌘ + Shift + F` to toggle Focus mode (entering and leaving Focus mode does not affect previous visibility of Sidebar and Toolbar, they are set back as user had them; Shift is needed as w/o Shift there is already taken action for Find)

Zen mode could nicely contemplate the already existing options. Here are some thoughts on what it could do:

- hide the Sidebar
- make Toolbar controls semi-transparent, set full color on mouse hover
- make Editing area more narrow, and center the content to the middle

Let me know what you think.

I would like to thank you for your coffee donation, very appreciated! Out of curiosity, I have looked on gbXML, Spider Viewer, or the webinar. Nice work there.

**Comment by theo-armour** [comment]
@penge 

Thank you for having a look at my efforts and for your kind words

The idea of playing with the visual opacity is a good one It helps with focus without losing quick access

There may be an issue with command key learnability. We live in a world where there are more and more apps each with their own command key operations.  Remembering the keystrokes - let alone knowing all the commands that are available - for each app may become a burden and no longer a joy.

I also note that repeating a key stroke is much faster and easier to learn that moving fingers to handle multiple key strokes. You might consider forking multiple versions and letting your users try different settings.
 
Here is a thought: Given that My Notes is a text editor it may be useful to follow closely the example of a major editor such as vsCode or Sublime (or Vim ;-) If you can do that then this can give you an excellent road map for adding new features. (alt up and down cursor keys, I am looking at you).

Theo

**Comment by penge** [comment]
@theo-armour 

I like the reasons you mentioned. To solve this, I am thinking about 2 possible solutions, which could co-exist.

1) There could be an "eye" icon that would open:

```
[✔️] Sidebar
[✔️] Toolbar
```

By seeing the "eye" icon and the list above, it would be obvious this option has something to do with changing the visibility of things. The relation between having `✔️` and having Sidebar (or Toolbar) visible or not, can help to translate this message as well. To go into focus mode, simple uncheck of both, Sidebar and Toolbar, would do. "eye" would help to operate without any additional hotkey(s) to learn. The hotkey to loop over the visibility modes, could be added as well.

2) Command palette

VS Code has a simple shortcut `Cmd + P` to open a command palette. Similar could be added to My Notes as well. A shortcut that rules them all. One shortcut to remember, making any additional shortcut a nice bonus.

Let me know what you think.

**Comment by penge** [comment]
Closing for following reasons:

**_Zen mode_** would be about subtle visual changes, fewer controls and/or less-opaque controls, semi-transparent Toolbar, etc. – all of which is possible now via a Custom theme.

Similar **_Zen mode_** experience can be achieved by hiding Sidebar, or Toolbar, or both (Focus mode).

Having too many visual options could lead to problematic switching between them, considering their combinations.

Closing for now, although might be open in future.
