### ISSUE TITLE
Text-marking color same as background, thus invisible

### ISSUE THREAD

**Issue by Alexbba** [penge/my-notes#196]
Using my chromebook with up-to-date browser, the text-marking color is the same as that of the background, thus invisible (cannot see where I have marked the text).

What can I change in the settings?

**Comment by penge** [comment]
Do you have the same behavior for Light or Dark theme? Are you using a Custom theme? If yes, check if you have set the the following variables (example below):

```
--highlight-background-color: yellow;
--highlight-text-color: black;
```

This can be set in Custom theme window. The content there should be based on either Light or Dark theme (`light.css` or `dark.css`), where copy-paste is sufficient to start with.

**Comment by Alexbba** [comment]
Customized, like this:

:root {

  /* Scrollbar */

  --scrollbar-track-background-color: #f1f1f1;
  --scrollbar-thumb-background-color: #c1c1c1;
  --scrollbar-thumb-hover-background-color: #888;


  /* Generic */

  --background-color: beige;
  --text-color: black;
  --link-color: black;
  --svg-fill-color: black;


  /* Notifications */

  --notification-border-color: silver;


  /* Overlay */

  --to-create-overlay-background-color: #1e88e5;
  --to-rename-overlay-background-color: rgba(30, 136, 229, .7);
  --to-delete-overlay-background-color: rgba(255, 0, 0, .6);


  /* Modal */

  --modal-background-color: white;
  --modal-border-color: #dfe1e5;
  --modal-input-border-color: #dfe1e5;
  --modal-button-background-color: #222;
  --modal-button-text-color: white;


  /* Context menu */

  --context-menu-background-color: #222;
  --context-menu-text-color: white;
  --context-menu-border-color: transparent;


  /* Sidebar */

  --sidebar-notes-background-color: #f5f5f5;
  --sidebar-notes-text-color: black;
  --sidebar-active-note-background-color: #bdbdbd;
  --sidebar-active-note-text-color: black;


  /* Drag */

  --drag-border-color: silver;
  --drag-resizing-border-color: #222;


  /* Bar */

  --bar-border-color: silver;


  /* Toolbar */

  --toolbar-button-color: black;
  --toolbar-button-hover-background-color: #222;
  --toolbar-button-hover-color: white;
  --toolbar-submenu-background-color: #f5f5f5;


  /* Editor */

  --pre-border-color: silver;
  --highlight-background-color: yellow;
  --highlight-text-color: black;
  --table-border: 3px solid #171717;
  --table-td-border: 1px solid silver;
  --table-td-heading-background-color: #dddddd;


  /* Only in Options */

  --hotkey-background-color: #e1e1e1;
  --hotkey-text-color: #121212;

  --comment-background-color: #e1e1e1;
  --comment-text-color: #121212;

  --slider-background-color: #d3d3d3;
  --slider-thumb-background-color: black;
  --slider-thumb-size: 11px;
}

body {
  opacity: 1;
}

**Comment by Alexbba** [comment]
SOLVED: I thought I'd only changed one thing in the settings, "beige", below, but I must have changed something else in the above as well (not sure what it was!).

/* Generic */
--background-color: beige;

Thanks again for feedback.

**Comment by penge** [comment]
Thank you. Glad to hear it works now.
