### ISSUE TITLE
Tab Key doesn't tab or space text

### ISSUE THREAD

**Issue by MichaelWehar** [penge/my-notes#2]
When I click tab, it doesn't tab or space the text.  Instead, it puts focus on the search bar.

It might be possible to add this functionality, but I'm not entirely sure how.

Maybe it can keep focus on the textbox and add a tab or spacing character to the textbox.

**Comment by penge** [comment]
I will look at it and let you know. Thanks for the finding!

**Comment by penge** [comment]
I have some great news! And I think you know what I mean by that.

It is possible!

Let's keep it simple for now and do it this way: I press Tab, 2 whitespaces get inserted.

In future, we may think of improvements.

Sounds goood? :)

**Comment by MichaelWehar** [comment]
If it works, that would be awesome.  :)

**Comment by penge** [comment]
I have detected some issues regarding this.

## Good scenario 👍 

When hitting space (or writing any text), and reaching the end of the visible area, textarea will insert a linebreak.

# Detected problem 🤣

When adding text in different way, like Tab = insert 2 whitespaces, and updating `textarea.value`, also `textarea.selectionStart` and `textarea.selectionEnd` accordingly and, it's about to reach the end of the visible width (which is variable btw and depends on the user's window), then, the NEW LINE character will NOT be put. This causes a problem.

## Waiting for solution 🧐

If it possible to solve this, without setting a fixed number limit to the visible area (which is not a nice idea) then it can work perfectly.

# Current functionality 😎

The current progress is nice. Ignoring the problem for a moment, it can now do the following. It can insert Tab, it can Tab forward and backward, it can even Tab a selection of text, again backward or forward. It works perfectly, except, the NEW LINE issue is now a stopper.

I will look it up later. I hope there's a solution to this and not a limitation of the textarea.

**Comment by penge** [comment]
Not achievable due to the behaviour of **textarea.**
