### ISSUE TITLE
feature request: explain what "clipboard" means - it sounds like it's actually syncing clipboard because it provides no inline explanation

### ISSUE THREAD

**Issue by jzacsh** [penge/my-notes#201]
i see issue #134 introduced this, and the opening issue description would make for perfectly acceptable inline documentation _(eg: a tooltip and/or a new paragraph on the options-page)_:

> "Use as clipboard" sets that note to receive text from the context menu **(right-click menu in Chrome)**. The clipboard note cannot be deleted or renamed, or the context menu functionality would break.

(Emphasis added for what I tweaked)

**motivation**: I only figured out what this "clipboard" button on the note meant after (eventually) coming to github issues (removing "is:open" filter) and searching `"use as clipboard"`

**Comment by penge** [comment]
Sorry for the late reply. I see, and agree, to add some explanation to what Clipboard is and how it works.

Tooltip seems like the easiest (probably best) way to provide the explanation. It can be added to QA (README here) too.

Here's my summary on Clipboard, can be improved where needed (also considering if some other name than Clipboard would suit this better and be more intuitive):

> Clipboard is a special note that you can use to send a text to, by selecting a text on any page, followed by a right click and using one of the options from the My Notes menu. You can either "Save selected text to Clipboard", which saves the text to you local Clipboard (My Notes does not have to be open), or "Save selected text to Clipboard in other devices", which saves the text to your remote My Notes installations (My Notes has to be open there, and same Google Account has to be used in Google Chrome).
There can be only one note set as a Clipboard at a time. To set a note as a Clipboard, right click on the note and select option "Use as Clipboard". If there is no Clipboard note and My Context menu is used, "Clipboard" note will be created automatically so it can receive the text. If "Clipboard" note already exists, text will be appended to its end.

**Comment by penge** [comment]
I have improved My Notes Context menu so it lists existing notes. Therefore "Use as Clipboard" is no longer needed. It was confusing anyway - about what it does and how it works.

The new Context menu is explained in README. PR is now in review and should be added shortly.
