### ISSUE TITLE
Increase "Loading Times," get rid of "extension://..." in the task bar

### ISSUE THREAD

**Issue by ajarang** [penge/my-notes#202]
Hello, 

This is a brilliant app. However, there are still a few issues. Whenever I press on the new tab page, the notes take some time to load. I think there was an issue [here](https://github.com/penge/my-notes/issues/91) where you said something about the extension having persistent background, but according to the notes, it appears to be fixed/mitigated. However, on my end, it still takes some time to load. 

Also, is there any way that I can get rid of the text in the URL bar? I know it is possible since [this](https://chrome.google.com/webstore/detail/tabnotes/omgomlnnfccahaaicaphjjgkjplfkjai) extension doesn't have have anything in the URL bar when used.

**Comment by penge** [comment]
Thank you! I try my best to explain why is this happening, and what could we do about it.

Chrome extensions can replace New Tab page in one of the following ways:

A. Declaratively, which is very fast and leaves the URL bar (address bar) empty. The downside of this approach is, it cannot be optional. In other words, user cannot decide if he would like to have his New Tab always replaced, or not. That's how TabNotes works. And it is how My Notes worked till some point. I didn't like the downside of this approach, that this setting couldn't be set optional. So I went for option B.

B. Programmatically, which allows this setting to be optional (which I like), but on the other hand has other issues (which I don't like as well). One of them is speed, where it takes long time for the browser to register that it should replace New Tab page (when user enabled that option). I tried a slightly different method too, it was a bit faster, but it didn't always catch that it should replace New Tab, sometimes it didn't. And the second issue is, the URL bar, it cannot be set empty (so it starts with chrome-extension://).

Both A and B have pros and cons. I like the fact of B being optional. But I also like A being faster, don't like it's not optional. I wish there would be some option C (best of A and B combined).

So, here are the options we have:

1. Use approach A, meaning New Tab replace is quick, address bar is empty, but on the other hand, New Tab replace always happens and is not optional (some might like it, some might not).
2. Not to use A, not to use B, and prefer to open My Notes in other ways, which are: click on the icon in the browser's Toolbar or, use the keyboard shortcut to open My Notes, that can be set at chrome://extensions/shortcuts.

Now the right question is, if 1 or 2 would be preferred (by majority), or something else. We now have GitHub Discussions (https://github.com/penge/my-notes/discussions), which we could use for this (or even this issue), to get more opinions. Which option would you vote for?

**Comment by ajarang** [comment]
Thank you for your response! Personally, I think that it would be best to set this program as Declarative (approach A). 

When I use this notes application, I use it for quick notes during phone calls, and the delay in showing up (and sometimes it doesn't show up at all!) makes it difficult to use for that case. I believe others who use this extension are in the same boat- they just want something to quickly take notes on. If I had to wait to open the extension, I would probably move to something like (joplin)[https://joplinapp.org/], or another dedicated, really well fleshed out app. 

I didn't know Discussions was a thing in github, and I'm fine to move there so we can poll user interest. I'm curious how you use the extension, though, if not in the new tab? Do you only set it to open when you use a shortcut like control+T?

I know nothing about coding chrome extensions, but if it was relatively simple to switch between declarative and programmable, perhaps I could try and help maintain a fork. I've opened up a discussion (here)[https://github.com/penge/my-notes/discussions/208]

**Comment by penge** [comment]
@ajarang Thank you for creating the discussion. We can take it from there, will reply to your questions there as well.
