### ISSUE TITLE
Feature request: Make a note read-only

### ISSUE THREAD

**Issue by alexgv99** [penge/my-notes#203]
Sometimes we keep things that are not suposed to be changed... for those cases, would be nice to have the ability to turn the note read-only.

**Comment by penge** [comment]
I like it. There could be a new menu item (on right click), either something like "Make read-only" (what would be the opposite to this to turn it back?), or maybe "Lock" and "Unlock". The could some icon of a lock, that would indicate the note is locked from editing.

**Comment by alexgv99** [comment]
Lock / Unlock sounds perfect... but if you prefer the original one, the opposite could be Writable... for icon, what do you think about a padlock closed / open?
![image](https://user-images.githubusercontent.com/6002790/112217225-25aeca00-8c01-11eb-94c5-8f4f6ced547d.png)

**Comment by alexgv99** [comment]
Oh... Now I see... you've already proposed that icon... :-)

**Comment by penge** [comment]
Cool, I think we both ment the same and that kind of icon will be perfect :)
I like "Lock" and "Unlock" too. Let's say if locked, locked icon is shown, and if unlocked, no icon.

**Comment by penge** [comment]
Decided to close.

**Comment by penge** [comment]
Right-click on any note to Lock it:

<img width="567" alt="lock" src="https://user-images.githubusercontent.com/907255/123447648-62140c80-d5da-11eb-8527-31f2f26ffd63.png">

When the note is locked, there is a locked icon:

<img width="567" alt="locked" src="https://user-images.githubusercontent.com/907255/123447750-7e17ae00-d5da-11eb-99ef-28811afbfd17.png">

When you want to unlock, Right-click on the note:

<img width="567" alt="unlock" src="https://user-images.githubusercontent.com/907255/123447800-8cfe6080-d5da-11eb-90ad-a6be75291a47.png">

<br>

While the note is locked, it CANNOT be **Edited**, **Renamed** nor **Deleted**.

If the currently open note is locked, the Toolbar will be locked too, except for the Info icon:

<img width="515" alt="locked_toolbar" src="https://user-images.githubusercontent.com/907255/123448295-0d24c600-d5db-11eb-9f52-3ce7913e3ed0.png">
