### ISSUE TITLE
On Chromebook, Ctrl+Shift+F not working any longer

### ISSUE THREAD

**Issue by Alexbba** [penge/my-notes#204]
The shortcuts Ctrl+Shift+F Ctrl+E or Ctrl+S etc to open My Notes, toggle etc hasn't worked since a few days.

**Comment by penge** [comment]
Thank you for reporting this issue. I will check it on Chromebook. If you press those shortcuts, is there (a) nothing happens or, (b) something else happens, like a browser's default action?

**Comment by Alexbba** [comment]
(a) Nothing happens.
Any tip on accessing menus/different notes, now? Including editing text? I only use the shortcut methods for toggling it.

**Comment by Alexbba** [comment]
CORRECTION: I probably set my own shortcut for opening notes in chrome://extensions/shortcuts, 
before that option became unavailable (as of the latest version, 3.6.1, as Penge stated here 
https://github.com/penge/my-notes/discussions/208#discussioncomment-520476).

And so that shortcut doesn't work any more. Some shortcut options in My Notes correspond to chrome's default shortcuts (thus your option (b) above).

**Comment by penge** [comment]
Good to hear. There is now discussion if new way (that would replace chrome://extensions/shortcuts) to open My Notes should be Ctrl+T (New Tab), and Ctrl+N (New Window), and if it would be fine to have this always enabled, meaning option "Open My Notes in every New Tab" would be removed and New Tab would always open My Notes.

Another solution could be, option "Open My Notes in every New Tab" is removed also (it is slow), there is no Ctrl+T or Ctrl+N (user keeps the default New Tab), but chrome://extensions/shortcuts could be used to set a custom shortcut to open My Notes, like Ctrl+Shift+M, or other available, could be also Ctrl+T, but not both Ctrl+T and Ctrl+N, meaning only 1 shortcut.

What would you prefer from these two solutions? @Alexbba @ajarang
