### ISSUE TITLE
Feature: Ability to hyperlink within the document

### ISSUE THREAD

**Issue by bhupesh-sf** [penge/my-notes#209]
I created a little bigger note and now I want to refer to some sections below in the note but cannot do so. So hyperlinking within the note and also an option to link to other notes will be great.

**Comment by penge** [comment]
Thank you, I like that suggestion. Linking within the note's sections (headings) is now not possible (in Markdown editing it could be made easy). The other feature – link other notes, that sounds nice too, and could be added.

**Comment by bhupesh-sf** [comment]
@penge this one is related to same TOC one.
