### ISSUE TITLE
Inconsistent Google Drive Sync

### ISSUE THREAD

**Issue by hematinik** [penge/my-notes#218]
There seems to be a problem with the sync. when I create a note and hit the sync button it works as expected on the first try, but when I go ahead and edit the document after a couple of open/close/refresh operations the sync process fails to work properly and the recent changes revert back to the previous version.
judging by the console logs the sync function performs the "SYNC - IN" instead of "SYNC - OUT" which in result you'll lose the latest edits.
![Screenshot_20210411_005504](https://user-images.githubusercontent.com/38541836/114284123-f7cfdf00-9a62-11eb-95f1-549402ccfe6b.png)

**Comment by penge** [comment]
Hi @hematinik 

I have just released version 3.7 that fixes this. It was sent to Web Store for a review. Should be available via an update soon – in a day or two.

Here's a screenshot what am I getting now on version 3.7. Tried several open/close and editing/syncing the same note a few times.

<img width="905" alt="sync_same_file" src="https://user-images.githubusercontent.com/907255/114284321-58552100-9a4f-11eb-998c-02be4ee3ee61.png">

Every time the changes went OUT as expected.

I'll keep the issue open so we can look at it once again after 3.7 is available.

**Comment by penge** [comment]
@hematinik New version 3.7 is out. Please, let me know if the problem persists or it's solved now.

**Comment by hematinik** [comment]
thank you dear @penge it seems like the problem is gone. I gave it a test drive and everything worked like charm. since I am not sure how to reproduce the problem I'll keep testing and will let you know the result in a day or two.
thank your for the quick update and all the effort on this great tool.

**Comment by hematinik** [comment]
After one day heavy usage the google drive sync is working as expected and I'll close this issue. kudos to you

**Comment by penge** [comment]
Happy to hear that. Thank you for testing!
