### ISSUE TITLE
Open on New Tab page not working as of latest update

### ISSUE THREAD

**Issue by jayarr100** [penge/my-notes#219]
Hi there,

Just wanted to let you know that the New Tab page funkiness seems to be back as of this latest (3.7.0) update. As of receiving the update in Chrome stable on Windows this morning, the extension is no longer opening as the New Tab page ever for me, despite that setting being activated in the option. It's not even inconsistent, like the last time; it just never does it now, from what I can tell so far.

Many thanks — hope all's well with you!

**Comment by penge** [comment]
Hi @jayarr100 

Option **"Open My Notes in every New Tab"** was removed in 3.7.0. **Reason:** It was slow and unreliable. I haven't found a solution that would allow to keep this optional (user can either enable or disable it) while solving mentioned problems. Different approach allowed to make it quick and reliable, but NOT optional. Not everyone wanted to have it always enabled. It was about 50/50.

So I went for a different solution: new quick way to open My Notes, is to use keyboard shortcut. That can be set here on this page `chrome://extensions/shortcuts`.

**Comment by jayarr100** [comment]
Ahh — sorry to hear that. It had seemed quite stable to me after the adjustments you'd made a short while back, and that NTP functionality was a key part of what made the app so useful and appealing to me. Totally understand that you've got a lot of different factors and priorities to balance, though. Thanks for letting me know.

**Comment by LuciusM** [comment]
Thank you, I was experiencing the same issue and since just opening a new tab was the only way I accessed my notes, I was afraid I could not acces my notes anymore.

**Comment by penge** [comment]
Hi, there are 2 possible ways how you can open My Notes:

- Click on icon in Chrome Toolbar (pin the icon for faster access)
- Keyboard shortcut (See Options, open `chrome://extensions/shortcuts`)
