### ISSUE TITLE
Feature Request: Add note number show in icon

### ISSUE THREAD

**Issue by yanickxia** [penge/my-notes#221]
my-notes is awesome chrome extensions. It's better if you add note numbers to the icon. Thanks

**Comment by penge** [comment]
Thank you!

I have prepared some examples how number in the icon can look. It can be number, it can be anything up to 4 characters in length. 

We can as well change colors. See examples:

<img width="36" alt="Screen Shot 2021-04-17 at 9 59 24" src="https://user-images.githubusercontent.com/907255/115106197-ae502a00-9f63-11eb-8b28-96a98fc0f1bd.png">

<img width="36" alt="Screen Shot 2021-04-17 at 9 58 52" src="https://user-images.githubusercontent.com/907255/115106200-b019ed80-9f63-11eb-87d0-57bb4cb1dbb3.png">

<img width="36" alt="Screen Shot 2021-04-17 at 10 03 36" src="https://user-images.githubusercontent.com/907255/115106330-801f1a00-9f64-11eb-9257-f03f50c9a514.png">

<img width="36" alt="Screen Shot 2021-04-17 at 10 04 29" src="https://user-images.githubusercontent.com/907255/115106339-890feb80-9f64-11eb-90e7-fcb3e026960d.png">

The question is, what value it brings to know how many notes you have based on the icon. I find it of no importance, a distraction.
But there may as well be other applications, which would make it very useful. Any ideas?

**Comment by yanickxia** [comment]
Because the note is a google extension, I don't save many notes on it. I just save some temp items on this, such as 
- todo list 
- some used command.  
The number for me is a notice.
----
Otherwise, I saw some alternative, the number is for this domain, they save notes for a site, where open a new page on site, the number will tell how note on this page

**Comment by penge** [comment]
Which color do you like from the examples?

**Comment by bhupesh-sf** [comment]
It makes more sense when we implement folders, where a folder could be a domain and a number indicator tell total notes in it.

**Comment by penge** [comment]
I think that makes more sense too compared to having some number in the icon.
