### ISSUE TITLE
Issues with giving color to text

### ISSUE THREAD

**Issue by bhupesh-sf** [penge/my-notes#236]
Remove format doesn't remove the color 
Ctrl + Z doesn't undo this but only text.

**Comment by penge** [comment]
There is no easy way to have this at the moment. Actions done by the [obsolete API](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) have Undo/Redo out of the box.

Custom history for Undo/Redo would have to be implemented. Undo/Redo for `surroundContents`, Undo/Redo for `replaceWith`, Unto/Redo for every command basically. Command pattern would be useful for that.

Not easy.
