### ISSUE TITLE
Ability to resize attached image

### ISSUE THREAD

**Issue by bhupesh-sf** [penge/my-notes#237]
Right now we can give a link to the image and it appears on the page but I should be able to resize that image to match my note formatting. Images we use are generally high quality and appear very big on the page, making the whole note a little odd.

**Comment by penge** [comment]
Thank you for the suggestion.

Let's say you can **drag image corner** (cursor will change to resizing cursor – see **Cursors**), and you can then use the mouse to resize the image down, or up (up to original size).

**Cursors:**
![image](https://user-images.githubusercontent.com/907255/116869029-372bbe80-ac10-11eb-9d8a-6a6ea7c37af6.png)
![image](https://user-images.githubusercontent.com/907255/116869060-4874cb00-ac10-11eb-9b53-a026e9042654.png)

Would that be fine?

**Comment by bhupesh-sf** [comment]
Yes it will work as long as I can resize all welcome :+1:

**Comment by penge** [comment]
This has been pushed quite a bit. We could achieve quite nice results if we add just option to modify pixel density. Not only we'll support Retina (or higher density) displays this way, but scaling picture in this precision (by half, by half, ...) could be enough.

**Comment by bhupesh-sf** [comment]
Didn't understand the RAW mode, can u explain?

**Comment by penge** [comment]
RAW mode allows to edit notes's HTML source and add any HTML or CSS. It can be also used to have plain text notes if no HTML is added. In the Toolbar, there is a new RAW button (with a tooltip Toggle **RAW**), to toggle the mode.

**Comment by penge** [comment]
@bhupesh-sf 

Glad to anounce this feature will be released in the next version. Here's a preview:

https://github.com/penge/my-notes/assets/907255/5d4fcf3e-5551-465f-adce-be4c44fec9b8

How it works:

1. Hold `Ctrl` (or `Cmd`) and move mouse over the image (order of these actions doesn't matter), move mouse wheel up and down (or use touchpad) to resize the image.
2. Double-click on the image to restore its original size.
