### ISSUE TITLE
Syncing fails across machines/browsers

### ISSUE THREAD

**Issue by MarkAPitt** [penge/my-notes#254]
I use My Notes on two machines. Notes are saved/synced to the same Google Drive folder, but now in different files with the same name.  Machine A reads/writes to one of the files, and machine B writes to the other version of the file.  I uninstalled and reinstalled the app on one machine, but this made no difference. The console log looks identical in both browser windows when saving. No errors are generated that I can see.

![image](https://user-images.githubusercontent.com/7736211/121227673-d5d3bc80-c859-11eb-8e25-8acfd86e6a68.png)

**Comment by penge** [comment]
Thanks for reporting. I'll check it out. Probably there's some issue that prevents using an existing file if not changed remotely (in Google Drive), or prevents merging with an existing file if changed remotely (in Google Drive), so in either of these cases, it creates a new file instead, to avoid overriding the data, although, in such cases, there is no need to make a file copy. Looking forward to fixing it.
