### ISSUE TITLE
Google Drive sync overwrites changes

### ISSUE THREAD

**Issue by skinnedpanda** [penge/my-notes#280]
I opened Notes, and started typing straight away. Suddenly everything I had written (except for the first couple of characters) where overwritten by the sync'ed version. This could perhaps be a bigger issue for people with higher internet latency.

**Comment by penge** [comment]
I suppose you have Auto Sync enabled, is that right?

**Comment by skinnedpanda** [comment]
Yes.

**Comment by penge** [comment]
I'll look into it.
