### ISSUE TITLE
Comments on Syncing

### ISSUE THREAD

**Issue by MarkAPitt** [penge/my-notes#285]
Perhaps the following text would be useful in the documentation. By coincidence, the second paragraph is related to issue #267. I do not know for certain that my employer turns off this feature, but it tends to occur when the OS is updated. I describe my work arounds and observations. I am not sure this constitutes an issue, but just trying to help out.

When syncing across multiple computers, the Auto Sync feature is a must, ensuring that My Notes is up to date on all of them. 

If your employer manages Google Chrome on computers on which you use My Notes, be sure to check periodically that the Google Drive Sync features is indeed syncing. Occasionally you might find this option unchecked, especially after a system update. When this happens, My Notes might fail to sync tabs with revisions once the option is rechecked. One way to ensure proper syncing going forward is to delete and recreate the affected tabs. One consequence of re-enabling syncing is that the contents of a note might be appended to that same note (creating in effect a copy). This will not occur for all tabs.

**Additional observations:** 
Day 1: I edited multiple tabs on My Notes on machine A. The day was interrupted by a critical system update (very unusual). After rebooting, I noticed that Google Sync was unchecked, so I re-checked the option and kept editing two tabs

Day 2: I am working on machine B. Only some of the updates to the tabs from machine A are present. I cannot say for sure whether only those that were made after the OS update are missing, but I know for a fact that some of them fall into this category. 

Day 3: I am on machine A again, having used machine B yesterday. The two tabs that I edited on machine B were appended to those same tabs on machine A (creating a duplicate below the original) once I synced machine A. The post-update changes (day 1) were not applied to the duplicate (this was only one tab). The top version had machine A changes from day 1. The bottom version had machine B changes from day 2. None of the other tabs was affected.

**Comment by penge** [comment]
Hi Mark,

See points below where I tried to address all concerns:

1. I think employer does not control your Chrome as I believe Google Drive is working for you, and My Notes was possible to install and run. As mentioned by yourself, the problem can be after OS (or browser) updates. You can check `chrome://management` (open in a new tab) to see if employer manages your browser or not.

2. I agree that Auto Sync is useful, and when working across different computers, it can be a must.

3. When My Notes is started, it checks if "identity" permission is still granted (it is required for Google Drive Sync), and if not, it disables Google Drive Sync. This "identity" permission can be granted when user checks "Enable Google Drive Sync", and removed when user unchecks "Enable Google Drive Sync". It seems there is some problem which causes to remove this permission even once the user has granted it, and didn't remove it by unchecking "Enable Google Drive Sync". I as well have experienced Google Drive Sync was disabled without my action.

4. The easiest way to spot Google Drive Sync is disabled, is to see "Sync now" button disabled, it also doesn't spin as disabled Google Drive Sync also disables Auto Sync.
 
5. When Google Drive Sync is disabled, notes are no longer linked to their files in Google Drive. Once Google Drive Sync is enabled again, it will check if notes and files have same modified time, making them safe to link. If modified time is different in any of them, they are merged (file appended).

Probably only solution is to change optional permission "identity" to a required permission. Optional permission seems to come and go even without user's action.

**Comment by MarkAPitt** [comment]
The problem has not occurred since the last system update.

**Comment by penge** [comment]
That's great to hear.
