### ISSUE TITLE
Add dark mode to options

### ISSUE THREAD

**Issue by psgoral** [penge/my-notes#29]
Like in title. White page is bad for people using dark modes.

**Comment by psgoral** [comment]
Ok, black dot changes background color. Sorry

**Comment by penge** [comment]
Hi @psgoral 

That's right. The **dot** can toggle between Light mode / Dark mode.

Actually, you gave me some good ideas now.

**Let me know what do you think about the following changes:**

1) Dark mode could be also applied to Options page, not just the text area.
2) Dark mode toggle (the dot) could be moved to Options page. It is something that is more-less 1 time action. Not changed often at all. Therefore it could be in Options page as a checkbox. And I guess that's where you searched for it in the first place.

I would say 1 is good.
2 is not necessary but, makes sense. Both 1 and 2 could be done.

What do you think?

**Comment by psgoral** [comment]
Hi @penge 
First option will be good. Just make it simple.
I have another ideas:

1. Add bullets [https://en.wikipedia.org/wiki/Bullet_(typography)](Bullet_(typography) to make a lists after enter "tab"
2. Add button to add another notes/lists like spliting in Atom etc.

Pic rel:
![2019-12-10 09_07_51-](https://user-images.githubusercontent.com/36134475/70507602-ff107100-1b2c-11ea-8d42-8919f7ba6d4a.png)

**Comment by penge** [comment]
Hi @psgoral 

Both ideas sound good.
I am considering adding them.

Regarding feature 1, let's say you may enable it via Options page and choose your bullet character (any single character you type in).

Regarding feature 2, I am soon adding multiple pages, see [this request](https://github.com/penge/my-notes/issues/27). It is similar to split panes although not the same. For the time being, switching between pages will be fast, even via shortcuts. Panes (horizontal or vertical) might come next.

Thanks for the suggestions!

**Comment by penge** [comment]
This one is solved.

The other requests (auto-insert custom bullets, and panes) are put into the backlog.
