### ISSUE TITLE
Notes copy themselves (and high CPU usage)

### ISSUE THREAD

**Issue by skinnedpanda** [penge/my-notes#292]
One of the notes got copied automatically over 200 times inside itself. The result might be why it reached the 5 Mbyte limit (ref. #291) The CPU usage was consistently high for a couple of hours.

The CPU usage stopped when I deactivated My Notes and restarted Chrome.

![image](https://user-images.githubusercontent.com/34305307/128612777-c16de453-ac60-41f0-9297-2758ba7fd2f9.png)

**Comment by penge** [comment]
I'll look into this tomorrow. Hopefully will reproduce it and fix it.

What do you see when you run this in the console?

```
chrome.alarms.getAll((alarms) => console.log(alarms.map((alarm) => alarm.name)));
```

The above command should list the names of alarms (alarm is used for Auto Sync every 6 seconds if notes changed). There should be just one listed.

Do you see many (like hundreds) of `SYNC - IN - *` messages in the console? I'll do some tests and first of all will try to get the same behaviour.

**Comment by skinnedpanda** [comment]
I'm monitoring the CPU usage to catch it when it happens.

**Comment by penge** [comment]
I am checking CPU usage too. So far everything ok. I think it may be a problem of Auto Sync.

**Comment by skinnedpanda** [comment]
The high CPU usage is back, but there are no alarms ("undefined") as of yet.

**Comment by skinnedpanda** [comment]
Discovered another symptom: it doesn't sync the duplicate text inside the note(s). NB! I removed the excess notes yesterday to get below the 5 Mbyte, and there is no error message about quota.

**Comment by penge** [comment]
Good. So no quota problem at least.

I was able to <ins>**reproduce**</ins> the problem now but under different conditions. I quickly opened My Notes 20x and then closed. Then I got 100% CPU.

**Comment by penge** [comment]
<ins>**Update:**</ins>

I think it will be Auto Sync after all. I have disabled it on initial open (when My Notes is open) and the problem didn't occur, even when I opened/closed 50 My Notes tabs. Will look into it.

**Comment by penge** [comment]
<ins>**Note:**</ins>
Auto Sync is using Google Drive Sync under the hood. It is used to sync notes on My Notes start (or when Auto Sync was enabled) and every 6 seconds when notes have chaged.

<ins>**Solving the bug was not successful:**</ins>
I have tried everything I could to solve this bug and <ins>**even completely disconnected**</ins> Google Drive Sync and Auto Sync, leaving us only with a few lines barebone that consists of these two API functions:

- https://developer.chrome.com/docs/extensions/reference/runtime/#method-sendMessage to send a message to other frames, which My Notes UI uses to ask the service worker to perfrom Auto Sync
- https://developer.chrome.com/docs/extensions/reference/runtime/#event-onMessage to receive a message in the service worker (in this case a message to Auto Sync) and do actions related

As said, I disconnected everything related to Sync/Auto Sync and `onMessage` became a complete dummy that only printed a simple text. Anyway, after disconnecting it all (and having nothing more to remove) I still was able to get 130% CPU usage just by quickly opening/closing 10+ My Notes tabs.

I have googled about this and found several places where service worker in extensions (introduced in Chrome 88) is causing 100% CPU problem. And it seems we are dealing with something that doesn't have a solution from our side:

- https://support.google.com/chrome/thread/95019579/google-drive-service-worker-high-cpu-usage-on-chrome-version-88-0-4324-96-official-build-x86-64
- https://bugs.chromium.org/p/chromium/issues/detail?id=1152793

After I removed `onMessage` from the service worker completely (which was printing a simple message only), the problem with the 100% CPU didn't occur again. But that was just removing the last pieces of the functionality.

Maybe there are some tricks or workarounds.

**Comment by skinnedpanda** [comment]
It's doing this regardless of Google Drive sync, or perhaps it is stuck there somehow. I disconnected Google Drive, turned off the extension, then loaded Chrome, seen normal CPU usage, but the moment I activate My Notes, it goes to what you see the screenshot is showing, and the duplication process continues within some of the notes. One of them has now been duplicated 14 times, and the other one 4 times.

![image](https://user-images.githubusercontent.com/34305307/128698187-dc6cae46-bd3b-4a20-997d-381a5c4cae5e.png)

**Comment by penge** [comment]
Try to run following:

```
/* ==== MAKES SURE AUTO SYNC OPTION IS DISABLED ==== */

// 1) Is it enabled?
chrome.storage.local.get("autoSync", (local) => console.log(local.autoSync));

// 2) Disable it
chrome.storage.local.set({ autoSync: false });

// 3) Is it still enabled?
chrome.storage.local.get("autoSync", (local) => console.log(local.autoSync));


/* ==== MAKES SURE AUTO SYNC ALARM IS NOT ACTIVE ==== */

// 1) Is there any active?
chrome.alarms.getAll((alarms) => console.log(alarms.map((alarm) => alarm.name)));

// 2) Clear them
chrome.alarms.clearAll()

// 3) Is there any active?
chrome.alarms.getAll((alarms) => console.log(alarms.map((alarm) => alarm.name)));
```

Haven't experience not even once note was copied to itself. Don't know what else should I try.

**Comment by penge** [comment]
Good news!!!! 🎉

I have now tried to manually send 100 and even 1000 messages at once to sync notes (the very simplified version that prints text for now) and CPU didn't even notice. So there's definitelly some bug that causes this.

**Comment by skinnedpanda** [comment]
> **Edit:** If Auto Sync is really disabled, calling chrome.alarms should result in:
> 
> ```
> Uncaught TypeError: Cannot read property 'getAll' of undefined
> ```
> 
> But this is not a solution, more like workaround. We still don't know what is causing 100% CPU (I experienced) or copy note in itself many times (I haven't experienced).

All of the commands gave "Uncaught TypeError". Now, all of a sudden the CPU has gone down to normal. I'll keep a watchful eye on it and let you know if anything else comes up.

Feel free to close this at your discretion. Let's hope the Google-team can come up with a solution. I have seen other posts of similar kind, but I am not savvy enough to know if it happens to be the same problem.

**Comment by penge** [comment]
Glad to hear the trick helped. The crucial part was:

```
chrome.storage.local.set({ autoSync: false });
```

which disabled Auto Sync.

<br>

I'll be now releasing version 3.11 which has some nice improvements.

**Comment by penge** [comment]
Damn it. Let's fix this.

I have experienced this issue only when I opened My Notes 20+ times (quickly in 2 seconds), closed about 10 tabs (quickly in 1 second), opened another 10, closed them, opened another 10, closed them. And then it got stuck on 130%. But that's very unlikely scenario. I believe it is happening for you in some very common use? How can I replicate that?

`chrome.storage` is available only in extensions (either in its tab or service worker). If you open My Notes and type `chrome.storage` there, it should print that it's an object.

**To see some logs:**

1. Open `chrome://extensions`
2. See My Notes
3. Click **"Details"**
4. Click on **service worker** (blue link)
5. See **"Console"** tab, to see logs related to sync

What would be suspicious? If logs would be in infinite cycle.

Something is causing infinite loop somewhere and even when I removed what Sync does (printed some text instead), it still was happening (scenario I described that I used). Going to check this out again.

**Comment by skinnedpanda** [comment]
Sorry, now I got it when I ran it under My Notes.

**Comment by penge** [comment]
In `chrome://extensions` you'll see:

<img width="415" alt="my_notes_extension" src="https://user-images.githubusercontent.com/907255/129215904-a67d76ea-9a68-4b93-943c-f4e476534266.png">

Where you can click on **service worker** directly (if visible there), or under "Details" (same thing):

<img width="1728" alt="my_notes_extension_service_worker" src="https://user-images.githubusercontent.com/907255/129216012-0d4cd858-a2d9-4401-9e1f-30324fca5f23.png">

In **Console** you can then see any outputs regarding Sync.

**Comment by penge** [comment]
@skinnedpanda Do you get 100% CPU when you open My Notes? Or only after you closed it? Does it happen always or sometimes only? What steps you follow when it happens?

**Comment by skinnedpanda** [comment]
I'll look at this more closely next week. I am swamped with work this weekend.

**Comment by penge** [comment]
ok

**Comment by penge** [comment]
I have released 3.11.1. It implements new Auto Sync.

**Comment by skinnedpanda** [comment]
I discovered that there were a few times that My Notes was not activated and the CPU went high. I googled and tried the suggestions under bullet point 3 to search for malware from this [Google support article](https://support.google.com/chrome/thread/60223994/constant-high-cpu-usage?hl=en&msgid=60264468), and it worked. It found 18 malicious instances within Chrome's environment. Afterwards I have run the computer with My Notes activated for several hours without any problem.

I'll try activating Auto Sync a little later.

**Comment by skinnedpanda** [comment]
Now I've run it for several days after resetting Chrome. It seems that one of the other extensions I have used in the past must've contained either bad or malicious code. I have not experienced any self-copying since, and I don't know if these issues were related.

On this issue, I don't see any more self-duplicating anymore.
