### ISSUE TITLE
Insert date and time creation inside each notes

### ISSUE THREAD

**Issue by yardstudio** [penge/my-notes#296]
Hi,
when notes are used oftenly, then is hard to remember, when was note createred. Some old notes can be deleted and date and time can help decide how old they are.

Some notes software allows insert this by key shortcut, but automatically added will be fine too

For example some notes software adding this by shortcut
![2021-08-11_10-41-48](https://user-images.githubusercontent.com/25852179/128998403-c2feaec2-445d-4d0e-9192-8a016c345039.png)

**Comment by penge** [comment]
Would this work?

<img width="1340" alt="date_and_time" src="https://user-images.githubusercontent.com/907255/129009808-04049ce1-f0f5-48ec-979f-3ffaf5e548e5.png">

**Comment by yardstudio** [comment]
Yeah, it will be great, I think

**Comment by penge** [comment]
Cannot use them. `Ctrl + T` is reserved for New Tab, `Ctrl + D` to Save to bookarks.

**Comment by yardstudio** [comment]
> Cannot use them. `Ctrl + T` is reserved for New Tab, `Ctrl + D` for Save to bookmarks.

CTRL+SHIFT+D and CTRL+SHIFT+T are free ?

**Comment by penge** [comment]
`Ctrl + Shift + D` = Bookmark all tabs
`Ctrl + Shift + T` = Restore closed tab

Here is a list of shortcuts:
https://support.google.com/chrome/answer/157179

**Comment by yardstudio** [comment]
> `Ctrl + Shift + D` = Bookmark all tabs
> `Ctrl + Shift + T` = Restore closed tab
> 
> Here is a list of shortcuts:
> https://support.google.com/chrome/answer/157179

CTRL+ALT+T and CTRL+ALT+D ? :)

**Comment by penge** [comment]
I forgot these actions have shortcuts already, same like in Excel. See Options page for details.
