### ISSUE TITLE
shortcuts confict on Mac

### ISSUE THREAD

**Issue by namhokim** [penge/my-notes#299]
There is shorcuts confict on "⌘ + Shift + M".

my-notes : [Open My Notes](chrome-extension://lkeeogfaiembcblonahillacpaabmiop/options.html)
<img width="711" alt="ScreenCapture 2021-08-14 08 20 59-1" src="https://user-images.githubusercontent.com/1442538/129426559-bc1d5734-240d-4f8b-adad-45bacf6c5566.png">
chrome: [Log in as a different user, browse as a Guest, or access payment and password info](https://support.google.com/chrome/answer/157179?hl=en#zippy=%2Cgoogle-chrome-feature-shortcuts)
<img width="680" alt="ScreenCapture 2021-08-14 08 21 26-9" src="https://user-images.githubusercontent.com/1442538/129426626-26cc0622-95e1-4bfe-8fd4-5886373f4d0c.png">

I haven't reviewed all the shortcuts, but the most important ones are overlapping.

**Comment by penge** [comment]
Would you like to keep the default behavior of `⌘ + Shift + M`?
You can change the shortcut to Open My Notes at `chrome://extensions/shortcuts`.

**Comment by namhokim** [comment]
I was confused.
`Open my notes shortcut` was  not a basic function. It should be set at `hrome://extensions/shortcuts` by user.
But I am concerned about is that the example of `⌘ + Shift + M` is default chrome behavior like the image above.

**Comment by penge** [comment]
Yes, default behavior is as in the image. Some shortcuts can be fine to override if not important. But there is still option to customize this one if need the keep the original shortcut.
