### ISSUE TITLE
Save button to save notes for later

### ISSUE THREAD

**Issue by MichaelWehar** [penge/my-notes#3]
It would be great if there was a save button.  This would allow users to save notes to a file or within the browser for later use.

**Comment by penge** [comment]
Challenging, but, I'll look at the options.

**Comment by ColinCPhysna** [comment]
Was just about to mention this, If I have have time this week a may submit a PR, thinking about just using the Google Drive API to save notes

**Comment by penge** [comment]
Hi,
If notes are saved in Chrome, is it necessary to put them to the Drive?

To save notes, you need to also think about loading them. (Besides the authorization).

Consoder the benefits and how often people might manage multiple notes. And switching between them. Google Documents is a good solution in that case.

I am thinking about notes as a temporary thing, notes, todos, something that is not meant to be managed, nothing bad would happen if you erase them. I think, if important documents are stored in Google Drive, they should be also managed there.

Please let me know your thoughts on this.
Besides anything I have said, I really appreciate your effort and looking for new ideas.

All best,
Pavel

**Comment by penge** [comment]
Closing for now.
