### ISSUE TITLE
Bug: strikethrough/italic links not opening with Ctrl+Click

### ISSUE THREAD

**Issue by khoaDLuu** [penge/my-notes#308]
This seems to be related to #243.
A link won't open in a new tab when I do a Ctrl+Click if it is formatted with Strikethrough or Italic.
There may be issues when using a combination of these format options and others as well.

**Comment by penge** [comment]
Hi @khoaDLuu,
Thank you for reporting this issue.

I have checked it and having a solution ready. I will test few more times. On Monday or so, it will be available via automatic update.
