### ISSUE TITLE
Continuous syncing shifts the cursor to the beginning

### ISSUE THREAD

**Issue by bhupesh-sf** [penge/my-notes#309]
As soon I start typing on every change it starts syncing and as soon as it sync cursor moves to the beginning of the note. So it hampers by typing. While writing itself cursor moves to the beginning.

**Comment by jpatterson1830** [comment]
I have the same problem (it started with version 3.11.2). I had to turn off Auto Sync to be able to use the app.

**Comment by penge** [comment]
Sorry for late reply. I have now free time to look at it. Having just one question. When you have experienced this, did you have only 1 open tab with My Notes, or more of them?

**Comment by bhupesh-sf** [comment]
It happens with one tab also.

**Comment by penge** [comment]
I am trying it now and haven't experienced it yet but will continue trying. Is it happening for you every time or under certain conditions only? Here's what I do: I type, I continue typing, Auto Sync starts to sync, I still type, the cursor is at the end for the whole time.

**Comment by bhupesh-sf** [comment]
Generally, if I continue typing cursor reached the top of the document. But if I type something and stop typing then it stays there. This is something I observed.

**Comment by penge** [comment]
@bhupesh-sf 
I have made one improvement that should solve this issue. Tomorrow (or once version 3.11.3 will be published - it is in pending review now, and need to wait for that to finish first) I will post this to Web Store under a new version 3.11.4.

_Some notes:_
There's **only one location** in code that can potentially cause this problem. When note is updated by Google Drive Sync, or by My Notes Context menu, or in other words, in any other way than **"user is typing"**, it should refresh the content of that updated note. That is why cursor jumps to the beginning. But, it should _NOT_ refresh the content of the note if you're typing into it, only in other tabs if it's open there also. So, that's basically the issue. As there's only one location in code where this problem can occur, that's where the improvements and fixes will be put. In case the problem would continue after version 3.11.4, we can look at it again. Meanwhile, I'll be testing 3.11.4 and do further improvements if needed.

**Comment by bhupesh-sf** [comment]
ok, great. Thanks @penge
