### ISSUE TITLE
SOLVED: Won't sync from drive (Win 10, chrome)

### ISSUE THREAD

**Issue by Alexbba** [penge/my-notes#313]
Sync enabled in settings, - on this my new Windows 10, Lenovo Ideacenter 3, but won't sync my notes even though it says the notes are being synced - been waiting 24 hours now.. I have two google accounts and am signed in to both. Does this matter? Is the problem that mynotes is being connected to the account it wasn't first connected with?

**Comment by penge** [comment]
Hi @Alexbba,

To your question – Yes. Same account needs to be used to access the same notes.

**Comment by Alexbba** [comment]
Which account is it now connected to?!

**Comment by Alexbba** [comment]
How do I know if it has switched the account connection?

**Comment by penge** [comment]
You can check that by opening the google drive link. If it opens Google Drive under the same Google Account as the one you are currently using in Chrome, it should be fine. Alternatively, sharing My Notes folder in Google Drive to your other account as "Editor", should also work. I haven't tried the latter though.

**Comment by Alexbba** [comment]
Same account connected as before. Days it might take to sync?

**Comment by penge** [comment]
It should take no more than a few seconds. Looks like there might be some issue.
Is the Sync now button spinning forever? Do you see some messages in Chrome Console (see Developer Tools) that would suggest it's syncing?

**Comment by Alexbba** [comment]
Yes, spinning forever. I don't have chrome console.

**Comment by Alexbba** [comment]
SOLVED: Today, when opened, it was synced (took about 40 hours)!
