### ISSUE TITLE
Can't open My Notes

### ISSUE THREAD

**Issue by KennyRay549** [penge/my-notes#315]
I am using the  Brave browser, which is based on Chrome. I have been using My Notes for quite some time with no problems. A week or so ago I was suddenly unable to open My Notes by clicking on the My Notes icon in the Extension List. I am not sure what happened, but if there are some debug logs I can look at, that would be super awesome.
Note: If I close all tabs in the browser, then open the browser, My Notes will open, because I have it set as one of the tabs to open when the browser is first opened. If I close My Notes, I cannot reopen it.

**Comment by penge** [comment]
Hi Kenn,

the problem seems to be that Chrome doesn't start the extension after it
unloaded it (to save resources).

I am observing it for some time now and not sure what I can do to solve it.
One thing that definitely helps, is to go to the extensions page (open
chrome://extensions in a new tab), find My Notes, turn it off and on, it
should solve the issue.


Pavel

**Comment by KennyRay549** [comment]
Hello, Pavel,

Thank you for your quick response. I will try turning the extension off and
back on as soon as I can.

Also, I would be glad to do any Alpha or Beta testing for you. I have been
a programmer for 45+ years, and I enjoy working on various projects.

Thanks!!!
---
Kenn Simons, Sr.
PO Box 656
Ozark, MO 65721
Tel: 417.839.9967

**Comment by penge** [comment]
Hi Kenn,

That would be great!

Let me prepare some notes on how to set up My Notes for local
development/testing.

I will post it here in a bit.

Pavel

**Comment by penge** [comment]
Hi @KennyRay549,

Here are some notes on the development/testing of My Notes.

**Communication:**
First and foremost, to share our findings during the testing, some good channel could be used to share screenshots (if needed to show the problem), or to get reply quickly. It could be, for example, Discord. Any preferences? Suggestions?

**What version would be tested:**
I would always prepare a separate branch here on GitHub. Example of the branch name:
**3_12_beta**
Any time there would be an update:
**3_12_beta2**
And so on.
You would be informed about the updates on the channel we would agree to use.

**How to install My Notes for the local development/testing:**
My Notes is developed in TypeScript and Nodejs. To set up the project, you would:
1. Check out the branch we are testing.
2. Install the packages if not done before (`npm install`).
3. Build the project one time for development (`npm run develop`).
4. Import the extension in Google Chrome (see below).

**How to import locally developed My Notes in Google Chrome:**
The steps are:
1. Open chrome://extensions in a new tab.
2. Enable **"Developer mode"** via the toggle.
3. Click **"Load unpacked"** button.
4. Navigate to "build" folder that is produced by the 3th step from the last section.
5. Click "Select" to load the extension.

You should then see My Notes added to the extensions list.

**How to test/develop Google Drive Sync locally:**
To make Google Drive Sync work locally, you will need to set `MY_NOTES_CLIENT_ID` environment variable first.
If that's not necessary for the test, it's not needed.
Either way, if you'd be interested, I can create one client ID for you in Google Cloud, and send it to you privately.


I think that's all for the introduction. If you'll have any questions, please let me know.
