### ISSUE TITLE
Automatic TOC for the note

### ISSUE THREAD

**Issue by bhupesh-sf** [penge/my-notes#316]
It will be helpful for longer notes to have an automatic table of contents on top having all the headings there. It helps me to know what all I have on the page as well as quickly jump to that section. It doesn't need to be nested (as these are not word docs), just heading list

I could find quick implementations in JS:
[https://projectcodeed.blogspot.com/2020/04/an-automatic-table-of-contents.html](url)
[https://stackoverflow.com/questions/187619/is-there-a-javascript-solution-to-generating-a-table-of-contents-for-a-page](url)

**Comment by penge** [comment]
I like the idea! Definitely would like to add it.

Some questions:

1. Do you think it would be better to have an option to quickly toggle (on/off) the TOC in notes? Maybe it could be in the Sidebar as a new icon.
2. If only first level sections would be listed in TOC, that means H1 headings, right?

**Comment by bhupesh-sf** [comment]
1 - This can be on/off OR collapsible div which can be refreshed as well.
2 - The first level I think is the wrong word selection. I meant all heading without indentation for now (if it adds to complexity)

**Comment by penge** [comment]
1. Will think about it. I like the collapsible idea.
2. Sure, can do it. Also with indentation. No complex.

**Comment by bhupesh-sf** [comment]
great, looking forward. Also horizontal line will help greatly with this as it really helps to differentiate between sections within a note

**Comment by penge** [comment]
I am planning to add the horizontal line very soon. Also I have a next version ready that fixes the jumping cursor to the beginning. Would you like to try it out if it works for you? You would need to be able to checkout the repository in a specific branch I would add, and install My Notes for local testing (can assist if needed) and set My Notes Client ID (for Google Drive Sync) which I would also provide. If no, no problem, I can publish it to Web Store. Good thing about testing it first thought, is that it can be quicker and we make sure it really works. It could save us days or even week, as reviews on Web Store take some time.

**Comment by bhupesh-sf** [comment]
Hey @penge Yes I can surely try it out. Let me know how can I do that? I will provide the feedback after testing it out for a day.

**Comment by penge** [comment]
Hi @bhupesh-sf, I have created Discord where we can talk about details:
https://discord.gg/xz6MbjdA

**Comment by penge** [comment]
@bhupesh-sf
How useful this feature would be to have?
How many Headings do you normally have?

**Comment by bhupesh-sf** [comment]
I generally have around 10 heading and each heading have a good amount of content, so it becomes a decent scroll.

**Comment by penge** [comment]
@bhupesh-sf

Listing a few options how this TOC feature could work:

A. having a sidebar **on the right** (on/off = show/hide) with TOC updated as you type, or,
B. reuse sidebar **on the left** (on/off = TOC/notes list) with TOC updated as you type, or,
C. a new **TOC button** in the Toolbar that would insert TOC (not updated as you type).

In any case (A, B, or C), headings in the list would be **_links_** you can click on and that would scroll down to the heading.

A or B **pros:**
- TOC visible at all times (can jump between headings without having to scroll back to top)
- TOC updated as you type

C **pros:**
- can be customized (not only making some list items bold, italic, change color, or edit titles or add some comments, but also able to remove any N-th level items that are not needed - for example, somewhere 2-nd level items are needed, but somewhere else aren't) 
- easiest to implement (we could have this feature within a week)

C seems the best. Customization is a huge plus. Jumping quickly back to the top of the page should be no issue, we have shortcuts like `Cmd + Up`. To refresh TOC, easiest would be to select it, remove, insert again. But as it could be customized, it would be even possible to add or remove list items manually.

What do you think? Let's go for C?
