### ISSUE TITLE
Import ?

### ISSUE THREAD

**Issue by LeninZapata** [penge/my-notes#329]
Hello, I just formatted my PC and exported all my notes, but when I already have my system updated and I want to import My notes, I realize that it does not have the option to import

why doesn't it add this so basic option?'

**Comment by penge** [comment]
Hi @LeninZapata 

Thank you reaching out. I will add import from a ZIP file in **_next version._** At this point, you can import notes only one by one, by moving a file over the bottom left part of the sidebar.
