### ISSUE TITLE
Unable to copy a table and align it to centre or right

### ISSUE THREAD

**Issue by bhupesh-sf** [penge/my-notes#332]
I was just trying to do some stuff with tables and found a few issues.

When trying to copy a table to some other place within the note, I cannot.
Wanted to align a table in the center again I cannot.
The movement of the cursor with arrow keys within the table is not very good. It goes to the edge of the corners of the columns and then go inside the column.

Another good thing would be to have a background option for rows..

**Comment by penge** [comment]
Let me look at it.
Copying a table is possible, but not comfortable at all - you would have to select table with one line above and below it, to copy and paste.

Seems like there's more to be done around tables - copy, align, etc.
How about we fix **copy** and **align** first.
Any ideas how it should be done?

**Comment by bhupesh-sf** [comment]
I believe if we can add context menu to tables that will be perfect, otherwise have to be checked with other applications out there to check the best way out...

**Comment by penge** [comment]
Sounds great. Let's add context menu then.

**Comment by penge** [comment]
Hi @bhupesh-sf 

Here is a preview of Table Context menu, that can be used to **align the table** (Left / Center / Right).

https://github.com/penge/my-notes/assets/907255/6db17758-11b8-44fd-a6a3-fe9af3b2cc30

This Context menu would be displayed when you would hold `Ctrl` (or `⌘`) key, so the browser's Context menu could still be used when needed inside the table.

<br>

**Note:** I have also one version with a **Copy** button as well, but it was always inserting a new line feed to the new table's last cell (so the tables were not exactly the same), which I didn't like. Selecting all table text, and copying the table that way, didn't cause this problem.

**Note 2:** I think this table alignment is already a nice feature, so I'd like to release it soon.
