### ISSUE TITLE
Add option to change cursor focus to address bar

### ISSUE THREAD

**Issue by milind-utsav** [penge/my-notes#333]
Trying to set up new tab and My Notes with a single shortcut Cmd+T.
In the current behaviour, the cursor is focused on the note. If I have to type something in the address bar, I have to first move the focus there.
An option to keep the cursor focus default behaviour can be introduced to achieve this.

**Comment by penge** [comment]
Hi @milind-utsav 
Extensions that replace every New Tab by default, have the address bar selected when open. This is not our case.

**Workaround 1:**
I would suggest using a separate shortcut for My Notes, such as Cmd+Shift+M – in this case, the content will be focused.
And keep Cmd+T intact – the address bar will be focused.

**Workaround 2:**
If **"Indent text on Tab"** is _NOT_ enabled, you can change focus between the address bar and note using the Tab key.
