### ISSUE TITLE
Creating backup in wrong user on Google Drive

### ISSUE THREAD

**Issue by GeoNomad** [penge/my-notes#343]
I am new and just trying out the extension so may be a user error.

I set up sync and made sure Chrome indicated that I am in the correct user profile 0 with the correct email address.

I clicked on the permission box and auto sync and saw that it was synced and with a date.

When I looked on Drive I couldn't find anything. Then I clicked on the URL shown in the settings.

It told me I needed permission and asked for it. That sent me an email.

Turns out the new folder was created in user 2 not user 0.

Really interesting. If I change the link URL shown in the settings from 

https://drive.google.com/drive/u/0/folders/etc...
to 
https://drive.google.com/drive/u/2/folders/etc...

I do see the note. I have not been able (at the user interface level) to see how to place this folder in u/0 where I want it to be.

But it looks like an interesting project and I might dig in further.

It seem odd that it got permission to install in user 2 as nothing I saw indicated that Drive account.

On a different computer where I only have 1 account being used by Chrome it correctly backed up to u/0. I am assuming if both computers use the same user I can share notes across computers. No?

**Comment by penge** [comment]
Hi @GeoNomad,

My Notes will install its folder for the currently logged-in user in Chrome. You can check that at this page:
`chrome://settings/syncSetup`

If the same user account is used on both computers, it should result in using the same notes folder.

I hope this helps to resolve the issue.

**Comment by GeoNomad** [comment]
That is what I expected. I have checked chrome://settings/syncSetup which shows the account I want to sync to.

However the sync was not created in that account. It was created in a different account. I have 3 accounts and the URLs for Drive, Gmail etc show 3 different URLs with u/0 u/1 and u/2.  Although the sync setting shows u/0 and the URL shows u/0 the actual sync files went to u/2.
