### ISSUE TITLE
It has no any occur when i click button of "Enable Google Drive Sync"

### ISSUE THREAD

**Issue by andyliuxp** [penge/my-notes#350]
Hi, writer:
thank you for your help.
my pc's os is debian bullyeye,
browse is chrome 98.0.4758.102,
I 'm from china though VPN (HOXX),
It has no any occur when i click button of "Enable Google Drive Sync"
Please,
thank you again!

**Comment by andyliuxp** [comment]
of course.
I have sync enabled in chrome. other plugin no problem.

**Comment by andyliuxp** [comment]
HI,
my sync setting: sync all data type.

**Comment by andyliuxp** [comment]
I try do it under win10,the result is same.

**Comment by penge** [comment]
Can you check Chrome Console (Menu / More Tools / Developer Tools) for messages it prints while you try to enable Google Drive Sync? What it prints?

**Comment by andyliuxp** [comment]
Permissions - Requesting permission "identity"
background.js:1 Permissions - Acting on added permission "identity"
Unchecked runtime.lastError: OAuth2 request failed: Connection failed (-7).

**Comment by andyliuxp** [comment]
Permissions - Requesting permission "identity"
background.js:1 Permissions - Acting on added permission "identity"
Unchecked runtime.lastError: OAuth2 request failed: Connection failed (-7).

**Comment by andyliuxp** [comment]
I see,I see , It maybe is network problem, the problem will  reslved  if "my notes" can access network through chrome proxy.
I don't know my suggest wheather right.

**Comment by penge** [comment]
It seems to be exactly it, as you say.

**Comment by andyliuxp** [comment]
Hi,
Can you upgrade your "my notes" for resolve the problem?
wheather have You  a play to resolve it?
Thank you for your help.
