### ISSUE TITLE
Google drive sync stops working in version 3.18

### ISSUE THREAD

**Issue by tri-bao** [penge/my-notes#360]
Chrome version: `99.0.4844.51 (Official Build) (x86_64)`
OS: `MacOS`
My Notes version: `3.18`

---
Every time the plugin gets updated, the check box "Enable Google Drive Sync" resets to unchecked. That's fine as I can have it checked again. However, after the update `3.18`, marking checked on that checkbox  doesn't take effect: When I close the Options tab and reopen it, the checkbox is still unchecked. And the result is that all notes are not synced to GDrive.

Looking at Chrome's inspection console, when the check box is checked, the following log is printed:

```
Permissions - Requesting permission "identity"
```

When I uncheck it, the following additional lines are printed

```
Permissions - Removing permission "identity"
background.js:1 Permissions - Removing permission "identity"
background.js:1 Permissions - Acting on removed permission "identity"
background.js:1 Permissions - Removing permission "identity"
```

Then check it again, 2 following lines appear

```
Permissions - Requesting permission "identity"
background.js:1 Permissions - Acting on added permission "identity"
```
No error, nothing shown on the "Network" tab

**Comment by tri-bao** [comment]
update: after a while, the following error shown on the inspection console:

```
Unchecked runtime.lastError: OAuth2 request failed: Connection failed (-118).
Unchecked runtime.lastError: OAuth2 request failed: Connection failed (-356).
```

**Comment by penge** [comment]
I would get similar error if I am not connected to the Internet.

```
Unchecked runtime.lastError: OAuth2 request failed: Connection failed (-106).
```

I wonder what are those status codes, -118 and -356.

**Comment by tri-bao** [comment]
Internet connection was OK. Chrome's profile is the account to which `My Notes` is synchronizing.

It is working fine on Ubuntu chrome but not my MacOS chrome. I'm happy to provide more information if you need

**Comment by tri-bao** [comment]
An update, if I sign out from my profile on chrome (that means everything will be deleted locally) and sign in back, `My Notes` will start synchronizing again
