### ISSUE TITLE
[feature request] Raw mode

### ISSUE THREAD

**Issue by adab4d** [penge/my-notes#361]
Please add back a plain text mode.
This would just be a switch to turn HTML rendering on/off, no conversion required.

Following #72 and related I see this was the case up to a certain point.

I have been having issues with plain text notes (actually org-mode), I type in text but then copy and paste pieces around and the automatic HTML conversion starts addding an insanity of nested elements, at times with inline style. 

I figure this is the root of the issue, so just having a plain text storing of the file would solve it.

**Comment by penge** [comment]
Hi @adab4d,
Typed text is transformed into HTML by the browser (I don't have control over it, unless implemented it from scratch). The resulting HTML might not be nice, but in the end it represents what was typed and that's important.

Regarding editing note in **plaintext-only mode**, I am thinking about adding it. To have this feature in a timely manner, notes would continue to be stored as HTML files, regardless if one is edited as plaintext or HTML, as this could be a setting that could be changed at any moment. Also this setting would not be synced into Google Drive, it would be a local setting only. So basically, I need to think about how switching between HTML/plaintext would work. Any ideas?

**Tip:** `Ctrl + V` will paste the content **with formatting**, as HTML if that's the case. If you'd wish to paste the content **WITHOUT formatting**, as plain text, you can use `Ctrl + Shift + V`.

**Comment by adab4d** [comment]
Thanks for replying.

Notice I am already using `C-S-v` when pasting, but as soon as I start typing enter, without even copying and pasting any inside the current buffer the html stuff appear.

Why would this be client only? 
You could use a containing HTML element (even a custom `<html-note>` one), anything not starting with it is plaintext.

**Comment by penge** [comment]
> Why would this be client only?

I just wanted to make it easier for myself but there's no reason not to have it synced from the beginning. So let's sync it.

> You could use a containing HTML element (even a custom `<html-note>` one)

That's a good idea to consider, haven't thought of it. Good as this custom tag would be part of the content of the note and sync of the note wouldn't need to be updated, it would continue to work as is.

The problem with `<html-note>` is, that any created note so far, would become **plaintext** if it isn't wrapped in this tag. This could be solved by having an inverted tag, which if not present, it's **html** note. Something like:

```
<note type="html"><! –– if not present, it's html by default ––>

</note>
```

and

```
<note type="text">

</note>
```

Which brings me to that html comments could be a solution too.

There are a few more problems in using a custom tag:
- it's ambiguous, the content still can be html especially if edited in other editor
- it requires all notes to be migrated during editing to have this tag as part of their content
- when editing, we need to make sure this tag does not disappear, especially when you hit backspace to remove all the content; in that case, it would be better if you edit only the first child of this tag which is the real content

Another approach which I am now keen on using, is to store this information (html or text) outside the note as a way to tell us how to consume the note (as html, or as text). This could be stored on the client (browser) as a note's new attribute called **"type"** with a default set to **"html"**. No migration would be needed and no note content would have to be updated. When the user would switch the **"type"** (html as default), it would be stored as the note's attribute (not in its content). The syncing of this information could be done using **"properties"** (just checking Google Drive API, more about that here: https://developers.google.com/drive/api/v3/reference/files/create and here: https://developers.google.com/drive/api/v3/reference/files/update).

Let's double check it first if we are on the right track here. But I think this would work nicely.

Next think we would need to agree on, is:
1) How we would like to change the type of the note (html or text)?
2) How the UI would look in text mode?

My idea so far:
1) There would be a toggle left to the info icon (toggle between html or text).
2) Toolbar would have all controls (B, I, U...) except info icon, hidden in text mode. (hidden so it's not confused with **"Lock"** mode)

Suggestions?

**Comment by adab4d** [comment]
> There are a few more problems in using a custom tag:
> 
> * it's ambiguous, the content still can be html especially if edited in other editor
> * it requires all notes to be migrated during editing to have this tag as part of their content
> * when editing, we need to make sure this tag does not disappear, especially when you hit backspace to remove all the content; in that case, it would be better if you edit only the first child of this tag which is the real content

The migration would be automated and since HTML is the current standard any note not having a type would gain a type="html" container.
What I am thinking about is a containing element just for storage, you unwrap the content when filling the editing area, then wrap the area content when saving it. 
i.e. the file would have the `<note></note>` element but the edit area in My Notes would just not display. Everything else would stay the same.

> Next think we would need to agree on, is:
> 
> 1. How we would like to change the type of the note (html or text)?
> 1. How the UI would look in text mode?
> 
> My idea so far:
> 
> 1. There would be a toggle left to the info icon (toggle between html or text).
> 1. Toolbar would have all controls (B, I, U...) except info icon, hidden in text mode. (hidden so it's not confused with "Lock" mode)

1. I agree on the toggle, with a stylized `H` for HTML and `T` for plain text
1. either hide altogheter them or disable them and make them grey, I prefer the latter since I do not like UI elements moving


>  When the user would switch the "type" (html as default), it would be stored as the note's attribute (not in its content). The syncing of this information could be done using "properties" (just checking Google Drive API, more about that here: https://developers.google.com/drive/api/v3/reference/files/create and here: https://developers.google.com/drive/api/v3/reference/files/update).

> Let's double check it first if we are on the right track here. But I think this would work nicely.

I use Insync to sync GDrive, I figure that would not keep the property but I am just guessing here. 

I think as long as there is a setting for "Default note type [ HTML | text ]" that would affect a new note or one without propert this would be fine and a proper use case for the property feature.

**Comment by penge** [comment]
@adab4d 
Thank you for the feedback. I'll look into this in the upcoming days and come up with a prototype, post it here and we can confirm it. I'll check Insync if it will sync even custom properties like type (html or text) but I believe it will. I will take that into consideration to have a solution which would be synced properly.

**Comment by adab4d** [comment]
I don't think it's up to you to check that, you have done enough already. I was just thinking that spanning over different filesystem the syncing program won't keep that info.

Again it's not a big issue.

**Comment by penge** [comment]
I'll be adding this feature to My Notes 3.22.
It will be called **Raw** mode. What it will be for, is raw editing of note's HTML but can as well be used to stay Raw to have that plaintext functionality (by having a text without HTML tags in it). Raw (off or on) will be synced to the Google Drive for each note. Each note will remember this setting when you'll come back. By having Raw, we achieve both:
- plaintext (when you stay in Raw and type just text)
- editing HTML markup when needed to tweak or add any valid HTML (that includes adding any valid CSS as well; inline JS will be excluded/escaped for security reasons)

**Comment by penge** [comment]
**RAW** mode is near complete (implementation done, slight changes may happen) and will be released during this week.

> Note: I have decided _NOT_ to sync the information (RAW ON or OFF per note) to Google Drive as this setting will be often toggled. But, I have found something else worth improving that I will look at, to make sure not so long ago added note properties remain intact after sync (pinned, locked, or RAW) so they stay saved locally or per computer.

Here are the **_first screenshots_** of the upcoming **RAW** mode I'd like to share with you:

<img width="1342" alt="raw_1" src="https://user-images.githubusercontent.com/907255/170169037-de5f9a13-0c9a-4f3d-b1c6-941bd9242294.png">

As you can see, there's **a new button** called **RAW** with a slight _light_ touch to it so it's not disturbing or confused with other buttons. I have decided to go with a button as it's really quick to toggle. The button is placed as first because how you choose to edit (HTML or TEXT) comes as first to mind. Also to minimize the distance between notes list and this toggle.

<img width="1342" alt="raw_2" src="https://user-images.githubusercontent.com/907255/170169725-669da9d9-6dff-47e0-ada4-c22de3da5e1d.png">

Once you click on the **RAW** button, you are in RAW mode and can edit plain text or HTML depending on what you'd prefer. When you are in RAW, the button has high contrast (orange) to quickly what's going on.

There is a simple tooltip:

<img width="489" alt="raw_3" src="https://user-images.githubusercontent.com/907255/170171680-a60be371-f6a6-418b-a2bb-fae6083d1067.png">

I hope you'll like this upcomming feature.

**Comment by adab4d** [comment]
Thanks, much appreciated.

**Comment by penge** [comment]
I have added side-by-side editing of the same note. Editing **HTML** or <ins>RAW</ins> (video in previous comment), or vice versa. Implementation is now complete. I will test it. Release in about 2 days.
