### ISSUE TITLE
Share notes between Google accounts

### ISSUE THREAD

**Issue by alexgv99** [penge/my-notes#364]
You know what could be super nice? If I could share a note with other my-notes google users...

**Comment by penge** [comment]
That's something I would definitely like to add.

It could be read-only or with writing (collaboration).

**Comment by alexgv99** [comment]
have you finished? or just gave up the idea?

**Comment by penge** [comment]
I like the idea, but it is too complex to be done now. I will need to think about it and hopefully can up with some easy solution. If you have any ideas how it could all work from the user perspective and what the expectations on the feature would be, feel free to share it here.
