### ISSUE TITLE
Sync not working

### ISSUE THREAD

**Issue by scody3** [penge/my-notes#365]
Can seem to get the sync working. I've installed it from the chrome web store but nothing syncs, I do love the extension.

**Comment by penge** [comment]
Hi @scody3,
what browser are you using? Is there any message when you try to sync? How it shows?

**Comment by scody3** [comment]
I'm using a chrome browser. I can check the sync box in options, but the
sync option doesn't light up on the main page.

**Comment by penge** [comment]
Hi @scody3,
is there any error indicating what might be happening? Can you try to open Chrome Console (https://balsamiq.com/support/faqs/browserconsole/) and repeat the process to see if there are any messages?
