### ISSUE TITLE
sidebar hotkey not working - need alternate way to open a new note w/o the sidebar windows 10

### ISSUE THREAD

**Issue by bdfox507** [penge/my-notes#368]

**Comment by bdfox507** [comment]
unable to get to the sidebar to open a new note - need alternate way to create a new note - not sure if the CTL-S hotkey is being blocked or not would appreciate another way to open a new note - Thanks !!

**Comment by penge** [comment]
Hi @bdfox507,
What browser are you using? Is there something else that happens on CTL-S or nothing happens at all?
We can try to change the shortcut to something that would not be in conflict.

**Comment by bdfox507** [comment]
thanks for the response - nothing happens - chrome Version 100.0.4896.75 (Official Build) (64-bit) 
is there an alternate way to open a new note other than that icon on the sidebar ?

**Comment by penge** [comment]
At the moment, **a new note** can be created only by clicking **on the icon** in the sidebar. Would you like to have a shortcut for that? How about show/hide sidebar shortcut? Is that one working for you? I am not sure now.

**Comment by bdfox507** [comment]
thanks again - anything that will allow me to get to the sidebar that is now permanently hidden would be awesome !!
btw this tool is amazingly useful and easy !! thank you so much - i am now dependent on it

**Comment by penge** [comment]
Glad to hear that. Thank you. I will add a shortcut to create a new note.

**Comment by bdfox507** [comment]
coffee is on me

![snap011](https://user-images.githubusercontent.com/104117728/164588578-131351e2-5b5a-4666-81e8-8bb005c507e9.jpg)

**Comment by penge** [comment]
@bdfox507 Thank you! Really appreciated.

Here's a quick workaround for now on how you can show the sidebar:
1) Inside My Notes, open [Chrome Console](https://balsamiq.com/support/faqs/browserconsole)
2) Enter the following command into the console:
```js
chrome.storage.local.set({ sidebar: true });
```
3) Refresh the page

You should see the sidebar now.

I'll be making some improvements for the upcoming version 3.20, so there is also another way how to hide/show the sidebar.
