### ISSUE TITLE
Note scrolling not possible

### ISSUE THREAD

**Issue by skinnedpanda** [penge/my-notes#376]
Scrolling the list of notes not possible since the last update, only within the notes themselves, and in the note search modal (Ctrl-P).

**Comment by penge** [comment]
Thank you for reporting. I will release a fix in a bit. I see Sidebar scrolling is a problem (it's not there). Not experiencing the same problem in Ctrl-P modal. Mmm... But I see other problem, which is the order of notes in Ctrl-P modal – it does not follow the same order as in the Sidebar. I will fix that as well.
