### ISSUE TITLE
Google Drive Auto Sync is grayed out 

### ISSUE THREAD

**Issue by DevlinTech** [penge/my-notes#385]
Good day,
Please could you assist me with the steps on how I can setup the Google Drive Auto Sync feature?

![image](https://user-images.githubusercontent.com/105951928/177332269-fdd4a64e-c83c-4908-8ba8-e6dd7967fba1.png)

**Comment by penge** [comment]
Hi,
is this problem happening on the version installed from Web Store, or is it a manually installed version (downloaded zip)?
Which browser are you using? Any useful messages in the browser's console?

**Comment by penge** [comment]
Hi Dev,
could you try to check out Chrome's console if any message pops out when you try to enable Google Drive Sync?
Here's how to open Chrome's console:
https://balsamiq.com/support/faqs/browserconsole/#google-chrome

**Comment by DevlinTech** [comment]
Hi Pavel,
Hope you’re well.

Yeah, sure. I’ll try these steps and revert back to you. Thanks bud!

**Comment by DevlinTech** [comment]
Hi Pavel,

As you can see from the screenshot below, I have followed the steps you've
recommended, but it does not display any message at all in Chrome's console.

[image: image.png]
