### ISSUE TITLE
[Feature Request] Check list option for formatting

### ISSUE THREAD

**Issue by onlytanmoy** [penge/my-notes#386]
Hiya, first things first, really useful Chrome extension, thanks for that.
You have covered all most all formatting types baring the check list, please can that be included? see example below
You can either fade out or strikethrough once a task is checked-off.

![image](https://user-images.githubusercontent.com/48493659/178287771-395182ca-e069-4a24-84ec-8cea57441d34.png)

**Comment by penge** [comment]
Hi Troy,
this is doable using bulleted (or numbered list) which also has indent (to make nested todos), having just text and ~strikethrough~ (when done).
But it's not exactly checkbox so I understand.

Here's a quick preview how this could look. Thing is, checkbox and label have to work together, as one, so it can get tricky to have that easily editable (so it does not disappear when label is empty).

Preview:
<img width="539" alt="todo-preview" src="https://user-images.githubusercontent.com/907255/178316597-0b4be11c-8e16-4283-bb39-72823ff69b7e.png">

**Comment by onlytanmoy** [comment]
Thanks for your response mate, yes that preview looks all good to me, can that be implemented please?

**Comment by onlytanmoy** [comment]
Thanks a lot, I am glad I stumbled upon this extension of yours, it makes it so easy for my brain dump 👍

**Comment by penge** [comment]
The problem with having a checkbox + text, is deleting the text, after which the checkbox is removed as well (and we don't want that). This is the behaviour of https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable that My Notes relies on.

Closing for now, as there's no quick solution for that. A simple list with ~Strikethrough~ (Strikethrough) should be good enough.
