### ISSUE TITLE
[Feature Request] Save URL to specified note

### ISSUE THREAD

**Issue by onlytanmoy** [penge/my-notes#388]
Hi mate, I love the Save URL to clipboard feature you have provided, so very thoughtful 👌
I was wondering if you can please extend that nifty feature a bit by giving the user the _option to save the URL to a specified note_ something like what you have already implemented for saving the highlighted text.
That way, I can have separate files for Reddit, YouTube, Amazon etc. and send the relevant URLs to the appropriate folder.

**Comment by penge** [comment]
Sure, this update sounds great. (and I think there's not really a reason to limit that to only \@clipboard as of now)
I'll add it to the next version! :)
