### ISSUE TITLE
[Feature Request] Search box for all my notes

### ISSUE THREAD

**Issue by onlytanmoy** [penge/my-notes#389]
Hi mate, hope you are doing well.
Please provide a search box on the top to search through the content of all my notes
![image](https://user-images.githubusercontent.com/48493659/179176584-a6a6f9be-9ab0-4533-98d9-6eda08a1d81b.png)

**Comment by penge** [comment]
Hi,
we could have that Search input. Any ideas what we would do with the [Command palette](https://github.com/penge/my-notes#command-palette) then? (as it does overlap with this functionality) Should Command palette be limited to just commands?

**Comment by onlytanmoy** [comment]
Yes please, let the command palette be still there to issue commands. Having that Search input box on the UI will be really convenient to search the content of all my notes. Hope it's not too much of a work? If so, then I will use the existing command palette to find notes by content.

**Comment by penge** [comment]
@onlytanmoy Would it be ok if search results is just a list of filtered notes? (similar to results in Command palette)
I would then make Command palette about commands only. And make one improvement about the Search input so it searches notes by name <ins>**and also**</ins> by content at once (no need to differenciate between name or content searching as it's now in Command palette). How sounds that?
I am now quite available so improved Context menu (save URL to any note) will be released today (now testing). And this Search box could be released in 2-3 days.

**Comment by onlytanmoy** [comment]
> And make one improvement about the Search input so it searches notes by name and also by content at once (no need to differenciate between name or content searching as it's now in Command palette). How sounds that?

Sounds absolutely brilliant mate, it will be just perfect, thanks a lot.

**Comment by penge** [comment]
@onlytanmoy Just to let you know. Context menu improvement to save image is about to be released now, as 3.24.
Search box will be released very soon after, as 3.25.

**Comment by onlytanmoy** [comment]
Glad to know that mate.
I just tested the save image feature in v3.24, working great 👌thank you!
QQ- will it be possible to have a sort of version history for the note so that we can view the edits made and restore it if needed? Something like this https://help.zoho.com/portal/en/kb/writer/user-guide/reviewing-revising/working-with-document-revisions/articles/working-with-document-revisions#View_changes_since_your_last_visit

**Comment by penge** [comment]
Great to hear that!
Regarding history, it's easiest to have that managed by **_Google Drive_**, if enabled, where file revisions are automatic. Which is great. What might not be best on the other hand: periodicity of the backups, cumbersome to revert the file and sync it back to My Notes.
If above is not great, we could have custom implementation of revisions. But in the end, even in that case, it could be better to have them stored Google Drive.
Definitely something to discuss.

**Comment by onlytanmoy** [comment]
Ah, wasn't aware of the automatic revisions of Google Drive but yes agree with you that custom implementation of revisions will be good and yet store in Google Drive. But seems this will be a difficult task so you can very well ignore my request of version history thingy 🙂

**Comment by penge** [comment]
Hi @onlytanmoy,
working on the Search input but not very sure about it (see screenshot at the end). Reasons:
- searched term does not convey if the search results are about note **name**, **content**, **or both** (underlying matching parts of the note name can be done, but it does't solve the other cases)
- searched term does not highlight in the open note (Chrome's search would need to be used again)
- Chrome's search could be used to search notes by name, or, **only** current note's content

So I'd like to ask, what are we trying to solve here, because maybe we can come up with a better solution. Examples: seeing all notes at once as tiles, and using Chrome's search to search it; labels and filtering notes by a specific label; something else. Any ideas?

Screenshot:

<img width="193" alt="search_input" src="https://user-images.githubusercontent.com/907255/182609184-9d568479-233c-42a8-bc49-23256225d4b9.png">

**Comment by onlytanmoy** [comment]
Yeah, I get you, we would still need to rely on Chrome's search functionality to highlight the item in the current note. And you already have Ctrl+P to launch the search box and perform some of the actions.

Looking at your screenshot I was thinking we can keep that Search bar at the very top (bypassing the need to launch it via Ctrl+P) and then perform the below allowed operations:

1. Find note(s) by their name, and open one. (default behavior)
2. Find note(s) by their content, and open one. (type ? first, then continue)
3. Find commands, and execute one. (type > first, then continue)

**Comment by penge** [comment]
I'd say utilizing Chrome's search could be best as it offers all we'd like to see: highlighted searches, search count, and easy navigation between the searches.
To get there, we can try to present data in a good searchable way first, like tiles. I'll provide some screens soon so we can have a look at it.
Command palette should continue be located above the content as it's where it operates now. Sidebar is too narrow for it too. Maybe I could display the Command palette at the cursor position so it doesn't overlay the place where it will be inserted, or in other ways simplify it. In the end the Command palette should allow to do everything without a mouse, that is text formatting, opening a note, creating a new note, etc. I think that could be nice and help accessibility. I'll provide some screenshots about the search soon.

**Comment by penge** [comment]
Hi [onlytanmoy](https://github.com/onlytanmoy),
sorry I haven't been here sooner, but I am finally having the first screenshot on this feature I'd like to share.

**Screenshot:**

![overview](https://user-images.githubusercontent.com/907255/186786974-fc4e0d3f-7f6c-4705-b455-25df6ad89e34.png)

We can call this page <ins>**Overview**</ins>. It would have its own URL (so it can be bookmarked), like `notes.html?overview`.

The number of **columns** would be based on the window size (column would have a minimum width). **Rows** would have a fixed height.

Tried to figure out if we could have Overview _NOT_ a separate page, but haven't found a good solution there.

Any thoughts?

**Comment by onlytanmoy** [comment]
The overview page looks great mate.
I think we should keep this as a separate page, it gives a dashboard view so optional for people to use it.
Like how you can strike-off items in ToDo once actioned, also the search looking great 👍

**Comment by onlytanmoy** [comment]
Yes, that makes sense, lets call the button 'Overview' instead of 'Open Overview', just so the button remains small in size :)

Regarding the ToDo, how do you mark them as striked out? I thought it we have check box instead of bullet points then clicking the check-box will strike-off the item.

**Comment by penge** [comment]
@onlytanmoy
I used Strikethrough which is in the Toolbar, there's also a shortcut for that, see Options.

Will call it just "Overview".

**Comment by onlytanmoy** [comment]
Got it, thanks mate.
I was thinking can we have check boxes instead of bullet points for the ToDo section as that feels more relevant, your thoughts?
If its too much work to switch to check boxes then happy with bullet points.
