### ISSUE TITLE
Indent & outdent using keyboard for lists

### ISSUE THREAD

**Issue by pronojitsaha** [penge/my-notes#398]
Right now indenting & outdenting requires to click a button. It should possible through keyboard like Tab & Shift+Tab option in general.

**Comment by penge** [comment]
@pronojitsaha 
Thank you for your suggestion. I think we could have in-place-of-cursor (**single-line**) indenting & outdenting using Tab quite easily. Multi-line might be tricky. Is single-line good enough?

**Comment by pronojitsaha** [comment]
Yes single line works, thanks!

Also typing 1. or - should automatically start a bulleted list. This is a very time saving action.

**Comment by penge** [comment]
Great! I will look into adding this feature next. (will post some results here soon)

**Comment by penge** [comment]
@pronojitsaha Sorry for later response.
Here's a preview of this new feature. Managed to add both single-line and multi-line indent and outdent using Tab and Shift+Tab.

https://user-images.githubusercontent.com/907255/195985546-bfce0b65-4ae8-4c60-9903-3495771c33fa.mov

This feature is planned to be released on Monday.
_Note 1:_ Indent level is not limited. Outdent will stop when you reach the top-level.
_Note 2:_ For single-line indent, text doesn't have to be selected to use this function.
_Note 3:_ For this feature to work, you would need to enable "Indent text on Tab" in the Options, as the default Tab function is to focus the address bar.

**Comment by pronojitsaha** [comment]
Great, thanks! This would be really helpful.

Would typing "1. " automatically create a bulleted list?

**Comment by penge** [comment]
> Would typing "1. " automatically create a bulleted list?

Unfortunately not at the moment. But you could use these shortcuts for it:

```
Bulleted List (⌘ + Shift + 7)
Bulleted List (Ctrl + Shift + 7)

Numbered List (⌘ + Shift + 8)
Numbered List (Ctrl + Shift + 8)
```

**Comment by pronojitsaha** [comment]
Ok, thanks for sharing.


That will be a really good feature to have as well. Saves lot of time, as
in note-taking your are mostly thinking in bullet points.
