### ISSUE TITLE
Its hiding the the bookmarks

### ISSUE THREAD

**Issue by navi-dev** [penge/my-notes#4]

**Comment by penge** [comment]
Can you please tell me more about this?
I am using My Notes myself, but Bookmarks bar is still there.

Bookmarks can be shown/hidden by a keyboard shortcut, or manually. But they do not interfere.

Can you possibly send me a picture of what happened?

**Comment by navi-dev** [comment]
Below is the image, in upper part the extension is disable and its showing the bookmark bar but in lower image when I enable the extension its not showing up the bookmark bar.

![image](https://user-images.githubusercontent.com/31265301/69037713-5e87cf00-0a0e-11ea-841d-9503353fa9d8.png)

**Comment by penge** [comment]
I think I have found the answer. In the old days, the Bookmarks bar is visible.

Once I visit the page I need, Bookmarks bar is not necessary so it hides.

Now it works differently. Please check out this thread:
https://superuser.com/questions/1471502/how-to-show-bookmark-bar-only-on-new-tab

I am sending you a picture that I am not experiencing this problem.

![picture](https://i.ibb.co/SwznWS6/bookmarks.png)


Can you maybe update your Chrome to the latest version if that helps?

**Comment by navi-dev** [comment]
Ohh okay, For some reason I need the older version of chrome. We can close the ticket if its working for you in latest version.

**Comment by penge** [comment]
My Chrome version is 78 at the moment.
I hope using that coud solve it.
