### ISSUE TITLE
Feature Request: Add sort order for created at

### ISSUE THREAD

**Issue by dagumak** [penge/my-notes#401]
Current sort order says "Newest first", but it's actually the order for last updated. This becomes an issue when I want my note entries in chronological order. If I need to fix a typo in an old entry then it gets resorted to the top which is unexpected since it's not the newest note. 

Ideally, it would be nice to have a sort order for creation date and last updated date (ex, created_at, updated_at)

**Comment by penge** [comment]
Hi @dagumak

I understand. The hardest part will be to name the options well. Let's fix this.

So, now we have:

<img width="684" alt="order-1" src="https://user-images.githubusercontent.com/907255/196372341-d7b04750-600d-4be8-b1a1-24b8745fe76a.png">

Here's what it could look like (Let's call it Suggestion 1):

<img width="684" alt="order-2" src="https://user-images.githubusercontent.com/907255/196372391-daacbd91-087c-4eb9-9325-8b6926ed7d76.png">

Here's what these options mean:

```
Name          =>  Name asc
Created time  =>  Created at desc
Updated time  =>  Updated at desc
Custom
```

And here's what it would look like if we use the more descriptive options (Suggestion 2):

<img width="684" alt="order-3" src="https://user-images.githubusercontent.com/907255/196378641-bbd54660-69e7-46c5-beab-14f066de2320.png">

What would you prefer? Suggestions?

**Comment by dagumak** [comment]
In terms of descriptive naming, I would suggest the following:

```
Name          =>  Name
Created time  =>  Date Created
Updated time  =>  Date Modified
Custom
```

As for ASC and DESC, I think that should be a separate dropdown.

**Comment by penge** [comment]
I curated the options because I didn't find following to be much of use (**[1]**):

- name desc
- latest created at the bottom
- latest modified at the bottom

In other words, I found useful to have:

- name **_always_** asc
- created **_always_** latest first
- modified **_always_** latest first

There was no need for asc/desc options basically. Maybe I am wrong and these options are needed. Would you use some of the options from **[1]**?

**Comment by dagumak** [comment]
> I curated the options because I didn't find following to be much of use (**[1]**):
> 
> * name desc
> * latest created at the bottom
> * latest modified at the bottom
> 
> In other words, I found useful to have:
> 
> * name **_always_** asc
> * created **_always_** latest first
> * modified **_always_** latest first
> 
> There was no need for asc/desc options basically. Maybe I am wrong and these options are needed. Would you use some of the options from **[1]**?

I hear you. When it comes to productivity software, it always boils down to individual user preferences. I agree that latest makes more sense for most cases, but there are always reasons for it to be otherwise.

Here is a suggestion if you want the ascending order curated:

```
Name          =>  Name
Created time  =>  Recently Created
Updated time  =>  Recently Modified # or "Updated"
Custom
```

**Comment by penge** [comment]
Maybe even this simplified version would work:

<img width="684" alt="order-4" src="https://user-images.githubusercontent.com/907255/196418489-f6d44f06-d0ac-4c90-a460-191735622c30.png">

**Comment by dagumak** [comment]
> Maybe even this simplified version would work:
> 
> <img alt="order-4" width="684" src="https://user-images.githubusercontent.com/907255/196418489-f6d44f06-d0ac-4c90-a460-191735622c30.png">

It would work, but it wouldn't indicate the ascending order like you wanted.

**Comment by penge** [comment]
How about this version?

<img width="684" alt="order-5" src="https://user-images.githubusercontent.com/907255/196477439-99e7081f-9bc4-404a-83f5-4ed03264dae6.png">

**Comment by dagumak** [comment]
> How about this version?
> 
> <img alt="order-5" width="684" src="https://user-images.githubusercontent.com/907255/196477439-99e7081f-9bc4-404a-83f5-4ed03264dae6.png">

You can use "Latest Created" or "Created first", but it's a bit redundant to use both in the same sentence. If I read it as: `Order by ___` then I think my previous suggestions read better. Ex, `Order by Recently Created`

**Comment by penge** [comment]
What would you use with `Current order ___`? I tried to match that with `Current font ___` which is at the top.

**Comment by penge** [comment]
Hi @dagumak,

just to let you know, this feature is about to be released today. I've opted for "Latest Created" as you suggested, and renamed modified option to "Latest Modified". Thank you the suggestions! _Note: English is not my first language so I bit struggle here between: Order/Sort, Order by, Current order, etc, but I believe, if needed, this can be revisited in future. As of now, this feature is ready to be released and labels are simple w/o redundancy._

**Comment by dagumak** [comment]
> Hi @dagumak,
> 
> just to let you know, this feature is about to be released today. I've opted for "Latest Created" as you suggested, and renamed modified option to "Latest Modified". Thank you the suggestions! _Note: English is not my first language so I bit struggle here between: Order/Sort, Order by, Current order, etc, but I believe, if needed, this can be revisited in future. As of now, this feature is ready to be released and labels are simple w/o redundancy._

@penge Sorry, I missed the last message and didn't respond! Thank you for implementing this, and no problems on the English back and forth.
