### ISSUE TITLE
It would be a good idea to preserve stored notes over the next update

### ISSUE THREAD

**Issue by FirebrandCoding** [penge/my-notes#41]
I don't know whether it was possible to port the existing notes into the new version of the extension. Seeing how they're essentially the same item in the extensions menu, using the same Chromium API, I think that might have been possible.

Now that I've lost my notes, I think it's a good idea to remind you – as well as any developer reading – that *retaining saved data over version bumps is really fucking important*. Pardon the swearing: it's important to me that the weight of the matter gets across accurately.

At the very least, consider letting the users know that their data may be lost in transition, so that at least there's a chance to copy it to an intermediary text file.

(I'm naturally assuming you had tested the data retention behavior before releasing the the new version *extensively*.)

**Comment by penge** [comment]
I am very sorry to hear that @FirebrandCoding.

What you can try to do, is to open **Console** inside _My Notes tab_ and enter:

```js
chrome.storage.sync.get(["value"], sync => console.log(sync.value));

// This might show the notes from version 1.4 but I cannot guarantee that.
```

Picture:

![Screenshot 2019-12-26 at 12 19 36 AM](https://user-images.githubusercontent.com/907255/71449056-44ad7a80-2778-11ea-9748-583dc19ab11b.png)

<br>

I am using My Notes differently – **temporary data only.** Therefore no migration was incorporated and resetting notes never bothered me. But don't take this as an excuse. I now see your (and others) use case(s) might be very different from mine.

I hoped that **2.x** will help to deliver the message about **breaking changes** from **1.x.**

**I'll try to implement the migration now.**

<br>

**Migration is not that easy to test or guarantee though.**
If the extension is uninstalled and then installed again, the content of the storage is non-recoverable. The only way to go around it is to store the notes on an own server, which is something I won't do.
From the store, just the latest version can be installed, which makes testing limited.

<br>

---

_I understand that losing your notes could make you angry. And I am again sorry for that. But please, understand this. I have shared this extension to help others, to have normal discussions on improvements. So please, be more considerate about the tone you choose next time, as this is the last time I tolerate it. I dislike lecturing like this or making a public example. That is not the way I would like the communication going here._

**Comment by FirebrandCoding** [comment]
You're right: I could've handled this better. My apologies.

Still, I stand by the message about the important of handling user data – not only as a user, but also as a developer of note-taking software of my own. Reliability is one of the few basic requirements you have for *any* piece of software. If I can't expect an extension to keep its end of the bargain for any reason other than the fool in the user seat or a cascade of failures of the platform itself, why should I?

In the meantime, I was able to recover my notes. I've done nothing on my end, so it must have been the work you put into data migration. Thank you for the effort.
