### ISSUE TITLE
Export all notes

### ISSUE THREAD

**Issue by penge** [penge/my-notes#47]
Add option to export notes.

Export – **Open**, **Closed**, or **All** Notes
Format – `.txt` or `.md`

If exporting more than 1 note, put them in `.zip`

**Comment by jrcasso** [comment]
I suspect that the people who use this burgeoning extension are the same people who are creating it: developers. I would find even greater value in this extension if I could export notes in markdown `.md` format, so that it plays nicely with other markdown note-taking applications I use elsewhere.

**Comment by penge** [comment]
Hi @jrcasso 
No problem. I can add export format – `.txt` or `.md`.
How would you address if you have a combination of notes in both formats?

**Export:**
- could be all at once
- could be for selected files (can be better as it covers the first scenario too)

Planning to add a new table where you could see all the notes. Checkboxes could be next to every note, to export selected, and one checkbox could be at the top, to select all to export.
