### ISSUE TITLE
Move page selection outside of the text field (Part 2)

### ISSUE THREAD

**Issue by penge** [penge/my-notes#50]
Originally created by @FirebrandCoding here https://github.com/penge/my-notes/issues/46

---

### Builds

- https://penge.imfast.io/my-notes/3/notes.html
- https://penge.imfast.io/my-notes/2/notes.html
- https://penge.imfast.io/my-notes/1/notes.html

### Branch
https://github.com/penge/my-notes/tree/next

---

This message will be updated on new builds.

**Comment by penge** [comment]
I have you say I still like 2.1 more.
No names (anonymous notes), no export (notes temporary).
It had much easier UI and temporary feel (and uses) to it.
This way it's becoming more and more a full blown editor which was never the main idea.
What is becoming trouble now and I overlooked, is the limit of storage sync.

**Comment by JeromeDeLeon** [comment]
Your call. It just to me I like the design (outline border) of version 1.
I also forgot about the opacity of "Delete` text. Better if you make it red? it's hard to see the text IMO.

**Comment by FirebrandCoding** [comment]
I still have something like 40 lines of notes stored in the new tab, because your extension is perfect for it. I already spend most of my time in the browser; having a notepad be within reach of the next tab is comfortable.

If you're aiming to change the persistence status, please notify beforehand: I want to be able to export them manually.

In my experience, if you don't like it, you shouldn't be doing it. You'll end up tired and angry, and that's never a good position to develop a popular extension from.

I was perfectly fine with a single page of notes, but you did have tabs, and I proposed a way to remove them from a place to be clicked by accident while trying to select text.

On design note, I liked it better when it was greyscale. Easier on the eye. Color does nothing for me.

If you're going to keep tabs, may I suggest reverting to boxes? Pills restrict clicking space to no positive effect. They look softer, and softer doesn't mean nicer.

**Comment by penge** [comment]
To be honest, I was perfectly fine with 1 page of notes too.
It was dead simple and ready to copy and paste. No export was needed.

3 pages was a valid request, maybe...
In example: page for copy/paste, page for todos, page for links.
But you know what? I had no problem organizing this in 1 page. Searching the text was simpler. And some text selection, instead of Ctrl + A, was not an issue for me. The obvious drawback is, notes are hidden under a page number that needs to be open first to see if something is there. This is not the case if having 1 page.

I knew if I just push the scrollbar up, so the text doesn't overlap the page number, it wouldn't look nice to me, because how the scrollbar would be rendered and how wasteful the footer would become. I also feel like adding Tabs, naming notes, that all just adds an unnecessary complexity. Trying to be something that it's not.
I believe My Notes should be about notes, open, edit, close, no more thinking about it.

One of the best features is chrome sync, which I don't use but some content creators do.
I think maintaining this feature is more important than pages, dark mode, tabs, or any other because it adds a significant value.

I know one of the hardest thing is to drop the work in progress but that's fine for me. I have a solid boilerplate that can be used in future. Not relying on hefty libraries like React or complex build process like 2.1 does - I consider that a feature too.

 This is what I would like to do instead:
- drop this work (can stay as a branch) and make 2.1 perfect instead
- go back to 1 page. I know some users might not like this, but it's chrome sync that makes it best (and having 1 page makes synchronization much easier and also stay within limits of chrome sync)
- if I would have to improve the codebase of 2.1 in some way, I would split files into smaller manageable chunks and use typescript instead (no Webpack or other complex build process)
- I would improve the synchronization across the devices by splitting notes into smaller chunks and put them together on other devices, make most of chrome sync this way.

**Comment by penge** [comment]
![local-synced](https://user-images.githubusercontent.com/907255/73133330-b91a5880-4059-11ea-96b4-a050add611ff.png)

**Comment by penge** [comment]
![grayscale](https://user-images.githubusercontent.com/907255/73135021-2f29ba00-4070-11ea-99a9-34bd62c1604f.png)

**Comment by penge** [comment]
![grayscale](https://user-images.githubusercontent.com/907255/73135181-e3781000-4071-11ea-91e1-3f21d998d8a4.png)

**Comment by JeromeDeLeon** [comment]
What is that `Local` and `Sync` tabs do?

**Comment by penge** [comment]
How about this?

![menu1](https://user-images.githubusercontent.com/907255/73137167-e7169180-4087-11ea-93d6-87f0fc3bb971.png)

![menu2](https://user-images.githubusercontent.com/907255/73137161-e1b94700-4087-11ea-98a3-ab88aa7d2b33.png)

<br>

**Menu:**
- **Options** - same as the extension Options (I believe not everyone might know there is such a thing someplace and it would anyway better if it's only right there)
- **Focus** - would enter the Focus mode, and display the tooltip how to come back
- **Help** - would explain what are Local and Synced and what limits apply, how to contact, where to ask questions

<br>

**To your question:**
Local notes are visible just in your computer.
Synced notes are visible in every computer where you are logged in with your Google account so you can copy/paste between your computers.

Local notes are stored in Chrome Storage Local, their limit is 5MB.
Synced notes are stored in Chrome Storage Sync, their limit is 100KB. Yes. 100KB! :D
Because of storage reasons and different use cases, they are separate.

If limit for Synced notes is reached, they still will be saved in your local computer just not send across.
This could be also explained in Help.

**Comment by JeromeDeLeon** [comment]
So if you want to transmit something over the other device, use `sync`, but if it is too large, move it piece by piece? 🤔 

I don't know for other users, for me, I just sent something to myself using Social Networking App like Messenger and opened it with my other device. I hardly do this though, because chrome already made it possible like sharing links.

Anyway, seems like you already decided and it's nice 😄 . Even the looks is simplified and seems very easy to navigate.

**Comment by penge** [comment]
^^ I like it btw and could be version 3

The feature list would be:
- Rewritten in React, build in Webpack (user don't see this)
- Menu
- Local and Synced are separate

Synced could be cropped into chunks because limit per item is 8KB :D  
I could do some basic hack in 3.0 💃 let's say:
1) crop synced notes into 5-6 KB chunks (a safe margin)
2) save chops and also save information how many chunks to put together on the other side
3) read N chunks
4) put them together
:d 
It will be based on UTF-8

^ Or, that could be in 3.1 :) so 3.0 can be faster

**Comment by penge** [comment]
^^^^^ Yeah. I could use Telegram or other chat app too.

But hear this. You open tab on one PC and CTRL C/V
and then open tab on second PC and oala, it's there :D 
it's highly addictive :D 

and if the tab is already open, in 1 sec you have it

**Comment by JeromeDeLeon** [comment]
Yeah, that's what I thought too, move the text chunk by chunk.

Do we really need framework for something as simple as this?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JeromeDeLeon** [comment]
>^^^^^ Yeah. I could use Telegram or other chat app too. ...

@penge Haha, let's see. I haven't encountered that kind of scenario 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by penge** [comment]
> Do we really need framework for

No we dont :D but I already did it :D

**Comment by penge** [comment]
This issue has gone offroad big time :D

I have some exciting news though

I will release 2.2 today or tomorrow
(React + other stuff was playground that won't be used)

Here's the screenshot:

![preview](https://user-images.githubusercontent.com/907255/73167238-141b8080-412a-11ea-875c-6952cdae78ec.png)

\* bigger than default font on purpose


Changes are:
- botton doesn't overlap
- there's Options link to open Options page in new tab 
- paddings are having relative measures, so it's a bit bigger on big font and smaller on small font, looks nice
- Focus mode can be turned by default (Options page), that means it's always in Focus (minimal UI, no bottom bar)
- in Options page you see the current font size as number, so it's no more guessing based on slider position
- Dark mode colors are improved (using #121212)


There's one more thing I'd like to solve. That is, if you hit Tab from address bar and jump into Textarea, its Tab won't be triggered (intends text).

**Comment by JeromeDeLeon** [comment]
what do you mean by `Tab won't be triggered`? what you want it to do?

**Comment by penge** [comment]
**scenario:**
Ctrl + N (new window) or Ctrl + T (new tab) to quickly open My Notes
search bar will be selected by default
you quickly hit **Tab** to focus the notes

**Now:** notes are focused, cursor is at the end, but also 2 spaces are inserted
**Expected:** notes are fucused, cursor is at the end, and that's it, no change in content

once notes are selected by this jump, Tab and Shift + Tab, will continue do its job (forward and backward intend)

solved it btw. feature list is now complete 😃🎉

**Comment by penge** [comment]
just one thing,
how do you feel if it would be configurable if My Notes replaces new tab?
a) replaces new tab by default
b) if turned off, you can click the icon in toolbar to open My Notes

do you think, if everytime you create New Tab to google something and my notes appear, it's a bit too much after time? or alright?

if it would be configurable, the benefit is well, can do a) and b) and choose which one prefer more
one more pro is, favicon could be displayed (not only if tab is pinned)
and one con - the url would be ugly :D

like this:
chrome-extension://ocnknjfnfjoldojpjmbchjmagiaoahmh/notes.html

**Comment by JeromeDeLeon** [comment]
URL doesn't matter in my case as long as the functionalities is there. If you could make it configurable, of course depends on your time. That would be great! You've been doing much more to this project :smile:

**Comment by FirebrandCoding** [comment]
It's an interesting proposition.

Ideally, you would a survey of how much of your extension's users feel so that you could accurately measure how valuable this feature is. Implementing it in a vacuum may sound fun, but in the end, user experience matters much more.

That said, it sounds like a neat feature. You'd some explanation about how it works: it's not a common mechanism. Beyond that, I see no reason not to implement it.

**Comment by penge** [comment]
I'll make it configurable :))

I just realized it would be great to have line numbers. Here's a picture:

![Screenshot 2020-01-28 at 8 50 42 PM](https://user-images.githubusercontent.com/907255/73270450-4653dd80-4211-11ea-8139-70cf2aef94db.png)

Ctrl + Shift + L (Option + L on Mac) can toggle line numbers, or they can be enabled by default (Settings page)

** those 2 features would be added to 2.2 and that's it 😃

**Comment by penge** [comment]
Guys, thank you very much for the great feedback on this.

I am now releasing 2.2 that should be live soon.

Changes are here: https://github.com/penge/my-notes/pull/51

<br>

Line numbers will be in 2.3. I had to address some important things first (saving notes to storage.local instead of storage.sync due to the limits).
While 2.3 will be on its way, cool Context Menu is added to 2.2.
