### ISSUE TITLE
"Focus" option is unclear

### ISSUE THREAD

**Issue by FirebrandCoding** [penge/my-notes#57]
I assumed, on seeing release notes, that what the "Focus by default" option does is focus the `<textarea>` element of the notes, making it easier to take notes when opening a new tab.

Instead what it does is engage focus mode.

It's an excellent option with an unclear title. Consider renaming it to "Focus mode on by default" so as to not confuse the user.

To new users, it may also be useful to explain what focus mode is. Consider adding a brief explanation of the different between default and focus mode under the category title or the checkbox itself in the options.

**Comment by penge** [comment]
Nice suggestion. I suggest to use "Focus mode" (checkbox).

Reasons would be:

- checkbox conveys on/off
- "Focus mode" would go nicely with "Toggle focus mode" (keyboard shortcut) which I would also rename to "Toggle Focus mode" so it's more alike and also consistent with "Light mode" and "Dark mode" (first uppercase, mode keyword)

In summary:
- **"Focus mode"** (checkbox)
- **"Toggle Focus mode"** (description for keyboard shortcut)

I can add following comment (could be also a tooltip to make the UI cleaner but I guess, visible comment will be better):

> Focus mode hides bottom panel that contains Options link and page number, to give you more editing space. You can change this option at any time by visiting Options through My Notes icon in the toolbar (right click), or using a keyboard shortcut.

Thanks for help on this btw. I will leave this open for few hours so we can decide what's the right wording. I'll also update README to cover Focus mode (or all the aspects of Options page, actually).

This will be part of a patch 2.3.1 (2.3 is now in review).

**Comment by penge** [comment]
This feature is getting its shape.

## Closed

![question](https://user-images.githubusercontent.com/907255/74440045-dba4d200-4e9f-11ea-8dc5-838d4e2c0c9d.png)

## Open

![question2](https://user-images.githubusercontent.com/907255/74440013-cf207980-4e9f-11ea-9830-11b371c8adcd.png)

## And a Dark version

![question3](https://user-images.githubusercontent.com/907255/74440253-40f8c300-4ea0-11ea-85dc-4c3dbd9cf086.png)

🙂

**Comment by FirebrandCoding** [comment]
Looking good.

Is there a reason for hiding the description text? Unless there is, it's better to leave the text visible at all times, rather than require two more clicks out of the user.

**Comment by penge** [comment]
Some reasons to consider would be:

- Checkboxes are near each other, that translates to less scrolling, faster change, less distraction

- In the overall composition of the page and the weight of detail I see across - when moving my focus to email, keyboard shortcuts, version, and other parts of the page and then back - always present descriptions seem disruptive (information overload, shifting white/black balance)

- Description is something I would get familiar with for the first time and most likely never read again (that's my view but I hope others would agree on this)

- Opening a description time to time seems fine and also a bit of "fun" - as an interaction

**Comment by FirebrandCoding** [comment]
> * Opening a description time to time seems fine and also a bit of "fun" - as an interaction

It isn't going to be considered fun. Interaction? Sure, but it won't bring users closer to your design. Interaction is only ever fun when it's something you actively want to achieve. Being able to click the checkboxes of the desired options is fun. Having to click another button to know what the hell the option is even for isn't fun.

Seems like you're making up reasons to leave things as is. Allow me to warn you that it would end up leaving you worse as a designer. This attitude leaves you vulnerable to your biases, and the design inevitably suffers as a result.

For what it's worth, every single piece on form design that I've read recommends that I leave the information visible at all times, whether it's usable once (like in a registration form) or a hundred times. It reduces friction considerably at no cost to either the user or the developer.

**Comment by penge** [comment]
No problem. I am open to feedback and definitely if something is biased (which I agree, happened) and causes a conflict, I am willing to change that.

It **would** be eventually better to see the description at all times. It supports the decision in the end.

Not saying that I am against changing it, although it might have looked that way. I like the change. Will add new screenshots later today.

**Comment by penge** [comment]
## Always visible

![description](https://user-images.githubusercontent.com/907255/74509922-33414d00-4f35-11ea-9596-8d4671134e24.png)

\* Replace New Tab will go away though
