### ISSUE TITLE
Allow user to focus the notes area by default as an option

### ISSUE THREAD

**Issue by FirebrandCoding** [penge/my-notes#58]
Related to #57: consider adding an option to focus the notes `<textarea>`. This should make taking notes slightly easier if it's something you do often in the browser. The [`HTMLElement.focus()` method](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/focus) should assist with that.

Also, add `Esc` keybind to escape `<textarea>` focus and re-focus the address bar. You can use the [`.blur()` method](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/blur) on [`document.activeElement`](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/activeElement) to achieve that.

**Comment by penge** [comment]
I tried that (would be a nice feature) a time ago, and I think it's not possible.

Reason would be:
Address bar is always focused (preselected) when a New Tab is open. This behavior cannot be changed.

I will try again. Maybe I overlooked something or it is actually possible. Worth a second try definitely.

**Comment by penge** [comment]
Update on this.

Looks like focus cannot be "stolen" from a New Tab that user creates by himself (keyboard shortcut, + button).

If a New Tab is created programmatically on the other hand (since version 2.3 it is 1 click on the icon), the focus **can be** changed and `<textarea>` therefore can be focused.

But, it is incosistent (one works, other not). For that reason I would drop this feature. I'll leave it open for a while.

**Comment by penge** [comment]
Update on this.

Looks like focus cannot be "stolen" from a New Tab that user creates by himself (keyboard shortcut, + button).

If a New Tab is created programmatically on the other hand (since version 2.3 it is 1 click on the icon), the focus **can be** changed and `<textarea>` therefore can be focused.

But, it is inconsistent (one works, other not). For that reason I would drop this feature. I'll leave it open for a while.

**Comment by FirebrandCoding** [comment]
Good research.

In this case, it's better to have no feature than an inconsistent one. Having two defaults to consider is cumbersome for both the user and the developer.

Seems the issue is moot. Feel free to close it. It might be worth revisiting if there's ever a revision in the Chrome policies.

**Comment by penge** [comment]
Cool

**Comment by penge** [comment]
## Hint

**Windows:**
`Ctrl + L` or `Alt + D` or `F6`

**Mac:**
`Cmd + I`

This keyboard shortcut can be used to **Move the cursor to the browser address bar and highlight everything in it.**

**Source:**
https://support.google.com/chrome/answer/157179?hl=en (see Address bar shortcuts)

<br>

## Focus the notes area by default

It is now possible as there is one way to open My Notes (1 click on the icon) which is programatic.

<br>

## Keyboard Shortcuts

I would mention shortcuts from the hint, and also `Tab` and `Shift + Tab`.

**Comment by penge** [comment]
## Hint

**Windows:**
`Ctrl + L` or `Alt + D` or `F6`

**Mac:**
`Cmd + I`

This keyboard shortcut can be used to **Move the cursor to the browser address bar and highlight everything in it.**

**Source:**
https://support.google.com/chrome/answer/157179?hl=en (see Address bar shortcuts)

<br>

## Focus the notes area by default

It is now possible as there is one way to open My Notes (1 click on the icon) which is programatic.

<br>

## Keyboard Shortcuts

I would mention keyboard shortcuts from the hint.

<br>

## Typing

I would add a new section Typing where I would also mention the role of `Tab` and `Shift + Tab`.

**Comment by penge** [comment]
No planning to implement. There is not enough interest in this feature.

If some others would like it, reach me out, I can add it but for me, I like the state where the open page is clean and I can decide what to do, where to click.

**Comment by penge** [comment]
I am reopening this as I found great use for it!

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/907255/82504632-287df180-9afc-11ea-9a8d-9dd1c011886c.gif)


At any point quickly open My Notes (`Cmd + Shift + M`), do the thing, Close (`Cmd + W`). Repeat.

(This will be in My Notes 3.1)

**Comment by penge** [comment]
**Update:**

<br>

![tab](https://user-images.githubusercontent.com/907255/82623443-7f5cf700-9be0-11ea-8860-92fe40b51056.gif)

**Comment by penge** [comment]
**Update 2:**

Improved. Very fast refreshes **now without carret flickering at the beginning** of note as that's carret's default position. Now no flicker.

Works like this:
- hide carret <--- this step added
- focus input
- move carret to the end
- display carret <--- this step added

**Comment by penge** [comment]
Related issue: https://github.com/penge/my-notes/issues/87
