### ISSUE TITLE
How about a Todo list?

### ISSUE THREAD

**Issue by penge** [penge/my-notes#59]
There has been a requirement in having a Todo list.

I am now evaluating how that could be done and if it's necessary.

<br>

How I manage a Todo list and might be efficient, is like this:

![todo](https://user-images.githubusercontent.com/907255/74494753-746f3800-4f08-11ea-9529-4c84c35880b3.png)

This gives me an option to write down a Todo list with additional notes (which I found to be a good combination) or write down **nested Todos** (a combined task).

![todo-nested](https://user-images.githubusercontent.com/907255/74495226-c06eac80-4f09-11ea-847b-b2b4cd1b34fb.png)

What do you think. Is a Todo list really necessary? Or is it already there?

**Comment by penge** [comment]
My take on this. I think a Todo list is not really necessary. There are already great apps for this like [**TickTick**](https://ticktick.com) or [**Microsoft To Do**](https://todo.microsoft.com) so let's not recreate that.

I also agree that having all at one place would be really great. I use to manage Todos in a text file or now in My Notes, basically in a text-form, for a long time.

PS: Nothing beats **paper** 😁

**Comment by bhupesh-sf** [comment]
Hey @penge Todo is very basic day to day thing which we do during our notes. May not be everything at one place but all basics at one place be realy helpful. I use Microsoft Todo but it again forces me go to 2 different apps. For elaborated todo management one can use such apps but for basic todo's should be part of my notes.

Thoughts?

**Comment by penge** [comment]
Hi @bhupesh-sf

I have some good news! A basic Todo organization will be possible in My Notes 3.

1. A custom name for the note can be set, like **Todo**

2. After selecting a text (todo item), a toolbar with commands would be displayed (toolbar would probably be hidden if nothing selected)

2. A <s>strikethrough</s> can be used to mark the done tasks
  If needed, tasks can be in an unordered/ordered list

## Screenshots

![todo](https://user-images.githubusercontent.com/907255/77406898-a1d7bd00-6db5-11ea-90c9-8d89e461f2ae.png)

![todo2](https://user-images.githubusercontent.com/907255/77406917-a7350780-6db5-11ea-9a44-c7895aef1150.png)

![todo3](https://user-images.githubusercontent.com/907255/77406934-abf9bb80-6db5-11ea-91b8-f5677b263b95.png)

More about new editing features will be here: https://github.com/penge/my-notes/issues/72

**Comment by bhupesh-sf** [comment]
@penge This will be awesome. Will wait for all these wonderful features.

**Comment by penge** [comment]
@bhupesh-sf Thank you. I'll be adding a new issue here when version 3 will be ready to undergo testing before the release.

So far it goes well and most of the things are done. The last two features is this - command toolbar, and Google Drive which is about 80% done.

**Comment by penge** [comment]
_Implemented - see https://github.com/penge/my-notes/issues/72. Closing. Proceeding to testing._
