### ISSUE TITLE
Rename notes, Create new notes, Delete notes

### ISSUE THREAD

**Issue by penge** [penge/my-notes#64]
<details>
  <summary><b>not to be used</b></summary>

<br>

### ~Tiles~

_Originally posted by @penge in https://github.com/penge/my-notes/issues/53#issuecomment-588147278_
</details>

**Comment by penge** [comment]
## Preview of Page switch and Page rename

![todos](https://user-images.githubusercontent.com/907255/74794305-6b5ddc80-52f5-11ea-850d-7fec8300b094.png)

- click on current page displays pages to choose from in bottom right, click on current page again closes the list
- current page is underlined
- click on page in the list opens the page
- double click on current page or page in the list allows you to rename the page

**Edit:**

On the very left of each page, there could be the X button to delete the page.

When X is clicked, confirmation message would be displayed: Delete Todos? Yes, No.

To add a new page there could be silver color "New page" above all pages. If you click or double click that, you would have a new page created that you are just renaming. If you would like to have it name "New page" just by coincidence, you can.

_Originally posted by @penge in https://github.com/penge/my-notes/issues/53#issuecomment-587573023_

**Comment by jmaicaaan** [comment]
> ## Tiles
> ![tiles](https://user-images.githubusercontent.com/907255/74825389-6b34ff80-533c-11ea-82d4-50c4a4db7c11.png)
> 
> 
> 
> _Originally posted by @penge in [#53 (comment)](https://github.com/penge/my-notes/issues/53#issuecomment-588147278)_

That's great to see!! 🔥 what do you think on making the font size a little smaller?

**Comment by penge** [comment]
> That's great to see!! 🔥 what do you think on making the font size a little smaller? Or is it just looks big?

Font size is actually as in Options. Scales down or up.

I use **cow** 😃 font to see less and edge cases but all is good on smaller font 😉👍

**Comment by jmaicaaan** [comment]
Sounds good! Looking forward man🔥

**Comment by penge** [comment]
I've been looking at those **Tiles** and the things I don't like would be:

- it is wasteful in space  
- might need to scroll
- slow to change a page

<br>

Going back to idea of having **Tabs:**

![Screenshot 2020-02-20 at 8 53 23 AM](https://user-images.githubusercontent.com/907255/74893275-9102e880-53be-11ea-8b6f-062622d80f90.png)

And here is how it would work:

**Tab:**

- single click => Open

- double click => Rename

- right click => opens context menu with Close and Delete
_If you click on Delete, it is replaced with Confirm delete, need to click that again, then it is deleted._

<br>

**+ button:**

- single click => Add page to the end

- right click => opens context menu to Open one of existing closed pages

**Comment by penge** [comment]
![Screenshot 2020-02-20 at 11 30 42 AM](https://user-images.githubusercontent.com/907255/74901141-818e9a00-53d4-11ea-9d70-20eda5aa814c.png)

**Comment by jmaicaaan** [comment]
I think you're right about those wasteful space for the tiles. Just minor style for the tabs. I think a separator or border would be ideal to indicate a separation between tabs as I click it. Other than that, this one still looks good! 👌

**Comment by penge** [comment]
This will change many times probably 😂

Here's one more:

![preview](https://user-images.githubusercontent.com/907255/74963448-504db280-5444-11ea-92af-9ea0125d10ea.png)

**Comment by penge** [comment]
May change many times. Visual prototype at the moment.

![Screenshot 2020-02-21 at 12 55 02 AM](https://user-images.githubusercontent.com/907255/74963827-f6012180-5444-11ea-9b0b-23d48619a742.png)

**Comment by jmaicaaan** [comment]
Not sure if I posted somewhere my comment last night but yeah it's missing 😓 anyways, I like the tabs too! Good job! 🔥 I think you're right regarding the tiles of having a lot of waste spaces. In regards to tabs, what do you think about having a separator or border between each item? I think that's really helpful on long  titles or something.

**Comment by jmaicaaan** [comment]
Oh it's already there. Lol my page didn't even get the latest updates! 😄

**Comment by jmaicaaan** [comment]
I love the grayish background color on the selected article instead of the black & white especially on non-dark mode 😄

**Comment by penge** [comment]
![Screenshot 2020-02-21 at 9 26 15 AM](https://user-images.githubusercontent.com/907255/74998802-48b1fc00-548c-11ea-914f-3870cec47038.png)

I will add this to the branch today, something visual as I am now at point where notes are having names and they are migrated from 2.x to 3.x.

I let you know when it's in the branch, you can try something out 😃👍

**Comment by penge** [comment]
2.3.1 still not published which is totally fucked, never took so long, it's been 7 days as Thursday is over in Cal, if not tomorrow, then no Saturday Sunday again, maybe no Monday, maybe together 11-12 days alltogether and I start thinking if this is not an intension... Sometimes it took 5 minutes, when I was publishing 1.x versions. I believe there is some bot for this, definitelly not done manually.
I need to publish 2.3.2 fast but 2.3.1 still not published. I guess it can be taking forever.

**Comment by jmaicaaan** [comment]
Yeah sounds good to me! The delay from Google seems unreasonable to me as well. But yeah, that's something we don't have control. I think this coming weekends I can check it locally :)

**Comment by penge** [comment]
Here are some updates.
<br>

## Renaming a tab

![Screenshot 2020-02-22 at 12 41 45 AM](https://user-images.githubusercontent.com/907255/75058343-6b382980-550d-11ea-99cc-3c4147cfb8e5.png)

![Screenshot 2020-02-22 at 12 42 10 AM](https://user-images.githubusercontent.com/907255/75058418-8efb6f80-550d-11ea-838a-e619ca4646e4.png)

![Screenshot 2020-02-22 at 12 41 55 AM](https://user-images.githubusercontent.com/907255/75058440-96227d80-550d-11ea-9ff2-0bd47e5fbcf0.png)


## Dark theme

![Screenshot 2020-02-22 at 12 49 39 AM](https://user-images.githubusercontent.com/907255/75058328-64a9b200-550d-11ea-9686-c6fead967459.png)

<br><br>

**Renaming**
To rename a Tab, simply double click on it (it doesn't have to be selected first).
Type a new name, hit Enter or click outside the tab.
Name cannot be set empty, in that case it would be set back (unchanged).

<br>

**In progress**
- Opening a note
- Creating a new note
- Closing a note
- Deleting a note

**Comment by penge** [comment]
I have changed the title to **"Rename notes, Create new notes, Delete notes"** as _what_ needs to be done comes before _how_.

**~Tabs~, ~Tiles~**
I tried to fit-in **Tabs** or **Tiles** before but I found both of them not to be a good solution, and just because it exists somewhere else or works well, it doesn't necessarily mean it should be force-used.

I have decided to use something else. I will post screenshots shortly.

**Comment by penge** [comment]
There are 2 different pages – **Current note**, **All notes**

<br>

### A) Current note

Current note looks like a chapter in a book.

![todo](https://user-images.githubusercontent.com/907255/76322591-e0fd0d00-62e3-11ea-9d6c-3fc805754caa.png)

**Possible actions:**

- **Todo** (any current title)

  - **LEFT CLICK** to open a different note (goes to page **All notes**)

  - **RIGHT CLICK** to rename the note

<br><br><br>

### B) All notes

![notes](https://user-images.githubusercontent.com/907255/76315184-7db9ad80-62d8-11ea-8c55-f30f01c07300.png)

**Possible actions:**

- Notes

  - **LEFT CLICK** to open the note (goes to page **Current note**)

  - **RIGHT CLICK** to rename the note

- (+) button

  - **LEFT CLICK** to create a new note

<br><br>

**On fresh install:**

![fresh](https://user-images.githubusercontent.com/907255/76315309-bbb6d180-62d8-11ea-8f9f-dbab470e959e.png)

---

<br>

### Mouse actions

- **LEFT CLICK** = open
- **RIGHT CLICK** = rename

<br>

### Deleting a note

Note is _safe to delete_ when the content and name are empty.
To delete a note, remove the content and change the name to **empty**. If there are some whitespaces left here and there, it's ok, it will be deleted.

### Clipboard

Clipboard is a special note that can be edited, but cannot be renamed nor deleted. Its purpose is to receive the text from My Notes Context menu.

<br>

### QA

**Q:** Can two notes have the same name?
**A:** No. Note name needs to be unique. If you try to change the name to an existing one, it will be changed back.

**Q:** Can I edit two different notes in two different tabs at the same time?
**A:** Yes.

**Q:** How to rename a note?
**A:** Right-click on the note, type in a new name. Confirm the name by either Enter or click anywhere else.

**Q:** How to delete a note?
**A:** Remove the note text and change the name to empty.

**Comment by penge** [comment]
Notes are displayed as **tiles**, similar to those in Google Docs. Tiles display the **preview** of the content. There are three dots to the side, to **Rename** or **Delete** the note. The only exception is **"Clipboard"** which cannot be renamed or deleted, as it is used by **"Save selection"** and **"Save selection to other devices"** context menus.

At the bottom, there are two buttons:
- **New Note**, to create a new note
- **Options**, to open Options in a new tab

Tiles **scale up and down** based on the available width.

See the tiles below.

## A) Plenty of space

![image](https://user-images.githubusercontent.com/907255/80309612-71c97280-87d6-11ea-9745-c2082ce04cdb.png)

## B) A little less space

![image](https://user-images.githubusercontent.com/907255/80309609-6f671880-87d6-11ea-8acc-3deb6e2fef50.png)

## C) Not much space

![image](https://user-images.githubusercontent.com/907255/80309603-6aa26480-87d6-11ea-819a-86c297e7148f.png)

At any point, you can change the font size in **Options**. If you need to change the size only temporarily, you can press the keyboard shorcuts for **Zoom In** / **Zoom Out**, or associated buttons in the browser.

**Comment by penge** [comment]
Here's a preview of the note detail.

## Note detail

![image](https://user-images.githubusercontent.com/907255/80310419-f4543100-87da-11ea-99bb-821eabe345e7.png)

<br>

At the top right, there are three dots (same as in **Tiles**, same function) to **Rename** or **Delete** the note.

Clicking three dots will open:

![image](https://user-images.githubusercontent.com/907255/80310466-31b8be80-87db-11ea-817b-de276734ae6c.png)

**Comment by penge** [comment]
Renaming and Deleting the note. Both can be done in either **Tiles** (notes list) or in **Note detail**.

After you click the **three dots**, you see:

![image](https://user-images.githubusercontent.com/907255/80310562-af7cca00-87db-11ea-84ec-1322a0f5f7ba.png)

Let's say you'd like to rename _Vacation_ to _Holiday_.

<br>

## Rename / Delete

![image](https://user-images.githubusercontent.com/907255/80310530-7fcdc200-87db-11ea-8d55-c1fef591c208.png)

<br>

![image](https://user-images.githubusercontent.com/907255/80310542-89efc080-87db-11ea-9e78-745bb1c46739.png)

<br>

## Rename / Delete

![image](https://user-images.githubusercontent.com/907255/80310603-e94dd080-87db-11ea-8b97-b437ded6e808.png)

<br>

![image](https://user-images.githubusercontent.com/907255/80310607-ece15780-87db-11ea-83b0-59b995653149.png)

**Comment by penge** [comment]
@jmaicaaan My Notes 3 have now the tiles as in Google Docs.

Now testing. Soon will open a new issue to join the testing.

**Comment by penge** [comment]
_Closing. Proceeding with testing._
