### ISSUE TITLE
Support for Markdown

### ISSUE THREAD

**Issue by bhupesh-sf** [penge/my-notes#71]
Its an awesome extension, helping me a lot in day to day life. More wonderful features are also coming.

Was just wondering if there is any plan to add support for using Markdown, it will help me to have checklists, headings, sections, tables in a single place to manage my notes better. For e.g. I keep the sprint plan always handy in my notes tab (along with many other day to day notes or other important items for the project) and if I have the option to use markdown I will be able to manage them better.

**Comment by penge** [comment]
Glad to hear that! Thank you!

I am considering _Markdown_ support. I'll look at it after the release of **My Notes 3**.

Depending on how the things would go, I would decide if and when, and how, this could be implemented. A good inspiration on how this could work is **Typora** (**https://typora.io/**), which is great.

**Comment by penge** [comment]
@bhupesh-sf Support for Markdown could be in future, for now, basic styling would be as HTML behind.

More about future styling here: https://github.com/penge/my-notes/issues/72

**Comment by bhupesh-sf** [comment]
@penge Does this mean we are not going to have it ever or add required things manually rather then full mark down support? I am good with either.

**Comment by penge** [comment]
@bhupesh-sf Hi, markdown support is not planned. What do you mean with add things manually?
