### ISSUE TITLE
Improve notes editor (bold, italic, underline, headings)

### ISSUE THREAD

**Issue by penge** [penge/my-notes#72]
My Notes 1 and 2 are using `<textarea>` to write down the notes in plain text. This doesn't allow to use styles to organize the content visually better. Here's how it can be improved.

## Required features

- Headings (h1, h2, h3)
- **bold**
- _italic_
- underline
- and possibly more

## Options

This can be done either by creating something, or using existing solution. Creating something seems better as feature list is not huge and creating something is quite simple.

Here are some options for the reference and also inspiration.

Known **WYSIWYG** editors are:

- [Slate](https://www.slatejs.org)
- [Draft.js](https://draftjs.org)
- [ProseMirror](https://prosemirror.net)
- [Quill](https://quilljs.com)
- [CKEditor](https://ckeditor.com)
- [TinyMCE](https://www.tiny.cloud/)
- [Editor.js](https://codex.so/editor)
- More at https://github.com/JefMari/awesome-wysiwyg

**Quill** looks nice, but seems not maintained:

- https://medium.com/@jhchen/the-state-of-quill-and-2-0-fb38db7a59b9 _(Sep 2017)_
- https://github.com/quilljs/quill/issues/2435 _(Roadmap)_
- https://github.com/quilljs/quill/graphs/commit-activity
- https://github.com/quilljs/quill/releases

Known **Code editors** are:

- [Ace](https://ace.c9.io) _(powers Cloud9)_
- [Monaco](https://microsoft.github.io/monaco-editor) _(powers VS Code)_
- [CodeMirror](https://codemirror.net)
- More at https://en.wikipedia.org/wiki/Comparison_of_JavaScript-based_source_code_editors

**Comment by penge** [comment]
I have checked [pell](https://github.com/jaredreich/pell) and [pen](https://github.com/sofish/pen) and basic functionality doesn't seem hard.

I'll be adding a custom implementation.

The features would be:

- bold
- underline
- italic
- strikethrough
- Heading 2
- Heading 3
- paragraph
- Unordered list
- Ordered list

## Screenshots

![styles](https://user-images.githubusercontent.com/907255/77410003-87eca900-6dba-11ea-97ef-d34550bcc0f6.png)

![article](https://user-images.githubusercontent.com/907255/77410066-a2bf1d80-6dba-11ea-87bc-23e5c2d32f5c.png)

![todo](https://user-images.githubusercontent.com/907255/77410078-a9e62b80-6dba-11ea-9d76-c0d68beaca51.png)

**Comment by penge** [comment]
Here is an update.

# Dark

![dark](https://user-images.githubusercontent.com/907255/77547456-82bc5680-6ead-11ea-98ac-9148bd7b7c0b.png)

<br>

# Light

![light](https://user-images.githubusercontent.com/907255/77547466-87810a80-6ead-11ea-9455-e7ea69c02917.png)

<br>

## Toolbar

**Toolbar allows you to set:**

- Bold
- Italic
- Underline
- Strikethrough
- Heading 2
- Heading 3
- Paragraph
- Horizontal rule
- Unordered list
- Ordered list

Some actions can be done with a shortcut as well:

- `CTRL+B` for Bold
- `CTRL+I` for Italic
- `CTRL+U` for Underline

Styles can be combined, like Bold + Underline.

<br>

## Status

**At this point all is implemented.**

_Notes:_

- _Changes in design can be done during the testing (margins, paddings, icons, location of the toolbar, etc.)_
- _For presentation purposes, I've added an empty line above the first line in the pictures_
- _I also used a bigger font as usual_
- _The used font was Roboto_
- _To rename a note, at any point, right-click on the note_

**Comment by penge** [comment]
I find the always visible **toolbar** to be little distracting to the content. The **toolbar** could be either:

A) moved somewhere else (like to the bottom), or,
B) it could be floating (somewhere called bubble) and displayed only when needed (like the text is selected)

Here's a screenshot to B:

![floating](https://user-images.githubusercontent.com/907255/77561474-07fc3700-6ebf-11ea-9ab2-4d3a1373d48e.png)

**Comment by bhupesh-sf** [comment]
When is it coming?

**Comment by penge** [comment]
Hi @bhupesh-sf 

During today/tomorrow I plan to update all issues related to 3.0. They will be closed and a new issue will be created regarding the private testing. You are as well invited.

I'd like to release My Notes 3.0 during this week.

**Comment by bhupesh-sf** [comment]
Awesome. Looking forward to it :+1:

**Comment by bhupesh-sf** [comment]
@penge Maybe not for now but have an option to add tables in notes will be great.

**Comment by penge** [comment]
@bhupesh-sf 

I have created a new issue for Tables. I'll try my best to add this in near future.

**Comment by bhupesh-sf** [comment]
Awesome. Thanks for being so quick :+1:

**Comment by penge** [comment]
Welcome! 🙂👍

**Comment by penge** [comment]
@bhupesh-sf 

I have received something I need to do first (not regarding My Notes). Need to postpone the testing and the release. New dates would be:
- testing at the end of the week (testing will take approximately 1 week)
- release in the beginning of May

I will keep you updated!

**Comment by bhupesh-sf** [comment]
Ok, eagerly awaiting :)

**Comment by penge** [comment]
_Implemented. Closing. Proceeding to testing._

**Tables** will be in future.

**Comment by penge** [comment]
Hi @bhupesh-sf
Just letting you know I am proceeding with testing.
If you'd like to join the testing, see **https://github.com/penge/my-notes/issues/76**
In the beginning of May I'd like to release My Notes 3
