### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by penge** [penge/my-notes#73]
A new editor in My Notes 3.0 (see https://github.com/penge/my-notes/issues/72) can be improved to support **Tables**.

Required functionality:

- Insert a new table

- Modify the table size in the following ways:

  - Insert row above
  - Insert row below
  - Insert column left
  - Insert column right
  - Delete row
  - Delete column

<br>

- Set Heading row(s) and/or Heading column(s)

**Comment by bhupesh-sf** [comment]
I believe this should be the next one after custom theme. Will help greatly to manage notes.

**Comment by penge** [comment]
Yes.

**Comment by penge** [comment]
@everybody There's a ton of work around Tables, so I'd like to know first your opinion, who needs this.

**Comment by bhupesh-sf** [comment]
@penge Any plan of working on this?

**Comment by penge** [comment]
@bhupesh-sf Almost done.

**Comment by penge** [comment]
Preview below.

### Inserting a new table

![table_insert](https://user-images.githubusercontent.com/907255/86608521-f5f45f00-bfaa-11ea-9212-fccebc9d99a4.gif)

### Setting a heading row (can also set a column)

![table_heading](https://user-images.githubusercontent.com/907255/86608902-6dc28980-bfab-11ea-9bce-4632216d27cb.gif)

### Adding a column, a row, or both

![table_add_row_column](https://user-images.githubusercontent.com/907255/86609201-e45f8700-bfab-11ea-91f2-ecfd668e0cda.gif)

### Deleting a column or a row

![table_delete_row_column](https://user-images.githubusercontent.com/907255/86609777-b9296780-bfac-11ea-8591-b910e4a7c360.gif)
