### ISSUE TITLE
Insert images to the note

### ISSUE THREAD

**Issue by penge** [penge/my-notes#74]
Editor in **My Notes 3** can insert any arbitrary HTML. Meaning, if you find an image on the internet you'd like to insert, like a picture of a cake:

<img width="381" alt="Screen Shot 2020-04-26 at 2 51 23 PM" src="https://user-images.githubusercontent.com/907255/80308124-69206e80-87cd-11ea-9f23-9e5a6dc382c1.png">

Simply **right-click** on the image and select **"Copy Image"** from the dropdown.

Then, in My Notes **right-click** and select **"Paste"**.

## Result

![image](https://user-images.githubusercontent.com/907255/80308192-ccaa9c00-87cd-11ea-86e8-0a359451bde0.png)

This issue is created to primarily let you know this is possible.
And possibly to have a discussion how this could be improved, like providing a picture's URL and having it inserted.

**Comment by bhupesh-sf** [comment]
@penge This was the next request I was about to add but found its already closed. Does this mean we are not going to implement it?

**Comment by penge** [comment]
It is possible to have in future. At this point it's not a priority. The only easy solution is to use obsolete `execCommand`. I would wait if there is a better solution to the existing uses of `execCommand` and replace them first, if possible.
