### ISSUE TITLE
Testing My Notes 3 (you are invited!)

### ISSUE THREAD

**Issue by penge** [penge/my-notes#76]
**My Notes 3** is almost here!

I am now testing the new features — it would be great if you could join! 

Here's how you could help out with the **testing**:
- to confirm the functionality
- to experience the UI/UX and provide feedback

See **Testing Checklist** for details.

### My Notes 3

- can **Create** / **Rename** / **Delete** the notes **(https://github.com/penge/my-notes/issues/64, https://github.com/penge/my-notes/issues/66)**
- improved **Editor** that supports **HTML** and an easy way to insert bold, italic, underline, strikethrough, Heading 2, Heading 3, paragraph, horizontal rule, unordered list, ordered list **(https://github.com/penge/my-notes/issues/59, https://github.com/penge/my-notes/issues/72)**
- **Google Drive** backup with automatic two-way sync (on every open, close, refresh of My Notes), which uploads new and edited notes to Google Drive, and downloads new and edited notes from Google Drive **(https://github.com/penge/my-notes/issues/53)**
- better integration with the browser, which comes down to:
  - **name** of the open note is displayed in the browser's **Tab** **(https://github.com/penge/my-notes/issues/65)**
  - **Back/Forward** buttons (or associated shortcuts) can navigate between last open notes **(https://github.com/penge/my-notes/issues/69)**

### Testing Checklist

Here's a list of things to test, which is also a detailed list of the new features. Any additional playing around is very welcome.

**Create / Rename / Delete**

1. Can **create** a new note (see **New note** button)

    - new note is added to the _NOTE_LIST_ in an alphabetical order; also in every other open My Notes tab _NOTE_LIST_
    - new note name needs to be unique – creating a note with the name taken by an existing note should not be allowed

2. Can **rename** the note (see **three dots** button)

    - can rename the note from the _NOTE_LIST_

        - while renaming the note, it should be highlighted in **blue**
        - after the note is **renamed**, the name should be updated, tiles should be updated in an alphabetical order; renaming should be applied in every open My Notes tab _NOTE_LIST_ and _NOTE_DETAIL_ for the same note
        - note should _NOT_ be **renamed** if the new name is taken by an existing note

    - can rename the note from the _NOTE_DETAIL_

        - while renaming the note, it should be highlighted in **blue**
        - after the note is **renamed**, the name should be updated; renaming should be applied in every open My Notes tab _NOTE_LIST_ and _NOTE_DETAIL_ for the same note
        - note should _NOT_ be **renamed** if the new name is taken by an existing note

3. Can **delete** the note (see **three dots** button)

    - can delete the note from the _NOTE_LIST_

        - while deleting the note, it should be highlighted in **red** and proceed only if you type **"delete"**
        - after **deleted**, it should be removed from the _NOTE_LIST_; also from every other open My Notes tab _NOTE_LIST_ and if in _NOTE_DETAIL_, it should jump to an updated _NOTE_LIST_

    - can delete the note from the _NOTE_DETAIL_

        - while deleting the note, it should be highlighted in **red** and proceed only if you type **"delete"**
        - after **deleted**, it should jump to an updated _NOTE_LIST_; also update every other open My Notes tab _NOTE_LIST_ and if in _NOTE_DETAIL_, it should jump to an updated _NOTE_LIST_

    - creating a new note with the name as deleted one should be possible

**Editing**

4. The new **Editor** can style the content, or insert the elements

    - buttons for bold, italic, underline, etc., should apply the style, or insert the element
    - keyboard shortcuts should work too after selecting a text, like `CTRL+B` for bold
    - styles can be combined, such as bold + italic

5. Editing the note content is **synchronized** across the other My Notes tab(s)

    - changing the note content should be updated after 1 second in every other open My Notes tab _NOTE_LIST_ and _NOTE_DETAIL_ for the same note

**Browser integration**

6. The title in the browser's **Tab** should change accordingly:

    - when in _NOTE_LIST_ to **"My Notes"**
    - when in _NOTE_DETAIL_ to note's **name**

7. Can use **Back/Forward** buttons (or associated shortcuts) to navigate between the recently open notes

    - if the note in the history was meanwhile renamed or deleted, navigating to it should open _NOTE_LIST_

**Google Drive**

8. **Google Drive** in **Options** does the following:

    - after **enabled**:
        - My Notes folder is created in your Google Drive – if it doesn't exist; and if it exists – existing folder should be used
        - it should display a link next to **"Backup location:"**; when clicked, it should open in the new tab newly created or existing My Notes folder in your Google Drive
        - your notes should be immediately uploaded to **Google Drive / My Notes**
        - Time of sync should be displayed next to **"Last sync:"**
        - _NOTE_LIST_ should have **"Sync Now"** button displayed, with **"Last sync:"** and **"Open in Google Drive"**
        - if enabled from a second computer, existing notes should be downloaded

    - after **disabled**:
        - it should remove the link next to **"Backup location:"**, remove the time next to **"Last sync:"**
        - _NOTE_LIST_ should have hidden **"Sync Now"** button, **"Last sync:"**, **"Open in Google Drive"**
        - uploaded notes should stay if Google Drive

9. When My Notes is **_Open/Closed/Refreshed_**, or **"Sync Now"** is clicked, following should happen:

    - towards Google Drive

        - notes that are new, are **uploaded** creating a new file
        - notes that are updated, are **uploaded** updating the existing file

    - towards My Notes:

        - files that are new, are **downloaded** as new notes
        - files that are updated (manually in Google Drive, or from other computer's My Notes), are **downloaded** and update the content of the note

    - if **Google Drive / My Notes** folder is deleted by you, the synchronization should stop (and hide/reset the elements related to the synchronization)

    - if **Google Drive** in **Options** is disabled, the synchronization should stop (and hide/reset the elements related to the synchronization)

### Testing Members

```
# MEMBERS

A=penge (me)


# RESULTS

    A
1   +
2   +
3   +
4   +
5   +
6   +
7   +
8   +
9   +

-   => not tested
!   => not working
+   => working 
```

I have tested all, but will do again.

### How to join

If you'd like to join, simply let me know here. I will soon prepare the branch with a commit we will be testing.

1. Let me know
2. Checkout the code
3. Install My Notes
4. Send me your My Notes installation ID, example: **ofdfapdmkkhenkgihklcdcmjbfkdojci**
5. I'll create for you a **Client ID** in Google Cloud Platform, and send it back to you
6. Put the **Client ID** in `manifest.json` and reload My Notes
7. Proceed with **Testing Checklist**
8. Send me back your results / feedback

Before the testing starts, the source code will be freezed and the branch / commit ID will be provided.

**Comment by penge** [comment]
Isn't that a coincidence that My Notes 3 has 3000 new lines of code?

**Comment by bhupesh-sf** [comment]
@penge I am sorry because I am through a project delivery and super busy this and next week. Will see if get sometime on weekends.

**Comment by penge** [comment]
@bbb651 No worries. I'll handle it.

**Comment by penge** [comment]
@bhupesh-sf No worries. I'll handle it.

**Comment by penge** [comment]
I have found out synchronization of the notes (mainly due to renaming) will require some bigger changes.

I'll post here once it is done.

**Comment by penge** [comment]
It is now reimplemented. Works Great!

**Details:**

- renaming a note in My Notes, will rename the file in Google Drive
- renaming the file in Google Drive, will rename the note in My Notes
  - `special case 1` – Renaming **"Clipboard"** is not allowed in My Notes, but if done in Google Drive, let's say renamed to **"CopyAndPaste"**, it will **unlink** **"Clipboard"** note, meaning, it will upload a new file **"Clipboard"** to Google Drive, and download **"CopyAndPaste"** file and create a new note with the same name for it
  - `special case 2` – This is very similar to the first case. Renaming any file in Google Drive to **"Clipboard"** will **unlink** the note connected to that file.

When My Notes is open (or closed, or refreshed), it will:

1. **Pull** any changes **_FROM_ Google Drive** (changes made in Google Drive directly or via other My Notes, like from a second computer), which are:
  
    - create new notes
    - update notes (their names and/or content)
    - delete notes

2. **Push** any changes **_TO_ Google Drive** (so they have a backup, and can be received by My Notes in a second computer), which are:

    - create new files
    - update existing files (new name and/or content)


If a note is **deleted** in My Notes, it will be deleted from Google Drive instantly. This prevents downloading the file as a new note during the **Pull**.

If a note is edited or deleted in Google Drive, the previous content cannot be seen in My Notes. This is a security setting in case someone would sit behind your computer.
Previous version of a note can always be seen in Google Drive via a **Version history (Revisions)**.

All the sensitive operations for the **Pull** and **Push** are supported with tests. My Notes 3 is completely rewritten. Using JavaScript modules (native support since Chrome 61).

There is no intermediate step before publishing My Notes, which was a huge priority for me to keep it that way. This means, there is no code minification which would obscure readability or allow to hide something, and no code transpiling which would result in a different looking code.

The source code found here on GitHub is a 100% match of what you would see when My Notes is installed. That will greatly improve openness, contributions, testing.

The goal is to be lightweight Google Docs for Notes, directly in a new tab, which is now one step closer.

**Comment by bhupesh-sf** [comment]
Awesome, so when is it going to be published, super eagerly waiting :+1:

**Comment by penge** [comment]
I will add **"Sync Now"** button to have that option. Especially if working between computer A and B, when want to be sure everything is synced before signing off.

I will also add **"Time of last sync"** information.

Then, I test it again, ask some to join the testing.  If no surprises, I finish up the documentation and add a screenshot. I will let it "settle" for a few days by using it.

I think **Next Monday (May 11th)** can be the official day to publish. Not a day later. Ideally the same day, or maybe during that week, it will be approved by Web Store and available to others. I'll write them an email just to be sure it won't take long.

**Comment by bhupesh-sf** [comment]
@penge Can we expect this to come out tomorrow?

**Comment by penge** [comment]
Hi @bhupesh-sf Here, yes. On Web Store, maybe. Sometimes it takes many days.

**Comment by penge** [comment]
**Thanks!!** to following, who helped me by sending a feedback on the upcoming **README.md**.

- @fatosmorina ([FatosMorina.com](https://www.fatosmorina.com))
- @JeromeDeLeon
- @jmaicaaan

**Comment by penge** [comment]
I have to move the release, hopefully **May 20**. Found a bug. Details:

1) Computer A = I sync the note, then change its name from **ABC** to **Article** but don't sync yet.

2) Computer B = Here I edit the same note and change its name from **ABC**, to **Article**, or **something else** (and may or may not also change the content), and also hit **"Sync Now"**.

3) Computer A = There is a problem because the previously linked **ABC** points to a note **Article**, but this has already been renamed in Computer B.

Need to handle these silly usecases, when editing the same note at the same time in both Computers A and B, either renaming only, or changing the content as well.

**The resolution:**
- rename the linked name from **ABC** to **{whatever name set from Computer B}**
- rename the note as well, if it doesn't match the previously linked **ABC**
- to merge the content (not only name could have been changed, but also content)

**Comment by penge** [comment]
![image](https://user-images.githubusercontent.com/907255/82266243-7a424280-9969-11ea-9298-c8eb7f079527.png)

![image](https://user-images.githubusercontent.com/907255/82266285-96de7a80-9969-11ea-8295-ce0019f9bf4e.png)

![image](https://user-images.githubusercontent.com/907255/82266266-8a5a2200-9969-11ea-9ce3-8821a74c2c76.png)

![image](https://user-images.githubusercontent.com/907255/82266636-7fec5800-996a-11ea-83b5-3f6b7e89e88e.png)

<br><br><br>

**Very soon.**

**Comment by penge** [comment]
## Release

Today (May 20) around 9 am California time.

**Comment by penge** [comment]
**My Notes 3** is now in pending review on Web Store. Let's wait.

And, Thank you for all the support !!! 🙂 👍

**Comment by penge** [comment]
My Notes can now run offline (it could even before!) but now it's also stated in Web Store.

![image](https://user-images.githubusercontent.com/907255/82492093-ef3a8700-9ae5-11ea-9232-fe6e7c31cdd9.png)

Pending review.

The good things is, it can run offline even when Google Drive Sync is enabled - it won't collapse! 😃

Once online, it "shakes" up and can continue the synchronization. 💪😁

**Comment by jmaicaaan** [comment]
Congrats!!! Let's wait for it to be published.

**Comment by penge** [comment]
I have 2-3 new features that might be great! Creating new issues for them now.
