### ISSUE TITLE
Integrate to address bar! (Maybe?)

### ISSUE THREAD

**Issue by penge** [penge/my-notes#80]
How about jumping into any note just by typing **"mn"** + Tab? (or Space)

![omnibox](https://user-images.githubusercontent.com/907255/82508915-cd053100-9b06-11ea-80e8-de330b133da4.gif)

This could possibly be used for much more. Jumping into Google Drive. Saving note to a clipboard. Etc.?

I think **https://github.com/penge/my-notes/issues/79** can be WAY FASTER and more functional. It would go like this:
- `Cmd + Shift + M` to quickly open My Notes,
- then start typing to jump into note!

**Comment by bhupesh-sf** [comment]
This one is really awesome. Many thumbs up for this :+1: :+1: :1st_place_medal:

**Comment by penge** [comment]
Thanks @bhupesh-sf I will consider adding this in near future.

**Comment by penge** [comment]
There is a slight **limitation**. The default suggestion can only be 1. And so to get list of all notes, I need to type **"mn"**, then `Tab` and then 1x `Space` (need to change the input to get the results). I find the last step with `Space` to be very inconvenient.

Giving this some time, but seems it will be better to close.

**Comment by penge** [comment]
Closing.
