### ISSUE TITLE
Allow custom theme color

### ISSUE THREAD

**Issue by bhupesh-sf** [penge/my-notes#81]
Hey @penge 

It will be good if we can allow not just light or dark but also to choose a color. I like dark theme but with a little variation (as I do on my code editors). Total black is not so cool but dark with some variation.

Just for example https://carbon.now.sh/ has select theme option. Maybe not selection like this but allow to choose a color and set that as a background.

Thoughts??

**Comment by penge** [comment]
I find it quite useful as well. Having more variety and common colorschemes to match with the OS — I am in!

Let's add **_ALL_ (Yes, AAAAALL)** the themes listed **Carbon!** 🤩🎇
This is _not_ a complication.

**Comment by bhupesh-sf** [comment]
In my email I got the comment before editing :P. Adding here for your reference ;)

> I find it quite useful as well. Having more variety and common colorschemes to match with the OS — I am in! 
Let's add ALL (Yes, AAAAALL) the themes listed Carbon! 🤩🎇
This is not a complication.

Not sure why you changed the comment? Is there really any difficulty in it?

**Comment by penge** [comment]
Wait about an hour. I'll update the options here.

**Comment by bhupesh-sf** [comment]
Ok, thanks for quick response.

**Comment by penge** [comment]
The best option would be to have:

```
- Light
- Dark
- Custom    <------ NEW
```

There are many colorschemes that adding them woudn't make sence (the customization would still be limited). There would be a complete customization instead, but made easy as possible to get through. There would also be a way to customize just about everything.

When you click **Custom**, you would jump into a new window. Here's how it can look:

<br>

## My Notes Custom Theme

```css
:root {
  /* Change Background Color */
  /* --background-color: rgba(40, 40, 40); */

  /* Change Text Color */
  /* --text-color: rgb(255, 255, 255); */

  /* Change Border Color */
  /* --border-color: silver; */

  /* Hide Toolbar */
  /* --toolbar: none; */

  /* Change Toolbar Size */
  /* --toolbar-size: .5em; */

  /* Move Toolbar to the Right */
  /* --toolbar-position: flex-end; */

  /* Move Toolbar to the Center */
  /* --toolbar-position: center; */
}

/* Place any custom CSS */
```

There would be two buttons. **Save** and **Reset**.

**Comment by penge** [comment]
![custom-theme](https://user-images.githubusercontent.com/907255/82719115-09bc5e00-9ca8-11ea-996e-34c8d7246952.gif)

**Comment by penge** [comment]
![image](https://user-images.githubusercontent.com/907255/82720078-7d626900-9cb0-11ea-8d09-0c9821bf995e.png)

**Comment by penge** [comment]
![image](https://user-images.githubusercontent.com/907255/82720083-88b59480-9cb0-11ea-9483-c819f6e42add.png)

**Comment by penge** [comment]
There is a possibility of adding one more built-in theme. That would be "Dark", and the current "Dark" would become "Black". The idea would be to match Dark theme in OSX.

![image](https://user-images.githubusercontent.com/907255/82743244-f4f3cf00-9d68-11ea-80bc-a98b5c0678d9.png)

In OSX, the background for the Dark theme is `rgb(53, 54, 58)` also as `#35363a`. The new "Dark" theme would be just a bit lighter to match that.

So, what do you think guys, would you welcome this updated "Dark" theme? Where the current "Dark" would be renamed to "Black". Do you use OSX?
@JeromeDeLeon @bhupesh-sf @soul-ride @jmaicaaan

## Preview

![image](https://user-images.githubusercontent.com/907255/82743531-f2937400-9d6c-11ea-9077-34c715a2759f.png)

![image](https://user-images.githubusercontent.com/907255/82743539-05a64400-9d6d-11ea-82a3-f1b5525cc2d6.png)

**Comment by JeromeDeLeon** [comment]
I would love to. Although I'm not using OSX. 👍👍

**Comment by soul-ride** [comment]
I'm on Windows but I totally support this idea. That was actually my initial suggestion for dark theme (on the chrome webstore comments) :)

**Comment by JeromeDeLeon** [comment]
What about the dark theme of github?

**Comment by penge** [comment]
@soul-ride Great! :) Can you please check what is the New Tab background color in Windows Dark mode?

@JeromeDeLeon Just checked the `GitHub Dark Theme` and there is `rgb(36, 41, 46)` which is a slightly different color.

Now the question is, if every major OS has same background color, or slightly different. Well, even if different, at least OSX could be covered.

**Comment by JeromeDeLeon** [comment]
I don't think we need to cope up with every dark mode of every OS. Matching OSX is fine for me 😁

**Comment by penge** [comment]
OK 😁

3.0.2 will be here tomorrow! 🤩

**Comment by jmaicaaan** [comment]
Adding the custom theme is great! I think we can just remove black if we will to replace it with dark theme. I think black and dark somehow the same just different variation on some parts. I guess if you want different variation based from the available, use custom.

**Comment by penge** [comment]
@jmaicaaan I have to agree on this. I was trying out this Dark theme mainly to match osx dark theme background (because if it matches, it can be done so there is no flicker in the background color change - either from white to dark, or in this case from dark to different variation of dark).

I would say the best version is this: https://github.com/penge/my-notes/issues/81#issuecomment-632974217

And any dark or light variant could be done just via Custom. Makes more sence too. Otherwise there could be Light, Lighter, Darker, Almost Dark, Not Pink Black Orange :D 

Let's keep it simple. Anyway, there will be "Dark", but not explictly, better if under Custom. So it's clean simple.

**Comment by penge** [comment]
<img width="537" alt="Screen Shot 2020-06-01 at 7 23 23 PM" src="https://user-images.githubusercontent.com/907255/83436010-6f91ae00-a43d-11ea-97c8-349053757977.png">


<img width="622" alt="Screen Shot 2020-06-01 at 7 26 08 PM" src="https://user-images.githubusercontent.com/907255/83436224-c4cdbf80-a43d-11ea-8348-e514bb733e14.png">

<br>

^^ Update on how it will look like. Any setting is autosaved / autoapplied. Settings are also migrated to future versions.

Color selection is an HTML5 color input (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color)
Color can be set in these formats: RGB, HSL, HEX.

**Comment by bhupesh-sf** [comment]
I believe this is really awesome. Some presets will be even good. But to begin with this is really good.

**Comment by penge** [comment]
@bhupesh-sf Custom themes are **DONE!!!!!!!** Next version next week.

**Comment by bhupesh-sf** [comment]
Awesome, waiting for it :+1:
