### ISSUE TITLE
Need content alignment option 

### ISSUE THREAD

**Issue by bhupesh-sf** [penge/my-notes#83]
Having the option to aling the content left, middle, right is good user experience. Considerting we have bold, italic etc HTML options, I believe this can be achieved as well and helps us to manage notes better.

Thoughts??

**Comment by penge** [comment]
Nice idea!

I shall add 3 new icons for the alignment:

- **Left**
- **Center**
- **Right**

Expect in the next version.

**Comment by penge** [comment]
I'll be checking this soon. With **Custom** theme, those would be only two additions to 3.1. **Custom** being a big one.

**Comment by bhupesh-sf** [comment]
Awesome. Custom theme is really cool thing, gives lots of control over the theme to the end user and content alignment is good for good content management. :+1:

**Comment by penge** [comment]
Hi @bhupesh-sf What do you think?

![align](https://user-images.githubusercontent.com/907255/82930266-65773780-9f85-11ea-82bf-b00db70ecdab.gif)

Works on individual lines, or whole text ;)

**Comment by penge** [comment]
Step 2: **All together**

<img width="933" alt="Screen Shot 2020-05-26 at 7 54 30 PM" src="https://user-images.githubusercontent.com/907255/82933833-da00a500-9f8a-11ea-8e3c-77680a745a73.png">

**Comment by penge** [comment]
<img width="795" alt="Screen Shot 2020-05-26 at 8 45 21 PM" src="https://user-images.githubusercontent.com/907255/82938302-e0464f80-9f91-11ea-8151-885dbad67899.png">
<img width="795" alt="Screen Shot 2020-05-26 at 8 45 16 PM" src="https://user-images.githubusercontent.com/907255/82938304-e0dee600-9f91-11ea-92e6-4276a004954b.png">
<img width="795" alt="Screen Shot 2020-05-26 at 8 44 58 PM" src="https://user-images.githubusercontent.com/907255/82938306-e1777c80-9f91-11ea-8872-40ad9b5a8d87.png">


Considering to hide the controls unless start using them.

**Comment by penge** [comment]
How about this:

<img width="835" alt="Screen Shot 2020-05-26 at 9 54 16 PM" src="https://user-images.githubusercontent.com/907255/82944423-7a5ec580-9f9b-11ea-81d4-e7b4fccad9d1.png">

**Comment by penge** [comment]
**Edit:**

In progress...

**Comment by JeromeDeLeon** [comment]
I'm fine with the icon because they are not noticeable in light theme.
I just also noticed that it when clicking one of it, it will not highlight the selected tools like bold, italic, etc. It would be great to also add that :)

**Comment by jmaicaaan** [comment]
Not specially related to these options. What do you guys think about making the "tab" works like how it works on other places (i.e. Notes - mac app, code editors, Google docs)?

**Comment by penge** [comment]
@JeromeDeLeon Sounds cool! Something like this? ;)

<img width="911" alt="Screen Shot 2020-05-27 at 3 12 58 AM" src="https://user-images.githubusercontent.com/907255/82965296-fec73d80-9fc7-11ea-970d-6c4178f3c7b8.png">


@jmaicaaan Definitely next to do. Tab could have two behaviors a) insert whitespaces, b) jump to adress bar and back. What do you think should be the default? I would say let's make default b), as articles and notes are majority and there, I don't find it so common? hmm?
Tab function could be either changed from Options, or through a button in the toolbar. Propably toolbar.

**Comment by JeromeDeLeon** [comment]
Yes, something like that. You could invert that for dark theme.

**Comment by penge** [comment]
Yep. It would basically use the same style as for on mouse hover. In the case of dark theme, a little subtle change:

<img width="256" alt="Screen Shot 2020-05-27 at 3 27 34 AM" src="https://user-images.githubusercontent.com/907255/82965987-08ea3b80-9fca-11ea-8097-2505062b00a7.png">

**Comment by penge** [comment]
I am surprised mac's TextEdit doesn't have **backward** indent :D but as it inserts tab character, backspace does the job :D

Alright, so we can have Tab pretty soon. Just need to figure out where to put the option... maybe in Options page? Like this?

**[x] Insert Tab with the Tab key**
If enabled, Tab key will insert a Tab character.
If disabled, Tab key will jump between the content and address bar.

![tab key](https://user-images.githubusercontent.com/907255/82968457-a98e2a80-9fcd-11ea-8fe1-b4d780cebf93.gif)

@jmaicaaan  Soon! :D

**Comment by penge** [comment]
![screely-1590546830405](https://user-images.githubusercontent.com/907255/82971736-b3b32780-9fd3-11ea-9658-ee646d285020.png)

^^^ New preview!

**Comment by penge** [comment]
Or this one?

![screely-1590547629161](https://user-images.githubusercontent.com/907255/82972425-4ef8cc80-9fd5-11ea-9912-98e7c8460e82.png)

**Comment by jmaicaaan** [comment]
Awesome tab support! 🎉
