### ISSUE TITLE
Option to set "Clipboard" as default note

### ISSUE THREAD

**Issue by soul-ride** [penge/my-notes#85]
Request to add an option to set "Clipboard" note as default one so you don't need to drill-down into it. Current implementation (table with note previews) adds unnecessary interactions (aim to the note preview + click).
Previous implementations were perfect (clickable page number in bottom corner or absence of paging at all).

**Comment by penge** [comment]
I guess I got cought with overcomplicating things this time (like which features accept, which deny). And sometimes less is more.

To your question. The note that is open before closing (Clipboard or other), is open on the next visit. That could help to get more quickly into same note.

<br><br>

`Cmd + [` and `Cmd + ]` could be used to quickly jump between recently open notes, but this works only per session  and is reset on next visit. Opening My Notes could be faster like with `Cmd + Shift + M` which can be set in `chrome://extensions/shortcuts` under **Activate the extension**.

Those are just some tips to get into notes faster, or navigate between them faster. But still.

<br><br>

I am considering to get the things back to where they were — depends on the feedback. This is what I would do. Drop the whole previews page, fu$k that. In the bottom right, where before was 1/3, 2/3, and 3/3, would be now the note name, if it's **Clipboard** or 1 or 1/3, any name this time.
Click on the note name would loop between the notes or rollup the selection. ~On the right to the note name would be 3 circles button, to rename or delete.~ << No. That could cause missclicks (note name VS some button), instead, context menu.
And on the bottom left, the opposite side, there would be timestamp of Last sync. No Sync Now button. No shit like that. The click on the timestamp would change from timestamp to Syncing..., and once done, it is synced and timestamp is back. To open in Google Drive, there could be very small icon in bottom left, left to the timestamp. Something like this:

```

       text


__________________
1 2              3


1 - Google Drive icon, I click it, I am in Google Drive
2 - Timestamp of Last sync, it goes automatically but if I click it,
    it changes to "Syncing..." and once done, the timestamp is back

3 - Note name. I click it, note list rolls above, on top of each other.
    I select the note to open. OR! it just loops between the notes and if I have them many, I hold down `Cmd` or something to open the selection (the selection slows things down, moving mouse around)
  - `Cmd + [` and `Cmd + ]` could also loop between notes, at any time, not just current session. 
  - If I right click, I have context menu to Rename, Delete
```

This is a very first sketch on how the things could be back to simple. What do you think?

**Comment by soul-ride** [comment]
> The note that is open before My Notes is closed, is the note that is open on next visit.
It works when you open 1 new tab and close it. When you open 2+ new tabs, close them and then open new tab again, it returns back to the main screen.

As for the suggestion about features (GT      E        O), I personally would keep features to minimum (1 note, text size change, background change, drive sync, that's it).

**Comment by penge** [comment]
Cool. Found the problem. It happend that the second tab didn't really know, if the missing value means "it is already saved", or "it should go to the main page".

**Having a fix on the go.** Should be here soon, after 3.0.1 is approved (in pending review now).

Regarding other changes, what do you think about this?

<img width="552" alt="Screen Shot 2020-05-21 at 11 45 26 PM" src="https://user-images.githubusercontent.com/907255/82609651-35164e80-9bbd-11ea-8ac1-ddba52e52604.png">

Now, imagine you would move the mouse on **Clipboard** (no click needed).

<br>

<img width="552" alt="Screen Shot 2020-05-21 at 11 45 22 PM" src="https://user-images.githubusercontent.com/907255/82609656-35aee500-9bbd-11ea-916f-cd79032aedc3.png">

**All notes.** Click on any note to open.

- always in A-Z order
- currently open note also in the list (so the list always looks the same and things are easier to find, remember)
- currently open note in silver (so it doesn't consume your attention)
- click on any note (silver or black), would open the note

**Comment by penge** [comment]
Regarding quick navigation, now there is an upcoming solution. https://github.com/penge/my-notes/issues/87

**Comment by penge** [comment]
My Notes 3.0.1 is approved. This can go out today as part part of 3.0.2.

**Comment by penge** [comment]
@soul-ride I am thinking if it would make sense, to have an option, to always open Clipboard note on next visit, even if other was open before closing.
The option, if enabled, would **override** the default behavior "open last open on next visit".
@soul-ride ? @JeromeDeLeon @jmaicaaan

**Comment by soul-ride** [comment]
I personally using only a single note (clipboard). Proposed option is nice to have as an addition, but I don't think it should replace "open recent note" functionality.

**Comment by penge** [comment]
Cool. I would say then, better not to add this option, it would clash with the "open recent note".
