### ISSUE TITLE
Jump between notes with hotkeys

### ISSUE THREAD

**Issue by penge** [penge/my-notes#87]
![carret](https://user-images.githubusercontent.com/907255/82629610-8b50b500-9bf0-11ea-8ee3-f546305c1107.gif)

Can't be much faster than that

Works with `Cmd + [` and `Cmd + ]` and other OS variants would come. Suggestions? what keys you would like to use?

Also, carret is always at the end, ready to type

**Comment by soul-ride** [comment]
Suggestion for the multiple notes implementation:
- Add notes list to the left or right corner of the screen.
- It could be titles or snapshots (similarly to what's already displayed on the main page)
- One of the notes is always opened (and selected in the list), there is no separate screen for notes list. 
- "Clipboard" is opened on start. After that recently selected note is opened by default. 

I see it similarly to the tabs and tab previews in MS Edge browser, but on the left/right side of the screen.

**Comment by penge** [comment]
Sounds cool. What would you say, if this **Sidebar** is _not_ always visible, but can be **toggled** with:
- `Cmd+S` (Sidebar) and `Cmd+B` (like in VSCode)

This would **toggle** the sidebar quickly. If the preference would be to have the sidebar visible at all times, just leave it open, as this would be remembered on the next visit.

Some details:
- Sidebar would be visible by default, unless hidden by the user (setting remembered on future visits)
- Sidebar would be on the Left (or Right), as set in the Options
- Previews page wound no longer be needed. Move the mouse over the note to immediatelly see its preview in main area (this would be set back to the active note after the mouse leaves the Sidebar). Click any note to open it.

What do you think?

**Comment by soul-ride** [comment]
Sounds awesome ))

**Comment by penge** [comment]
![image](https://user-images.githubusercontent.com/907255/82720158-12656200-9cb1-11ea-99f6-96a831f005bb.png)
