### ISSUE TITLE
Get back to the last active tab

### ISSUE THREAD

**Issue by penge** [penge/my-notes#90]
Imagine this workflow. This 4-step loop.

1. You are on some page
2. You quickly open My Notes (`Cmd + Shift + M`) (new tab is added to the end)
3. You paste something
4. You close My Notes

As by default browser's behavior, finishing step 4 would activate the tab placed before it (on the left).

**Proposal:**
How about, if finishing step 4 would get you back to the tab from the step 1? Isn't it something you would naturally expect to happen? Would it make you more productive using the Clipboard?

If during the step 3 you would focus some other tab or some other app for a moment (and therefore break the chain), finishing the step 4 would _NOT_ go back to the step 1, and follow the default behavior instead.

**Comment by penge** [comment]
What do you think guys!

@bhupesh-sf @JeromeDeLeon @jmaicaaan @soul-ride

**Comment by soul-ride** [comment]
Current behavior for me in Chrome browser on Windows is the one which is proposed - when I close My Notes I always returned to the tab where I was before (not the one before new tab). That's preferred behavior. I open new tab with CTRL+T though.

**Comment by penge** [comment]
You are right. `CTRL+T` works just as expected (goes back to previous active tab). I think it could be great, if `CTRL+SHIFT+M` and closing, would do the same (used when new tab replace is off).

**Comment by penge** [comment]
The purpose is to emulate the same behavior, that comes with `CTRL + T` even on `CTRL + SHIFT + M`. I believe this is so important, that it should be part of the API, so any extension could benefit from it.

**Comment by penge** [comment]
This would require setting `openerTabId` and having `tabs` permission at all times. If the new tab loses focus, the step 4 shouldn't be applied. As sessions might be longer than a fast `CTRL C/V`, it might get confusing, maybe.

Alternative fatures:
- always open as pinned
- always open as one tab only, and make `CTRL + SHIFT + M` to focus the already open tab
