### ISSUE TITLE
Use of obsolete browser API execCommand

### ISSUE THREAD

**Issue by ronshe** [penge/my-notes#93]
Copied from: https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand
**Obsolete**
This feature is obsolete. Although it may still work in some browsers, its use is discouraged since it could be removed at any time. Try to avoid using it.

**Comment by penge** [comment]
Thanks @ronshe. My guess is, it will be years until the API is removed.
But definitely will be looking how to do it in some alternative way.

Adding a link to the list:
https://stackoverflow.com/questions/12251629/is-there-something-better-than-document-execcommand

**Comment by ronshe** [comment]
Please look at my pool request.
I added RTL<->LTR buttons. It cannot be done using execCommand so I added pretty generic code to implement style on selected objects.
The main problem was how to select the objects and only the top ones. I can explain more if you'd like.

**Comment by penge** [comment]
Thanks a lot!

There will be `3.1` released this week. After that, we can rebase this PR, or apply better solutions if available.

I will check the PR now and drop some comments.
