### ISSUE TITLE
Need to implement spell check

### ISSUE THREAD

**Issue by bhupesh-sf** [penge/my-notes#96]
While taking notes it will be good to have spell check in place

**Comment by penge** [comment]
Yes, we could have a spell-check that is built-in into the OS / Chrome.

Here's how to enable it in OSX (under **Edit** menu):

<img width="602" alt="Screen Shot 2020-06-04 at 2 07 39 PM" src="https://user-images.githubusercontent.com/907255/83754828-e660be00-a66c-11ea-8a83-03d33e3e7e1d.png">

Here's how it would work:

<img width="587" alt="Screen Shot 2020-06-04 at 2 06 04 PM" src="https://user-images.githubusercontent.com/907255/83754855-ee206280-a66c-11ea-95b4-bee8fc10817f.png">

Seems legit? There could be an option **Spellcheck** in the Options, so it can be enabled/disabled at wish, not ruled by the OS setting.

**Comment by bhupesh-sf** [comment]
@penge I am using Ubuntu and could not figure out the setting. Any idea?

**Comment by penge** [comment]
Here's a setting in Chrome.

![spellcheck](https://user-images.githubusercontent.com/907255/83874279-84b85680-a735-11ea-909a-fb319f6ae17d.png)

Setting it woudn't reflect in writing as in the screenshot above right now. It needs adding one html attribute. That could be done in next version.

**Comment by bhupesh-sf** [comment]
Cool. Will wait for that now. :)

**Comment by penge** [comment]
@bhupesh-sf This is done. Next version will be next week 😉
