### ISSUE TITLE
Can we implement Auto complete?

### ISSUE THREAD

**Issue by bhupesh-sf** [penge/my-notes#97]
I am not sure if this is feasible but while taking notes there are many words which are repeated. Can we have something like auto complete as we have in code editors?

**Comment by penge** [comment]
The easiest way would be to use [Monaco editor](https://github.com/Microsoft/monaco-editor).
It is not purpose of My Notes though, to be a code editor.

I believe extensions using Monaco already exists, if not, and there would be greater interest, I could create my-monaco, or such.

**Comment by bhupesh-sf** [comment]
@penge I was just being over ambitious thought it can be helpful. Lets see if other people also acknowledge the need of the same.

**Comment by penge** [comment]
It now supports change of **fontSize**, and **theme**.

## fontSize

![fontSize](https://user-images.githubusercontent.com/907255/83802337-d9fb5600-a6aa-11ea-9809-d9123b318d09.gif)

## theme

![theme](https://user-images.githubusercontent.com/907255/83802348-dec00a00-a6aa-11ea-9fec-c07362b8884b.gif)

**Comment by bhupesh-sf** [comment]
I don't need a code editor but a simple auto complete which saves time for repetitive words. But if its that difficult that it needs to be a seperate extension then we can leave it.

**Comment by penge** [comment]
It's not what word processors do. If Word or Google Docs, would suggest autocompletions to words such as: and, or, at, is, with, a; that would be pretty annoying.

**Comment by penge** [comment]
@bhupesh-sf do you have idea what words you would like to have auto-completed? what do you write repeatedly?

**Comment by bhupesh-sf** [comment]
@penge It's not about some specific words but depends upon note to note. E.g. When I take notes for a particular project the project name comes repeatedly and that I have to type every time. In one of my notes, I used the word consciousness which is a big word and I have to type every time, so I was thinking if I have a word already in the document and that with some mechanism can come as autocomplete.

**Comment by penge** [comment]
@bhupesh-sf 
Not fun to write "consciousness" over and over, indeed. But how does Copy/Paste the word work for you? Or, what would you say about having a bar, just like on phone, where you would see the suggested (repeated existing) words as you type?

**Comment by bhupesh-sf** [comment]
I would prefer the suggested (repeated existing) words. This is the desired behavior I am looking for.

**Comment by penge** [comment]
Let's say you would type in "c", "co", "con", and you would see the word "consciousness" in the suggestions. If it's the only word that starts with "c", then only type "c". This could be optional setting at best as I believe some might find it annoying (in shorter words) or not to be a good practice to be guided to repeat the words in a text. The question also remains, how much faster this typing experience would be, or how the suggestions would be displayed and selected quickly.

**Comment by bhupesh-sf** [comment]
I think we can put a limit, show options only when at least 3 characters have been typed.
